Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Weightage_Basement__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Weightage - Basement (Footings, Retaining Walls and Water Proofing)</description>
        <inlineHelpText>Weightage - Basement (Footings, Retaining Walls and Water Proofing)</inlineHelpText>
        <label>Weightage - Basement(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Electrification_Sanitation__c</fullName>
        <defaultValue>0.075</defaultValue>
        <label>Weightage-Electrification &amp; Sanitation %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Excavaton_of_Footings__c</fullName>
        <defaultValue>0.3</defaultValue>
        <label>Weightage - Excavaton of Footings(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Finishing__c</fullName>
        <defaultValue>0.075</defaultValue>
        <description>Weightage for Finishing (titles, Doors, QC)</description>
        <inlineHelpText>Weightage for Finishing (titles, Doors, QC)</inlineHelpText>
        <label>Weightage - Finishing(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Masonary__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Weightage for Masonary (Brickwork, Doors and Window Frames)</description>
        <inlineHelpText>Weightage for Masonary ( Brickwork, Doors and Window Frames)</inlineHelpText>
        <label>Weightage - Masonary(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_RCC_Slab_Casting__c</fullName>
        <defaultValue>0.45</defaultValue>
        <label>Weightage - RCC Slab Casting (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>RBI</fullName>
        <active>true</active>
        <label>Realty BI</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Customer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weightage_Basement__c</fullName>
        <label>Weightage - Basement(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Electrification_Sanitation__c</fullName>
        <label>Weightage-Electrification &amp; Sanitation %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Excavaton_of_Footings__c</fullName>
        <label>Weightage - Excavaton of Footings(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Finishing__c</fullName>
        <label>Weightage - Finishing (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Masonary__c</fullName>
        <description>Weightage for Masonary ( Brickwork, Doors and Window Frames)</description>
        <inlineHelpText>Weightage for Masonary ( Brickwork, Doors and Window Frames)</inlineHelpText>
        <label>Weightage - Masonary(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_RCC_Slab_Casting__c</fullName>
        <label>Weightage - RCC Slab Casting (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Type__c</fullName>
        <description>This field deterimes the weightage reference values.</description>
        <label>Weightage Type</label>
        <picklist>
            <picklistValues>
                <fullName>Realty BI</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_CusProjTriggerHandlerTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RBI_CusProjTriggerHandlerTestClass {

    static testMethod void RBI_CusProjTriggerHandler() {
    	ID  CusRecType = [SELECT Id FROM RecordType WHERE Name = 'Customer'].Id;
	 	ID RbiRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'RBI'].Id;
    	list<Account> Acclist = new list<Account>();
		Account acc = new Account(Name='Test Class',Weightage_Basement__c=10 ,Weightage_Electrification_Sanitation__c=3.00, 
									Weightage_Excavaton_of_Footings__c = 9, Weightage_Finishing__c =2, Weightage_Masonary__c = 3,RecordTypeId=RbiRecType);
		Account acc1 = new Account(Name='Test1 Class',Weightage_Basement__c=2 ,Weightage_Electrification_Sanitation__c=1.00, 
									Weightage_Excavaton_of_Footings__c = 2, Weightage_Finishing__c =15, Weightage_Masonary__c = 3,RecordTypeId=CusRecType);								 
		Acclist.add(acc);
		Acclist.add(acc1);
		insert Acclist;
    	
        list<Project__c> projlist = new list<Project__c>();
		Project__c proj = new Project__c(Project_Name__c='Test Class',Status__c='PDS' ,Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
										 City__c ='test', Brochure_Zipcode__c = '412578', Site_Address_zipcode__c = '123456', Launch_Date__c = System.today(),
										 Site_Address_City__c='Bangalore');
		projlist.add(proj);
		insert projlist;
		
		list<Customer_Projects__c> customerProjectlist = new list<Customer_Projects__c>();
		Customer_Projects__c cp = new Customer_Projects__c(Project_Id__c = projlist[0].Id,Weightage_Type__c='Realty BI', AccountId__c =acc1.Id);
		Customer_Projects__c cp1 = new Customer_Projects__c(Project_Id__c = projlist[0].Id,Weightage_Type__c='Customer', AccountId__c =acc1.Id);
		customerProjectlist.add(cp);
		customerProjectlist.add(cp1);
		insert customerProjectlist;
		
		//test for  Handler OnBeforeUpdate method
		system.Test.startTest();
		cp.Weightage_Type__c ='Customer';
		cp.Weightage_Basement__c = acc1.Weightage_Basement__c;
		cp.Weightage_Electrification_Sanitation__c = acc1.Weightage_Electrification_Sanitation__c;
		cp.Weightage_Excavaton_of_Footings__c = acc1.Weightage_Excavaton_of_Footings__c;
		cp.Weightage_Finishing__c = acc1.Weightage_Finishing__c;
		cp.Weightage_Masonary__c = acc1.Weightage_Masonary__c;
		cp.Weightage_RCC_Slab_Casting__c = acc1.Weightage_RCC_Slab_Casting__c;
		update cp;
		system.assertEquals(cp.Weightage_Finishing__c, 15);
		
		//test for else part
		cp.Weightage_Type__c ='Realty BI';
		cp.Weightage_Basement__c = acc.Weightage_Basement__c;
		cp.Weightage_Electrification_Sanitation__c = acc.Weightage_Electrification_Sanitation__c;
		cp.Weightage_Excavaton_of_Footings__c = acc.Weightage_Excavaton_of_Footings__c;
		cp.Weightage_Finishing__c = acc.Weightage_Finishing__c;
		cp.Weightage_Masonary__c = acc.Weightage_Masonary__c;
		cp.Weightage_RCC_Slab_Casting__c = acc.Weightage_RCC_Slab_Casting__c;
		update cp;
		system.assertEquals(cp.Weightage_Finishing__c, 2);
		system.Test.stopTest();
		
    }
}