Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Export_Projects__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to determine whether the customer can export projects</description>
        <label>Export Projects?</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>RBI</fullName>
        <active>true</active>
        <label>Realty BI</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Group_Email__c</fullName>
        <description>To capture multiple Email Id, used in ProjectTriggerHandler.</description>
        <label>Group Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to denote Primary Contact for an account. Used for Customer Record Type</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Customer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>AccountId__r.Name</formula>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Region__c</fullName>
        <formula>TEXT(Project_Id__r.Project_Region__c)</formula>
        <label>Project Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Actual_No_of_Towers__c</fullName>
        <label>Actual No of Towers</label>
        <summaryForeignKey>Tower__c.Project__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <formula>Developer_Id__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Units__c</fullName>
        <label>Planned Units</label>
        <summarizedField>Tower__c.Launched_Units__c</summarizedField>
        <summaryForeignKey>Tower__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Plot_Area__c</fullName>
        <label>Plot Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Region__c</fullName>
        <label>Project Region</label>
        <picklist>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Apartment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial / Mall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Row House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Villa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Mall</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_Actual__c</fullName>
        <formula>IF(ISBLANK(Site_Address_Line_1__c) , &apos;&apos; , Site_Address_Line_1__c &amp; &apos;,&apos;) &amp; IF(ISBLANK(Site_Address_Line_2__c), &apos;&apos;, Site_Address_Line_2__c &amp; &apos;,&apos;) &amp; IF(ISBLANK(Site_Address_Landmark__c), &apos;&apos; , Site_Address_Landmark__c &amp; &apos;,&apos; ) &amp; IF(ISBLANK(TEXT(Site_Address_City__c )), &apos;&apos; ,TEXT(Site_Address_City__c) &amp; &apos;,&apos;) &amp; IF(ISBLANK(TEXT(  Site_Address_State__c)), &apos;&apos; ,TEXT(  Site_Address_State__c) &amp; &apos;,&apos;) &amp; IF(ISBLANK(Site_Address_zipcode__c), &apos;&apos; ,Site_Address_zipcode__c)</formula>
        <label>Site Address Actual</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_Landmark__c</fullName>
        <label>Site Address Landmark</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To_Be_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is flag which will determine whether a project needs to be displayed to the Customer or not. If it is Y,, then it will not be displayed to any Customer.</description>
        <label>To Be Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Units__c</fullName>
        <label>Total Units</label>
        <summarizedField>Tower__c.Total_Units__c</summarizedField>
        <summaryForeignKey>Tower__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ExporttoXLStarterPgHandler.cls
public with sharing class RBI_ExporttoXLStarterPgHandler {
	// Variable Declaration
	public list<wrapCheckbox> WrapperProjList {get; set;}
 	private String first_picklist_option = '- All -'; 
 	public Customer_Projects__c Proj;
	public string     ProjId = '';
	public boolean    ProjectFlag = false;
	public boolean    ErrorFlag {get; set;}
	public boolean    flag {get; set;}
	public boolean    sendEmailflag {get; set;}
	public string AcctId     = '';
	string PrjId='';
	public Id SelectedProjId {get;set;}
	public String ProjIdforDownload1 {get; set;}
	
	public List<String> SerchAlpabet{get;set;}
	public String SearchVar{get;set;}
	List<Customer_Projects__c> projList;	
	public list<Customer_Projects__c> Showpro{set;get;}
	public integer sizee{get;set;}

	//Pagination
	public RBI_PageManager objPageManager {get;set;}   
	public Integer pageSize;
	public List<wrapCheckbox> Wrapper1prolist{get;set;}
	public List<Customer_Projects__c> prolist = new List<Customer_Projects__c>(); 
	public List<wrapCheckbox> proDetails = new List<wrapCheckbox>();
	String ProfileName = '';
	
	//For Popup window
	public boolean displayPopup {get; set;}
	
	public Project__c prj;
	public string Projectname{get; set;}
	public string Projectcity{get; set;}
	transient String QryString;
	
	/* Constructor */
    public RBI_ExporttoXLStarterPgHandler(){
        WrapperProjList = new list<wrapCheckbox>();  
        ErrorFlag       = false;
        sendEmailflag   = false;
        
        AcctId          = UserUtil.CurrentUser.AccountId; //Logged in user's account id  
        ProfileName     = UserUtil.CurrentUser.Profile.Name; //logged in user's profile name
        projList 		= new list<Customer_Projects__c>();
		SelectedProjId = null;
        
		//paging variables
		pageSize = 15; 
        objPageManager = new RBI_PageManager(pageSize);               
        objPageManager.page = 0;
        objPageManager.numberOfRows =0;
        Wrapper1prolist= new List<wrapCheckbox>();	
		SerchAlpabet=new List<string>{'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','All'};        	           
    }
    
    /* Action funtion called on initial load */
	public PageReference InitialLoad(){
		PageReference pg = Page.RBI_ExportToXLErrorPg;
		projList = [Select Id, Name, Project_Name__c, Project_Id__c, Customer_Name__c,AccountId__c, AccountId__r.Export_Projects__c, Project_Id__r.Name, Project_Id__r.Plot_Area__c, Project_Id__r.Project_Name__c, Project_Id__r.Project_Type__c, Project_Id__r.Developer_Name__c, Project_Id__r.Project_Region__c
					, Project_Id__r.Total_Units__c, Project_Id__r.Launch_Date__c, Project_Id__r.Site_Address_City__c,  Project_Id__r.Site_Address_Actual__c, Project_Id__r.Site_Address_Landmark__c, Project_Id__r.Actual_No_of_Towers__c, Project_Id__r.Land_Area_in_acres__c, Project_Id__r.Planned_Units__c 
					From Customer_Projects__c where 
					AccountId__c = : AcctId AND Project_Id__r.To_Be_Approved__c=false AND Project_Id__r.Status__c = 'PMR' order by createddate desc]; 
        WrapperProjList = new list<wrapCheckbox>();  
  		SearchVar='All';
  		Showpro = new list<Customer_Projects__c>();
  		Showpro.addAll(projList);
		for(Customer_Projects__c proj : Showpro){
			WrapperProjList.add(new wrapCheckbox(proj, false));
		}
		if(WrapperProjList!= null){
			sizee=WrapperProjList.size(); 
			objPageManager.numberOfRows = WrapperProjList.size();
		}	
		if(projList != null && projList.size() > 0 && projList[0].AccountId__r.Export_Projects__c != true){
			pg.setRedirect(true);
			return pg;
		}		
		return null;
	}
	
	/* Action funtion called on click of aphabet order */
	public PageReference display() 
	{
		Showpro.clear();
		/* Logic to maintain the selected project */
		map<Id, wrapCheckbox> selectedProject = new map<Id, wrapCheckbox>();
		for(wrapCheckbox wrap : WrapperProjList){
			if(wrap.emailCust == true){
				selectedProject.put(wrap.custProjrecord.Id,wrap);
			}
		}
		/* End */
		WrapperProjList.clear(); 
		set<Id> projectSetId = new set<Id>();
		if(selectedProject != null && selectedProject.size() > 0) 
			WrapperProjList.addAll(selectedProject.values());
		for(Customer_Projects__c p:projList)
		{			
			if(SearchVar.equals('All') ){
				Showpro.add(p);
				if(selectedProject != null && selectedProject.size() > 0 && selectedProject.containsKey(p.Id)){
			 		continue;
				}
				WrapperProjList.add(new wrapCheckbox(p));
			}					
			else
				if(p.Project_Id__r.Project_Name__c.startsWith(SearchVar.toLowerCase())||p.Project_Id__r.Project_Name__c.startsWith(SearchVar))
				{
					Showpro.add(p);
				   	if(selectedProject != null && selectedProject.size() > 0 && selectedProject.containsKey(p.Id)){
				 		continue;
					}
			 	   	WrapperProjList.add(new wrapCheckbox(p));
				}   
		}
		if(WrapperProjList!= null){
			sizee=WrapperProjList.size(); 
			objPageManager.numberOfRows = WrapperProjList.size();
		}			
		return null;
	}

    // Getter-setter for proDetails used for pagination
  	public List<wrapCheckbox> getproDetails(){
  	
  	if((WrapperProjList !=null) && (WrapperProjList.size() >0)){ 
      	 if(Wrapper1prolist !=null)	
       		Wrapper1prolist.clear();
        	for(integer i=objPageManager.startIndex;i<objPageManager.endIndex&&i<WrapperProjList.size();i++){
            	Wrapper1prolist.add(WrapperProjList.get(i));
         	}
     	} 
    return Wrapper1prolist; 
    } 
    
	public void  setproDetails (List<wrapCheckbox> proDetails) {
		this.proDetails = proDetails;
	}
	
	public PageReference SearchProjects(){
		QryString = 'Select Id, Name, Project_Name__c, Site_Address_City__c, Project_Id__c, Customer_Name__c,AccountId__c, AccountId__r.Export_Projects__c, Project_Id__r.Name, Project_Id__r.Plot_Area__c, Project_Id__r.Project_Name__c, Project_Id__r.Project_Type__c, Project_Id__r.Developer_Name__c, Project_Id__r.Project_Region__c' +
					', Project_Id__r.Total_Units__c, Project_Id__r.Launch_Date__c, Project_Id__r.Site_Address_City__c,  Project_Id__r.Site_Address_Actual__c, Project_Id__r.Site_Address_Landmark__c, Project_Id__r.Actual_No_of_Towers__c, Project_Id__r.Land_Area_in_acres__c, Project_Id__r.Planned_Units__c From Customer_Projects__c where AccountId__c = : AcctId AND Project_Id__r.To_Be_Approved__c=false AND Project_Name__c LIKE \'%'  + Projectname + '%\'';
		system.debug('ABCD ' + QryString);
		if(!Projectcity.equals('- All -')) {
   	    	QryString += ' AND Site_Address_City__c LIKE \'%' + Projectcity + '%\'';
   	    }
   	    system.debug('Coming Into search');
   	    projList = new list<Customer_Projects__c>();
   	    projList = Database.query(QryString);
   	    
   	    /* Logic to maintain the selected project */
		map<Id, wrapCheckbox> selectedProject = new map<Id, wrapCheckbox>();
		for(wrapCheckbox wrap : WrapperProjList){
			if(wrap.emailCust == true){
				selectedProject.put(wrap.custProjrecord.Id,wrap);
			}
		}
		WrapperProjList.clear();
		if(selectedProject != null && selectedProject.size() > 0){
			WrapperProjList = new list<wrapCheckbox>();
			WrapperProjList.addAll(selectedProject.values());
		}
		/* End */
   	    
   	    if(projList == null){
		     
   	 	}else{	  
   	 		
	  		SearchVar = 'All';
	  		Showpro = new list<Customer_Projects__c>();
	  		Showpro.addAll(projList);   	 				
	        for(Customer_Projects__c Serv1: projList) {
	        	if(selectedProject != null && selectedProject.size() > 0 && selectedProject.containsKey(Serv1.Id)){
				 	continue;
				}
    			WrapperProjList.add(new wrapCheckbox(Serv1));
	        }
	   	}
		if(WrapperProjList!= null){
			sizee=WrapperProjList.size(); 
			objPageManager.numberOfRows = WrapperProjList.size();
		}
   	 	return null; 
	}
	
	/*This method is refered from RBI_UtilClass to fetch the City values*/
    public List<selectOption> getCity() {
    	prj = new Project__c();
		list<selectOption> pickvalue;          
    	pickvalue = RBI_UtilClass.getPickValues(prj, 'Site_Address_City__c', first_picklist_option);
        return  pickvalue;  
   	}
		
	public pageReference detail() {
    
	 	PrjId=Apexpages.currentPage().getParameters().get('PrjId');
	 	PageReference pagref;
	 	system.debug('ProfileName'+ProfileName);
	 	if (ProfileName == 'RBI Customer Portal Manager')
	  		pagref = new PageReference('/apex/RBI_ProjectDetail?id='+SelectedProjId);
	  		
	  	if (ProfileName == 'RBI Customer Portal User')
	  		pagref = new PageReference('/apex/RBI_DetailPageforPortalUser?id='+SelectedProjId);
	  		
	  	return pagref;
    }
     
    public PageReference sendMail(){
     	list<wrapCheckbox> selectedProjects = new list<wrapCheckbox>();
     	List<Messaging.Emailfileattachment> attList = new List<Messaging.Emailfileattachment>();
     	Contact primaryContact = new Contact();
     	String[] toAddresses;
     	try{
     		String bigProject = '';
     		system.debug('Coming to sendemail');
	     	Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
	     	for(wrapCheckbox wrap : WrapperProjList){
	     		if(wrap.emailCust == true){
	     			system.debug('========'+wrap.custProjrecord.Project_Id__c);
	     			selectedProjects.add(wrap);
	     			PageReference myPdf = Page.RBI_ProjectExport;
					myPdf.getParameters().put('ProjId',wrap.custProjrecord.Project_Id__c);
					Blob b;
					try{
						b = myPdf.getContent();
					}catch(VisualforceException e){
						bigProject +=  '\''+wrap.custProjrecord.Project_Name__c+'\',' ;//Testing
					}
					Messaging.EmailFileAttachment attachment = new Messaging.EmailFileAttachment();
					attachment.setFileName(wrap.custProjrecord.Project_Name__c);
					attachment.setBody(b);
					attachment.setContentType('application/vnd.ms-excel');                           
					attList.add(attachment);    
	     		}
	     	}
	     	if(bigProject != null && bigProject != ''){
	     		bigProject = bigProject.substring(0, bigProject.length()-1); 
	     		apexpages.addmessage(new apexpages.message(apexpages.severity.Info, 'The size of the project '+bigProject+' exceeds the limit range. Please select other projects and proceed.'));
	     	}
	     	if(attList != null){
	     		email.setFileAttachments(attList);
	     		if(AcctId != null)
	     			primaryContact = [select name, Group_Email__c from Contact where (AccountId = : AcctId) and (Primary__c = true) limit 1];
	     	}
			email.saveAsActivity = false;
			if(selectedProjects != null && selectedProjects.size() > 0){
				email.setWhatId(selectedProjects[0].custProjrecord.Id);
				
			}
		    if(primaryContact != null){
		    	email.setTargetObjectId(primaryContact.Id);
		    }	
		 	email.setTemplateId(System.label.RBI_ProjectImportTemplateId);	
			if(primaryContact != null && primaryContact.Group_Email__c != null)
				toAddresses = primaryContact.Group_Email__c.split(',');
			email.setToAddresses(toAddresses);
			email.setOrgWideEmailAddressId(system.label.RBI_OrgWideEmailAddr);
			if (!Test.isRunningTest()) { 
				Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
			} 
     	}catch(EmailException e){
     		apexpages.addmessage(new apexpages.message(apexpages.severity.error, 'Faliure in sending email!'));
     		showPopup();
     		return null;
     	}catch(Exception e){
     		apexpages.addmessages(e);
     		showPopup();
     		return null;
     	}
     	sendEmailflag = true;
     	showPopup();
		InitialLoad();
     	return null;
	}
	
	/* For openning the popUp window and closing it. */
	public PageReference closePopup() {
		PageReference pg;
		if(sendEmailflag != false){
			pg = Page.RBI_ExporttoXLStarterPg;
			displayPopup = false;
			pg.setRedirect(true);
			return pg;
		}
		displayPopup = false;
		return null; 
    }
 
    public void showPopup() {
		displayPopup = true;
    }
     
    public PageReference downloadProj(){
     	PageReference myPdf = Page.RBI_ProjectExport;
    	string prjid = Apexpages.currentPage().getParameters().get('ProjIdforDownload');
     	string test = ProjIdforDownload1;
     	myPdf.getParameters().put('ProjId',prjid);
     	return myPdf;
    }
     
    public class wrapCheckbox{
		public Customer_Projects__c custProjrecord{get; set;}
		public Boolean emailCust {get; set;}
		public wrapCheckbox(Customer_Projects__c custProj){
			custProjrecord = custProj;
			emailCust = false;
		}
		
		public wrapCheckbox(Customer_Projects__c custProj, Boolean check){
			custProjrecord = custProj;
			emailCust = check;
		}
    }
}