Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Developer</fullName>
        <active>true</active>
        <label>Developer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Bank Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Year__c</fullName>
        <label>Completion Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_Project_Address__c</fullName>
        <description>This will hold the address for the other projects by Developer</description>
        <label>Project Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the reference to the Account(developer) for other ongoing projects</description>
        <label>Developer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ongoing and Completed Projects</relationshipLabel>
        <relationshipName>OnGoingProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dwelling_Units__c</fullName>
        <label>Dwelling Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Loan Amount (in Crs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_DeveloperBatchtestclass.cls
@isTest(SeeAllData=true)
private class RBI_DeveloperBatchtestclass {

    static testMethod void DeveloperBatch() {
       ID DevRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Developer'].Id; 
        list<Account> acc = new list<Account>();
        Account Acnt = new Account(Name = 'TestAccount', BillingStreet = 'TestStreet', BillingCity = 'Mumbai', BillingState = 'MR', BillingCountry = 'India',
                                    BillingPostalCode = '123456', Phone = '124567',RecordTypeId = DevRecType);
         Account Acnt1 = new Account(Name = 'TestAccount1', BillingStreet = 'TestStreet', BillingCity = 'Delhi', BillingState = 'Delhi', BillingCountry = 'India',
                           BillingPostalCode = '123456', Phone = '124567',RecordTypeId = DevRecType);                            
        acc.add(Acnt);
        acc.add(Acnt1);
        insert acc;
        
        list<List_of_Values__c> lovlist = new list<List_of_Values__c>();
        List_of_Values__c lov = new List_of_Values__c(Name='Other Projects', Entity_Name__c='Other Projects', Entity_Type__c='Other Projects',
									Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
									Loan_Amount__c=25000, Dev_Project_Address__c='test unit',Project_Type__c='Completed',Developer__c=acc[0].Id);
		List_of_Values__c lov1 = new List_of_Values__c(Name='Other Projects', Entity_Name__c='Other Projects',Entity_Type__c='Other Projects',
									Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
									Loan_Amount__c=25000, Dev_Project_Address__c='test unit',Project_Type__c='Ongoing',Developer__c=acc[1].Id);
		lovlist.add(lov);
		lovlist.add(lov1);
		insert lovlist;	
		
		//start test
        Test.StartTest();
        RBI_DeveloperAlertBatch batch = new RBI_DeveloperAlertBatch();
		Id JobId = Database.ExecuteBatch(batch);
		
		RBI_DeveloperAlertScheduler sco = new RBI_DeveloperAlertScheduler();
		String sch = '0 0 23 * * ?';        
		system.schedule('Creating', sch, sco);	
		//stop test	
		test.stopTest();				
        
    }
}