Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>RBI</fullName>
        <active>true</active>
        <label>Realty BI</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Details_of_Experience__c</fullName>
        <label>Details of Experience</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Qualifications__c</fullName>
        <label>Qualifications</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>AccountId__r.Name</formula>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Bank Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Year__c</fullName>
        <label>Completion Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Unit Report generation</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unit Report Details</relationshipLabel>
        <relationshipName>UnitReport</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dev_Project_Address__c</fullName>
        <description>This will hold the address for the other projects by Developer</description>
        <label>Project Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the reference to the Account(developer) for other ongoing projects</description>
        <label>Developer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ongoing and Completed Projects</relationshipLabel>
        <relationshipName>OnGoingProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dwelling_Units__c</fullName>
        <label>Dwelling Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_Acres__c</fullName>
        <label>Land Area In Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Loan Amount (in Crs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Id_Const_Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Id for the Construction Loan taken by Developer</description>
        <label>Construction Loan for Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Construction Loan Details</relationshipLabel>
        <relationshipName>ConstructionLoan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Unit__r.Tower_Id__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_BUA__c</fullName>
        <label>Total BUA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Developer_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Apartment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial / Mall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Row House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Villa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Mall</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Legal_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Legal Agency</description>
        <label>Legal Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits (Legal Agency)</relationshipLabel>
        <relationshipName>Visits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Forwarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Used for Project level visits</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ProjectSnapshot.cls
/*
    Type:       Custom Controller
    Purpose:    Used to generate the Project Snapshot Report for a Customer from Customer Portal.        

    Used By:   RBI_GenerateProjectSnapshotReport.page
    ---------------------------------------------------------------
    History:

    26-Apr-2013     Created     Tugboat Info Solutions Pvt. Ltd

*/
public class RBI_ProjectSnapshot {
    public Contact con{get; set;}
    public list<Contact> conlst{get;set;} 
    public Project__c prj{get; set;}
    public list<Project__c> projlist{get;set;}
    public list<List_of_Values__c> Quantlist{get;set;}
    public list<List_of_Values__c> lovlist{get;set;}
    public list<List_of_Values__c> lvongoinglist{get;set;}
    public list<List_of_Values__c> lvcomplete{get;set;}
    public Id projid;
    public ApexPages.StandardController sController;
    public Visit__c visit {get; set;}
    public Visit__c visittsr {get; set;}
    public list<Visit__c> visitlist{get;set;}
    public list<Visit__c> tsrlist{get;set;}
    public list<Visit__c> dvulist{get;set;}
    public list<Customer_Projects__c> customerlist{get;set;}
    public string dateStr {get; set;}
    public boolean IsPorEnabled {get;set;}    
    private string RBIaccnt = '';
    public string AcctName {get;set;}
    private string AcctId     = '';
    
    public RBI_ProjectSnapshot(ApexPages.StandardController stdCon)
    {
        sController = stdCon;
        projid=ApexPages.currentPage().getParameters().get('id');
        showDevAccContact(); 
        showlovproject();
        showvisit();
        projlist = new list <Project__c>();
        RBIaccnt =  System.Label.RBI_AccountId;
        AcctId = UserUtil.CurrentUser.AccountId; //Logged in user's account id
        AcctId = (AcctId == null || AcctId == '')?RBIaccnt:AcctId; //set account id to RBI cust record in case it is null
        IsPorEnabled = UserUtil.CurrentUser.IsPortalEnabled;
		AcctName = UserUtil.CurrentUser.contact.account.Name;
        //customerlist=[Select Customer_Name__c,Project_Id__c from Customer_Projects__c where Project_Id__c=:projid ORDER by LastModifiedDate DESC];
    }
    public void showDevAccContact(){
        projlist=[Select id, Developer_Id__c From Project__c where id=:projid ];
        if (projlist[0].Developer_Id__c != null)
        	conlst = [select Id, Name ,Age__c, Details_of_Experience__c, Qualifications__c,AccountId from Contact where AccountId =:projlist[0].Developer_Id__c];
    
    }
    
    public void showlovproject(){
        //Quantlist=[Select Total_BUA__c, Project_Type__c, Loan_Amount__c, Land_Area_in_Acres__c, Id,Project_Id_Const_Loan__c, Dwelling_Units__c, Dev_Project_Name__c, Completion_Year__c, Bank_Name__c From List_of_Values__c  where Developer__c=:projlist[0].Developer_Id__c]; 
        Quantlist=[Select Total_BUA__c, Project_Type__c, Loan_Amount__c, Land_Area_in_Acres__c, Id,Project_Id_Const_Loan__c, Dwelling_Units__c, Dev_Project_Name__c, Completion_Year__c, Bank_Name__c From List_of_Values__c  where Project_Id_Const_Loan__c =: projid];
        lvongoinglist= new list<List_of_Values__c>();
        lvcomplete = new list<List_of_Values__c>();
        lovlist=[Select Total_BUA__c, Project_Type__c,Dev_Project_Address__c, Loan_Amount__c, Land_Area_in_Acres__c, Id, Dwelling_Units__c, Dev_Project_Name__c, Completion_Year__c, Bank_Name__c,Customer__r.Name From List_of_Values__c where Developer__c=:projlist[0].Developer_Id__c]; 
        for(List_of_Values__c lv :lovlist){
            if(lv.Project_Type__c == 'Ongoing')
            { 
                lvongoinglist.add(lv);
            }
            else if(lv.Project_Type__c == 'Completed')
            { 
                lvcomplete.add(lv);
            }   
        }
        
    }
    public void showvisit(){
        DateTime d = system.Today() ;
        dateStr =  d.format('dd/MM/yyyy') ; 
            
        visit=new Visit__c ();
        visittsr = new Visit__c ();
        visitlist = new list<Visit__c>();
        tsrlist = new list<Visit__c>();
        dvulist = new list<Visit__c>();
        
        visitlist=[Select Status__c, LastModifiedDate, Legal_Agency__r.Name,Project__c, Visit_Report__c From Visit__c  where Project__c=:projid ORDER by LastModifiedDate DESC]; 
        for(Visit__c vis :visitlist){
            if(vis.Visit_Report__c == 'TSR Report')
            { 
                tsrlist.add(vis);
                visittsr = tsrlist[0];
            }
            else if(vis.Visit_Report__c == 'DVU Report') 
            { 
                dvulist.add(vis);
                visit=dvulist[0];
            }   
            
        }
         
    }
}