Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Customer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Infrastructure_Near_Project__c.object
<CustomObject>
    <fields>
        <fullName>Infrastructure_Near_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Infrastructure Near Project</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Infrastructure Near Project</relationshipLabel>
        <relationshipName>Infrastructure_Near_Project</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Infrastructure Near Project</relationshipLabel>
        <relationshipName>Infrastructure_Near_Project</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Developed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Developed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Infrastructure Near Project</label>
    <nameField>
        <displayFormat>INF-{0000000000}</displayFormat>
        <label>Infrastructure Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Infrastructure Near Project</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Bank Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Year__c</fullName>
        <label>Completion Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dwelling_Units__c</fullName>
        <label>Dwelling Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_Acres__c</fullName>
        <label>Land Area In Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Loan Amount (in Crs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Unit__r.Tower_Id__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To_Be_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is flag which will determine whether a project needs to be displayed to the Customer or not. If it is Y,, then it will not be displayed to any Customer.</description>
        <label>To Be Approved</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Project__c</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Strores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Feedbacks</relationshipLabel>
        <relationshipName>Project_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Feedback</label>
    <nameField>
        <displayFormat>FB-{0000000000}</displayFormat>
        <label>Feedback Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Launched_Units__c</fullName>
        <label>Launched Units</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Avg_Developer_BSP_per_Sq_Ft__c</fullName>
        <label>Max Avg Developer BSP (per Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Avg_Resale_Price_Per_Sqft__c</fullName>
        <description>Used to store Avg Resale Price (Per Sqft)</description>
        <label>Max Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Developer_BSP_per_Sq_Ft__c</fullName>
        <description>Used to store min avg developer BSP</description>
        <label>Min Avg Developer BSP (per Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Resale_Price_Per_Sqft__c</fullName>
        <description>Used to store Min Avg Resale Price (Per Sqft)</description>
        <label>Min Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sold_Units__c</fullName>
        <label>Sold Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ExportXLStarterPgTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest (SeeAllData=true)
private class RBI_ExportXLStarterPgTestClass {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        ID  CusRecType = [SELECT Id FROM RecordType WHERE Name = 'Customer'].Id;
        list<Account> acc = new list<Account>();
       	Account Acnt = new Account(Name = 'TestAccount', BillingStreet = 'TestStreet', BillingCity = 'Hyderabad', BillingState = 'AP', BillingCountry = 'India',
       								BillingPostalCode = '123456', Phone = '124567', Type='Customer', RecordTypeId = CusRecType);
       	acc.add(Acnt);
       	insert acc;
        
        list<Project__c> projlist = new list<Project__c>();
		Project__c proj = new Project__c(Project_Name__c='Test Class', Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
										 City__c ='test', Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' , To_Be_Approved__c = false, 
										 Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today(),Status__c='PMR');
		projlist.add(proj);
		insert projlist;
		
		list<Customer_Projects__c> customerProjectlist = new list<Customer_Projects__c>();
		Customer_Projects__c cp = new Customer_Projects__c(Project_Id__c = projlist[0].Id, AccountId__c = acc[0].Id);
		customerProjectlist.add(cp);
		insert customerProjectlist;
		
		list<Tower__c> tw = new list<Tower__c>();
        Tower__c tow = new Tower__c(Name = 'Test Tower', Project__c = projlist[0].Id,Min_Avg_Developer_BSP_per_Sq_Ft__c=12, Launched_Units__c = 80,
                                        Min_Avg_Resale_Price_Per_Sqft__c=20, Max_Avg_Developer_BSP_per_Sq_Ft__c=25,
                                        Max_Avg_Resale_Price_Per_Sqft__c=27, Sold_Units__c=16);
        tw.add(tow);
        insert tw;
        
        /* This is created for Infrastructure_Near_Project__c */
        list<List_of_Values__c> lovlist = new list<List_of_Values__c>();
            List_of_Values__c lov = new List_of_Values__c(Name='Marker Feedback', Entity_Name__c='Infrastructure Near Project Site', Entity_Type__c='Public Convenience',
                                    Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
                                    Loan_Amount__c=25000, Dev_Project_Address__c='test unit');
            List_of_Values__c lov1 = new List_of_Values__c(Name='Marker Feedback', Entity_Name__c='Payment Plan',Entity_Type__c='Payment Plan',
                                    Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
                                    Loan_Amount__c=25000, Dev_Project_Address__c='test unit');
            List_of_Values__c lov2 = new List_of_Values__c(Name='Marker Feedback', Entity_Name__c='Document',Entity_Type__c='Document',
                                    Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
                                    Loan_Amount__c=25000, Dev_Project_Address__c='test unit');
            List_of_Values__c lov3 = new List_of_Values__c(Name='Marker Feedback', Entity_Name__c='Remark',Entity_Type__c='Remark',
                                    Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
                                    Loan_Amount__c=25000, Dev_Project_Address__c='test unit');
            List_of_Values__c lov4 = new List_of_Values__c(Name='FTR', Entity_Name__c='Package',Entity_Type__c='Package',
                                    Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
                                    Loan_Amount__c=25000, Dev_Project_Address__c='test unit');  
            List_of_Values__c lov5 = new List_of_Values__c(Name='PAS', Entity_Name__c='Package',Entity_Type__c='Package',
                                    Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
                                    Loan_Amount__c=25000, Dev_Project_Address__c='test unit1');
                                    
            List_of_Values__c lov6 = new List_of_Values__c(Name='PMS', Entity_Name__c='Package',Entity_Type__c='Package',
                                    Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
                                    Loan_Amount__c=25000, Dev_Project_Address__c='test unit3');
                                                                
            lovlist.add(lov);
            lovlist.add(lov1);
            lovlist.add(lov2);
            lovlist.add(lov3);
            lovlist.add(lov4);
            lovlist.add(lov5);
            lovlist.add(lov6);
            insert lovlist;
        
        list<Infrastructure_Near_Project__c> infraproj = new list<Infrastructure_Near_Project__c>();
        Infrastructure_Near_Project__c infranearproj = new Infrastructure_Near_Project__c(Infrastructure_Near_Project__c = lov.Id, 
                                            Project_Id__c = projlist[0].Id);
        infraproj.add(infranearproj);
        insert infraproj;
                
        list<Project_Feedback__c> projfeedbacklist = new list<Project_Feedback__c>();
        Project_Feedback__c projfeed = new Project_Feedback__c(List_of_Values_Id__c = lovlist[3].Id, Project__c=projlist[0].Id,Comments__c='xxx');
        projfeedbacklist.add(projfeed);
        insert projfeedbacklist;        
                
        //start test class method
       	System.Test.startTest(); 
       	
       	//Instantiate the RBI_MyProjects Page
       	PageReference ExportXLStarterPage = Page.RBI_ExporttoXLStarterPg;
       	System.Test.setCurrentPage(ExportXLStarterPage);
       	
       	RBI_ExporttoXLStarterPgHandler ExportHandler = new RBI_ExporttoXLStarterPgHandler();
       	ExportHandler.AcctId = acc[0].Id;
       	ExportHandler.InitialLoad();
       	ExportHandler.WrapperProjList[0].emailCust = true;
       	ExportHandler.sendMail();
       	ExportHandler.closePopup();
       	
       	ExportHandler.SearchVar = 'All';
       	ExportHandler.SelectedProjId = projlist[0].Id;
		ExportHandler.display();
		
		ExportHandler.SearchVar = 'A';
		ExportHandler.display();
		
		ExportHandler.Projectname ='Test Class';
		ExportHandler.Projectcity ='All';
		ExportHandler.SearchProjects();
		
		//test selectoption  GetCity picklist method
		List<selectOption> locale_picklist_options = ExportHandler.getCity();
        System.AssertNotEquals(0, locale_picklist_options.size());
		
		ExportHandler.getproDetails();
		
		ExportHandler.setproDetails(ExportHandler.proDetails);
		ExportHandler.detail();
		
		/* This is for RBI_ProjectExport */
		PageReference ExportPage = Page.RBI_ProjectExport;
		ExportPage.getParameters().put('ProjId' , projlist[0].Id);
		System.Test.setCurrentPage(ExportPage);
		RBI_PrjMultiSheetExcel prjMulti = new RBI_PrjMultiSheetExcel();
		prjMulti.inpprojectId = projlist[0].Id;
		
       	System.Test.stopTest();
    }
}