Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Bank Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Year__c</fullName>
        <label>Completion Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_Project_Address__c</fullName>
        <description>This will hold the address for the other projects by Developer</description>
        <label>Project Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the reference to the Account(developer) for other ongoing projects</description>
        <label>Developer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ongoing and Completed Projects</relationshipLabel>
        <relationshipName>OnGoingProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dwelling_Units__c</fullName>
        <label>Dwelling Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_Acres__c</fullName>
        <label>Land Area In Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Loan Amount (in Crs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Id_Const_Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Id for the Construction Loan taken by Developer</description>
        <label>Construction Loan for Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Construction Loan Details</relationshipLabel>
        <relationshipName>ConstructionLoan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_BUA__c</fullName>
        <label>Total BUA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_DeveloperProfile.cls
public with sharing class RBI_DeveloperProfile {

	public list<List_of_Values__c> allprojlist{get;set;}
	public list<List_of_Values__c> lvongoinglist{get;set;}
	public list<List_of_Values__c> lvcomplete{get;set;}
	public Account acc {get; set;}
	string accId;
	public ApexPages.StandardController sController;
		
	public RBI_DeveloperProfile(ApexPages.StandardController stdCon)
	{
		sController = stdCon;
		this.acc=(Account)stdCon.getRecord();
		accid=acc.Id;
		showlovproject();
		
	}
	
	public void showlovproject() {
		
		allprojlist = new list<List_of_Values__c>();
		allprojlist = [Select Total_BUA__c, Project_Type__c, Dev_Project_Address__c, Loan_Amount__c, Land_Area_in_Acres__c, Id,Project_Id_Const_Loan__c, Dwelling_Units__c, Dev_Project_Name__c, Completion_Year__c, Bank_Name__c From List_of_Values__c  where Developer__c=:accid];
		system.debug('Project List '+allprojlist + accid);
		if (allprojlist.size() != null) {
			lvongoinglist= new list<List_of_Values__c>();
		 	lvcomplete = new list<List_of_Values__c>();
		 
	    	for(List_of_Values__c lv :allprojlist){
	    		if(lv.Project_Type__c == 'Ongoing') { 
	    			lvongoinglist.add(lv);
	    		
	    		}
	    		else if(lv.Project_Type__c == 'Completed') {
	    			lvcomplete.add(lv);
	    		 
	    		}	
	    	
	   	   	}
		}
		
	}
		
}