Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Customer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Bank Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Year__c</fullName>
        <label>Completion Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_Project_Address__c</fullName>
        <description>This will hold the address for the other projects by Developer</description>
        <label>Project Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dwelling_Units__c</fullName>
        <label>Dwelling Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_Acres__c</fullName>
        <label>Land Area In Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Loan Amount (in Crs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Unit__r.Tower_Id__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>To_Be_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is flag which will determine whether a project needs to be displayed to the Customer or not. If it is Y,, then it will not be displayed to any Customer.</description>
        <label>To Be Approved</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Cust_Packages__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship of Customer project</description>
        <label>Customer Project</label>
        <referenceTo>Customer_Projects__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>List_of_Values__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores reference of master data for List of Values object</description>
        <label>Package Name</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <description>This field is used in Trigger.</description>
        <formula>Customer_Project__r.Project_Id__c &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 5, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 4, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 3, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 2, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 1, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 10, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 9, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 8, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 7, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 6, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 15, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 14, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 13, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 12, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 11, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1)</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Customer_Project__r.Project_Id__r.Name</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Customer_Project__r.Project_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Customer Package</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Package Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Package</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_LaunchedProjectsTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true) 
private class RBI_LaunchedProjectsTestClass {

   static testMethod void RBI_LaunchedProjects() {
        //Create And Insert Data
        ID  CusRecType = [SELECT Id FROM RecordType WHERE Name = 'Customer'].Id;
        
        list<Account> acc = new list<Account>();
       	Account Acnt = new Account(Name = 'TestAccount', BillingStreet = 'TestStreet', BillingCity = 'Hyderabad', BillingState = 'AP', BillingCountry = 'India',
       								BillingPostalCode = '123456', Phone = '124567', Type='Customer',RecordTypeId = CusRecType );
       	acc.add(Acnt);
       	insert acc;
        
        list<Project__c> projlist = new list<Project__c>();
        Project__c proj = new Project__c(Project_Name__c='Test Class', Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
                                         City__c ='test', Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' ,To_Be_Approved__c = true, 
                                         Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today());
        Project__c proj1 = new Project__c(Project_Name__c='Test1 Class', Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
                                     	 City__c ='test1', Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' , 
                                     	 Site_Address_City__c = 'Mumbai', Launch_Date__c = System.today()+1);    
                              
        projlist.add(proj);
        projlist.add(proj1);
        insert projlist;
        
        list<Customer_Projects__c> customerProjectlist = new list<Customer_Projects__c>();
        Customer_Projects__c cp = new Customer_Projects__c(Project_Id__c = projlist[0].Id,AccountId__c= acc[0].id);
        customerProjectlist.add(cp);
        insert customerProjectlist;
        
        list<List_of_Values__c> lovlist = new list<List_of_Values__c>();
        List_of_Values__c lov = new List_of_Values__c(Name='Marker Feedback', Entity_Name__c='Package',Entity_Type__c='Package',
                                Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, 
                                Loan_Amount__c=25000, Dev_Project_Address__c='test unit');
        lovlist.add(lov);
        insert lovlist;
        
        list<Project_Cust_Packages__c> projcustpackagelist= new list<Project_Cust_Packages__c>();
        Project_Cust_Packages__c projectCustPackage = new Project_Cust_Packages__c(Customer_Project__c =customerProjectlist[0].Id ,List_of_Values__c=lovlist[0].Id);
        projcustpackagelist.add(projectCustPackage);
        //insert projcustpackagelist;
        
        //Start Test Class
        System.Test.startTest();
        
        //Instantiate the RBI_LaunchedProjects
        PageReference RBI_ProjectLaunchedPage = Page.RBI_LaunchedProjects;
        System.Test.setCurrentPage(RBI_ProjectLaunchedPage);
        
        ////Class instantiating 
        RBI_LaunchedProjects RBILaunched= new  RBI_LaunchedProjects();
        RBILaunched.InitialLoad();
        
        //Test for display method in RBI_LaunchedProjects class
        RBILaunched.SearchVar='All'; 
        RBILaunched.display();
        
        //Test for  else part in display method in RBI_LaunchedProjects class
        RBILaunched.SearchVar='T';   
        RBILaunched.display(); 
        
        //Test for  else part in display method in RBI_LaunchedProjects class
        RBILaunched.SearchVar='t';   
        RBILaunched.display(); 
        
        //Test for getproDetails method
        
        RBILaunched.getproDetails();
        RBILaunched.setproDetails(RBILaunched.proDetails);
        
        //Test for  searchProjects method
        RBILaunched.Projectcity='- All -';
        RBILaunched.searchProjects();
        
        //Test for else part  searchProjects method
        RBILaunched.Projectcity='A';
        RBILaunched.searchProjects();
        
        //test selectoption  GetCity picklist method
        List<selectOption> locale_picklist_options = RBILaunched.getCity();
        System.AssertNotEquals(0, locale_picklist_options.size());
        
        //Test For savelist Method
        RBILaunched.savelist();
       
        //Test For QryDevProfile
        RBILaunched.QryDevProfile() ;
        
        //Test For Displaypopup method
        RBILaunched.displayPopup=false;
        RBILaunched.closePopup();
        RBILaunched.displayPopup=true;
        RBILaunched.showPopup();
        
        //Test for FTRPASIdGenerate And CheckFTR method
        RBILaunched.FTRPASIdGenerate();
        RBILaunched.CheckFTR();
        
       	//Test for GoogleMap popup
       	RBILaunched.displayPopupforPrjMap=true;
       	RBILaunched.showPopupforPrjMap();
       	RBILaunched.displayPopupforPrjMap=false;
       	RBILaunched.closePopupforPrjMap();
        
        //stop the Test class
        System.Test.stopTest();
    }
}