Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_Contract_End_Date__c</fullName>
        <label>Current Contract End Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Customer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Unit Report generation</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Unit Report Details</relationshipLabel>
        <relationshipName>UnitReport</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Unit__r.Tower_Id__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Cust_Packages__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This field will store the Expiry date for the service</description>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>List_of_Values__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores reference of master data for List of Values object</description>
        <label>Package Name</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <description>This field is used in Trigger.</description>
        <formula>Customer_Project__r.Project_Id__c &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 5, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 4, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 3, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 2, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 1, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 10, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 9, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 8, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 7, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 6, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 15, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 14, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 13, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 12, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 11, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1)</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Customer_Project__r.Project_Id__r.Name</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Customer_Project__r.Project_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This is used to store the Start date for the service</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Customer Package</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Package Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Package</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/RBI_Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <description>Stores Relationship between Subscription and Customer</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RBI_Subscriptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Launched_Cities__c</fullName>
        <label>Launched Cities</label>
        <picklist>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{000000000}</displayFormat>
        <label>Subscription Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <recordTypes>
        <fullName>Launched</fullName>
        <active>true</active>
        <description>RBI_Subscriptions Object Recordtype</description>
        <label>Launched</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_SubscriptionTriggerHandler.cls
public with sharing class RBI_SubscriptionTriggerHandler {
	
	Map<Id, Date> custIdDateMap;
	Map<Id, String> custIdCityMap;
	Set<String> LaunchedCities;
	boolean callFutureFlag;
	public Id launchedId;
	
	public RBI_SubscriptionTriggerHandler(){
		launchedId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Launched'].Id;
		custIdDateMap = new Map<Id, Date>();
		LaunchedCities = new Set<String>();
		custIdCityMap = new Map<Id, String>();
		callFutureFlag = false;
	}
	
	public void OnAfterInsert(list<RBI_Subscription__c> subscription){
		for(RBI_Subscription__c sub : subscription){
			if(sub.Start_Date__c != null && sub.Launched_Cities__c != null && sub.RecordTypeId == launchedId){
				list<String> cityList = sub.Launched_Cities__c.split(';');
				LaunchedCities.addAll(cityList);
				custIdDateMap.put(sub.Customer__c, sub.Start_Date__c);
				custIdCityMap.put(sub.Customer__c, sub.Launched_Cities__c);
				callFutureFlag = true;
			}
		}
		if(callFutureFlag){
			futureHandler(custIdDateMap, custIdCityMap, LaunchedCities);
		}
	}
	
	public void OnAfterUpdate(list<RBI_Subscription__c> newSubscrip, list<RBI_Subscription__c> oldSubscrip, Map<Id, RBI_Subscription__c> oldsubmap){
		for(RBI_Subscription__c subsc : newSubscrip){
			if((subsc.Id == oldsubmap.get(subsc.Id).Id && oldsubmap.get(subsc.Id).Start_Date__c != subsc.Start_Date__c) || (subsc.Id == oldsubmap.get(subsc.Id).Id && oldsubmap.get(subsc.Id).Launched_Cities__c != subsc.Launched_Cities__c)){
				if((subsc.RecordTypeId == launchedId)){
					list<String> cityList = subsc.Launched_Cities__c.split(';');
					LaunchedCities.addAll(cityList);
					custIdDateMap.put(subsc.Customer__c, subsc.Start_Date__c);
					custIdCityMap.put(subsc.Customer__c, subsc.Launched_Cities__c);
					callFutureFlag = true;
				}
			}
		}
		if(callFutureFlag){
			futureHandler(custIdDateMap, custIdCityMap, LaunchedCities);
		}
	}
	
	@future (callout=true)
	public static void futureHandler(Map<Id, Date> mapDt, Map<Id, String> mapStrCity, set<String> cityLaunched){
		list<Customer_Projects__c> cusProjlist = new list<Customer_Projects__c>();
		Map<String, Customer_Projects__c> mapDuplicateCusProj = new Map<String, Customer_Projects__c>();
		list<Customer_Projects__c> CusProjinsert = new list<Customer_Projects__c>();
		list<Customer_Projects__c> CusProjExandNew = new list<Customer_Projects__c>();
		
		list<Project_Cust_Packages__c> custPkginsert = new list<Project_Cust_Packages__c>(); 
		Map<String, Project_Cust_Packages__c> mapPrjCustPkgDup = new map<String, Project_Cust_Packages__c>();
		list<Project_Cust_Packages__c> custPkgList = new list<Project_Cust_Packages__c>();
		
		Map<String, List_of_Values__c> lovmap = new Map<String, List_of_Values__c>(); 
		list<List_of_Values__c> lovList = new list<List_of_Values__c>();
		set<Id> projId = new set<Id>();
		set<Id> custId = new set<Id>();
		set<Id> cusPrjId = new set<Id>();
		list<Project__c> projectlist = new list<Project__c>();
		map<Id, Account> customerMap;
		
		// This will contains all the customer
	    if(mapStrCity != null && mapStrCity.size() > 0){
	    	customerMap = new map<Id, Account>([select name, Current_Contract_End_Date__c from Account where Id IN : mapStrCity.keySet()]);
	    	system.debug('1111111111'+customerMap);
	    }
		
		/*Query for the Project Object*/
		projectlist = [select Name, Launch_Date__c, Site_Address_City__c, Project_Name__c from Project__c where Site_Address_City__c IN: cityLaunched 
						AND (Launch_Date__c >= :mapDt.values() AND Launch_Date__c <= :system.today())];
		for(Project__c prj : projectlist){
			projId.add(prj.Id);
		}
		custId.addAll(mapStrCity.keySet());
		
		/*Query for the Customer Projects Object*/
		cusProjlist = [select Id, AccountId__c, Project_Id__c from Customer_Projects__c where Project_Id__c = :projId and AccountId__c = :custId];
		for(Customer_Projects__c csProj : cusProjlist){
			String prjId = csProj.Project_Id__c;
			String cusId = csProj.AccountId__c;
			cusPrjId.add(csProj.Id);
			mapDuplicateCusProj.put(prjId + '-' + cusId, csProj);
		}
		for(String cspId : custId){
			if(projectlist != null && projectlist.size()>0){
				for(Project__c prj : projectlist){
					system.debug('1111111 ' + cspId + '...... ' + prj.Project_Name__c);
					if(mapDuplicateCusProj.containsKey(prj.Id + '-' + cspId)){
						CusProjExandNew.add(mapDuplicateCusProj.get(prj.Id + '-' + cspId));
					}else{
						CusProjinsert.add(new Customer_Projects__c(Project_Id__c = prj.Id, AccountId__c = cspId));
					}
				}
			}
		}
		try{
			if(CusProjinsert != null && CusProjinsert.size() > 0){
				insert CusProjinsert;
				CusProjExandNew.addAll(CusProjinsert);
			}
		}catch(DMLException ex){
			system.debug(ex);
		}
		/*Query for List of Values Object */
		lovList = [Select Name, Entity_Name__c, Entity_Type__c from List_of_Values__c where Entity_Type__c = 'Package' AND Name IN('PAS', 'FTR')];
		for(List_of_Values__c lv : lovList){
			if(lv.Entity_Type__c == 'Package'){
				lovmap.put(lv.Name, lv);
			}
		}
		/*Query for Customer Package Object*/
		custPkgList = [select Name, Customer_Project__c, List_of_Values__c,List_of_Values__r.Name from Project_Cust_Packages__c where Customer_Project__c = : cusPrjId];
		for(Project_Cust_Packages__c csPkg : custPkgList){
			if(csPkg.List_of_Values__r.Name == 'PAS')
				mapPrjCustPkgDup.put(csPkg.Customer_Project__c + '-PAS', csPkg);
			else if(csPkg.List_of_Values__r.Name == 'FTR')
				mapPrjCustPkgDup.put(csPkg.Customer_Project__c + '-FTR', csPkg);
		}
		for(Customer_Projects__c custProj : CusProjExandNew){
			system.debug('////////'+custProj);
			if(!mapPrjCustPkgDup.containsKey(custProj.Id + '-PAS')){
				if(lovmap != null && lovmap.size() > 0 && lovmap.containsKey('PAS') && (customerMap != null && customerMap.size() > 0 && customerMap.containsKey(custProj.AccountId__c)))
					custPkginsert.add(new Project_Cust_Packages__c(Customer_Project__c = custProj.Id, List_of_Values__c = lovmap.get('PAS').Id, Service_Requested_Date__c = System.today(), End_Date__c = customerMap.get(custProj.AccountId__c).Current_Contract_End_Date__c));
			}
			if(!mapPrjCustPkgDup.containsKey(custProj.Id + '-FTR')){
				if(lovmap != null && lovmap.size() > 0 && lovmap.containsKey('FTR') && (customerMap != null && customerMap.size() > 0 && customerMap.containsKey(custProj.AccountId__c)))
					custPkginsert.add(new Project_Cust_Packages__c(Customer_Project__c = custProj.Id, List_of_Values__c = lovmap.get('FTR').Id, Service_Requested_Date__c = System.today(), End_Date__c = customerMap.get(custProj.AccountId__c).Current_Contract_End_Date__c));
			}
		}
		try{
			if(custPkginsert != null && custPkginsert.size() > 0)
				insert custPkginsert;
		}catch(DMLException ex){
			system.debug(ex);
		}
	}
}