Dev-RBI/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/CRM_Report__c.object
<CustomObject>
    <description>Used to store list of project reports</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Stores relationship with project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CRM Report</label>
    <nameField>
        <displayFormat>RPT-{0000000}</displayFormat>
        <label>Report Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRM Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Customer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Developer_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Be_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is flag which will determine whether a project needs to be displayed to the Customer or not. If it is Y,, then it will not be displayed to any Customer.</description>
        <label>To Be Approved</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_CreateNewProject.cls
/*
    Type:       Custom Controller
    Purpose:    Used to Create New projects by a Customer on the Customer Portal Home Page.         

    Used By:   RBI_CreateNewProject.page
    ---------------------------------------------------------------
    History:

    12-Apr-2013     Created     Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_CreateNewProject {

    public Account acc{get; set;}
    public list<Account> acclst;
    public Project__c prj{get; set;}
    public ApexPages.StandardController sController;
    public list<CRM_Report__c> rptlist {get;set;}
    public string AcctId     = '';
    public list<Customer_Projects__c> approvallist {get;set;}
    public string appStatus {get;set;}  
    String  prjId;
    
    public RBI_CreateNewProject(ApexPages.StandardController stdCon){
        sController = stdCon;
        this.prj=(Project__c)stdCon.getRecord();
        AcctId  = UserUtil.CurrentUser.AccountId; //Logged in user's account id     
        prjId = prj.Id;
    }
    
    public pageReference AddValue() {
        acclst = new list<Account>();
        acc = new Account();
        acclst = [select BillingStreet, BillingCity, BillingState, BillingCountry, BillingPostalCode, Phone from Account where Id =:prj.Developer_Id__c];
        acc = acclst[0];
        return null;
    }
    
    public pagereference save(){
    
        prj.To_Be_Approved__c = true;
        try{
	        insert prj;
	        list<Customer_Projects__c> objCustProjlst = new list<Customer_Projects__c>();
	        objCustProjlst.add(new Customer_Projects__c(Project_Id__c = prj.Id, AccountId__c = AcctId));
	        if(objCustProjlst != null)
	            Database.insert(objCustProjlst);
        }catch(DMLException e){
        	ApexPages.addMessages(e);
            return null;
        }
        PageReference myProjectPage = Page.RBI_MyProjects;
        return myProjectPage;
    }
    
    public PageReference doCancel(){
        PageReference Pg = Page.RBI_MyProjects;
        return Pg;
    }
    
}