Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Weightage_Basement__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Weightage - Basement (Footings, Retaining Walls and Water Proofing)</description>
        <inlineHelpText>Weightage - Basement (Footings, Retaining Walls and Water Proofing)</inlineHelpText>
        <label>Weightage - Basement(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Electrification_Sanitation__c</fullName>
        <defaultValue>0.075</defaultValue>
        <label>Weightage-Electrification &amp; Sanitation %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Excavaton_of_Footings__c</fullName>
        <defaultValue>0.3</defaultValue>
        <label>Weightage - Excavaton of Footings(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Finishing__c</fullName>
        <defaultValue>0.075</defaultValue>
        <description>Weightage for Finishing (titles, Doors, QC)</description>
        <inlineHelpText>Weightage for Finishing (titles, Doors, QC)</inlineHelpText>
        <label>Weightage - Finishing(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Masonary__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Weightage for Masonary (Brickwork, Doors and Window Frames)</description>
        <inlineHelpText>Weightage for Masonary ( Brickwork, Doors and Window Frames)</inlineHelpText>
        <label>Weightage - Masonary(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_RCC_Slab_Casting__c</fullName>
        <defaultValue>0.45</defaultValue>
        <label>Weightage - RCC Slab Casting (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>RBI</fullName>
        <active>true</active>
        <label>Realty BI</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Customer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weightage_Basement__c</fullName>
        <label>Weightage - Basement(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Electrification_Sanitation__c</fullName>
        <label>Weightage-Electrification &amp; Sanitation %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Excavaton_of_Footings__c</fullName>
        <label>Weightage - Excavaton of Footings(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Finishing__c</fullName>
        <label>Weightage - Finishing (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Masonary__c</fullName>
        <description>Weightage for Masonary ( Brickwork, Doors and Window Frames)</description>
        <inlineHelpText>Weightage for Masonary ( Brickwork, Doors and Window Frames)</inlineHelpText>
        <label>Weightage - Masonary(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_RCC_Slab_Casting__c</fullName>
        <label>Weightage - RCC Slab Casting (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Type__c</fullName>
        <description>This field deterimes the weightage reference values.</description>
        <label>Weightage Type</label>
        <picklist>
            <picklistValues>
                <fullName>Realty BI</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_CustomerProjectTriggerHandler.cls
public with sharing class RBI_CustomerProjectTriggerHandler {
	public static boolean firstRun = true;
	public ID  CusRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Customer'].Id;
	public ID RbiRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'RBI'].Id;
	public list<Account> Acclist=[Select Id , Weightage_Electrification_Sanitation__c,Weightage_Basement__c,
	                    Weightage_Excavaton_of_Footings__c, Weightage_Finishing__c,
	                    Weightage_RCC_Slab_Casting__c,RecordTypeId,Weightage_Masonary__c from Account WHERE RecordTypeId=:RbiRecType OR RecordTypeId=:CusRecType];
	     
                    
	// Before Insert Trigger
	public void OnBeforeInsert(list<Customer_Projects__c> Cusprojectlist){ 
		if(Cusprojectlist!=null && Cusprojectlist.size()>0){
			for(Customer_Projects__c cusproj : Cusprojectlist){
		    	for(Account Acc : Acclist){
			    	if((cusproj.Weightage_Type__c == 'Realty BI') && (Acc.RecordTypeId==RbiRecType)) {
				    	cusproj.Weightage_Basement__c=Acc.Weightage_Basement__c;
				        cusproj.Weightage_Electrification_Sanitation__c=Acc.Weightage_Electrification_Sanitation__c;
				        cusproj.Weightage_Excavaton_of_Footings__c=Acc.Weightage_Excavaton_of_Footings__c;
				        cusproj.Weightage_Finishing__c=Acc.Weightage_Finishing__c; 
				        cusproj.Weightage_RCC_Slab_Casting__c=Acc.Weightage_RCC_Slab_Casting__c;
				        cusproj.Weightage_Masonary__c=Acc.Weightage_Masonary__c; 
					}
		            else if((cusproj.Weightage_Type__c == 'Customer') && (Acc.RecordTypeId ==CusRecType) && (Acc.Id == cusproj.AccountId__c)) { 
		            	cusproj.Weightage_Basement__c=Acc.Weightage_Basement__c;
				        cusproj.Weightage_Electrification_Sanitation__c=Acc.Weightage_Electrification_Sanitation__c;
				        cusproj.Weightage_Excavaton_of_Footings__c=Acc.Weightage_Excavaton_of_Footings__c;
				        cusproj.Weightage_Finishing__c=Acc.Weightage_Finishing__c; 
				        cusproj.Weightage_RCC_Slab_Casting__c=Acc.Weightage_RCC_Slab_Casting__c;
				        cusproj.Weightage_Masonary__c=Acc.Weightage_Masonary__c;
		            }
		        }
		    }
		}
	}
	//OnBeforeUpdate trigger
	public void OnBeforeUpdate(list<Customer_Projects__c> CusprojectNew, list<Customer_Projects__c> CusprojectOld, Map<Id, Customer_Projects__c> ObjectMap){
		for(Customer_Projects__c cusprj : CusprojectNew){
			if(cusprj.Id == ObjectMap.get(cusprj.Id).Id && ObjectMap.get(cusprj.Id).Weightage_Type__c != cusprj.Weightage_Type__c){
				for(Account Acc1 : Acclist){
			    	if((cusprj.Weightage_Type__c == 'Customer') && (cusprj.AccountId__c==Acc1.Id) && (Acc1.RecordTypeId ==CusRecType) ) { 
				    	cusprj.Weightage_Basement__c=Acc1.Weightage_Basement__c;
				        cusprj.Weightage_Electrification_Sanitation__c=Acc1.Weightage_Electrification_Sanitation__c;
				        cusprj.Weightage_Excavaton_of_Footings__c=Acc1.Weightage_Excavaton_of_Footings__c;
				        cusprj.Weightage_Finishing__c=Acc1.Weightage_Finishing__c; 
				        cusprj.Weightage_RCC_Slab_Casting__c=Acc1.Weightage_RCC_Slab_Casting__c;
				        cusprj.Weightage_Masonary__c=Acc1.Weightage_Masonary__c;
			        }
			        else if((cusprj.Weightage_Type__c == 'Realty BI') && (Acc1.RecordTypeId==RbiRecType)) {
			        	cusprj.Weightage_Basement__c=Acc1.Weightage_Basement__c;
			            cusprj.Weightage_Electrification_Sanitation__c=Acc1.Weightage_Electrification_Sanitation__c;
			            cusprj.Weightage_Excavaton_of_Footings__c=Acc1.Weightage_Excavaton_of_Footings__c;
			            cusprj.Weightage_Finishing__c=Acc1.Weightage_Finishing__c; 
			            cusprj.Weightage_RCC_Slab_Casting__c=Acc1.Weightage_RCC_Slab_Casting__c;
			            cusprj.Weightage_Masonary__c=Acc1.Weightage_Masonary__c;
			        }
		        }
			}
		}
	}
}