Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Weightage_Basement__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Weightage - Basement (Footings, Retaining Walls and Water Proofing)</description>
        <inlineHelpText>Weightage - Basement (Footings, Retaining Walls and Water Proofing)</inlineHelpText>
        <label>Weightage - Basement(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Electrification_Sanitation__c</fullName>
        <defaultValue>0.075</defaultValue>
        <label>Weightage-Electrification &amp; Sanitation %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Excavaton_of_Footings__c</fullName>
        <defaultValue>0.3</defaultValue>
        <label>Weightage - Excavaton of Footings(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Finishing__c</fullName>
        <defaultValue>0.075</defaultValue>
        <description>Weightage for Finishing (titles, Doors, QC)</description>
        <inlineHelpText>Weightage for Finishing (titles, Doors, QC)</inlineHelpText>
        <label>Weightage - Finishing(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Masonary__c</fullName>
        <defaultValue>0.05</defaultValue>
        <description>Weightage for Masonary (Brickwork, Doors and Window Frames)</description>
        <inlineHelpText>Weightage for Masonary ( Brickwork, Doors and Window Frames)</inlineHelpText>
        <label>Weightage - Masonary(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_RCC_Slab_Casting__c</fullName>
        <defaultValue>0.45</defaultValue>
        <label>Weightage - RCC Slab Casting (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Customer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stores the value to indicate Exceptions for an approval from Customer</description>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FTR_File_Path__c</fullName>
        <description>Used to store FTR file path of s3</description>
        <label>FTR File Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weightage_Basement__c</fullName>
        <label>Weightage - Basement(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Electrification_Sanitation__c</fullName>
        <label>Weightage-Electrification &amp; Sanitation %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Excavaton_of_Footings__c</fullName>
        <label>Weightage - Excavaton of Footings(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Finishing__c</fullName>
        <label>Weightage - Finishing (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_Masonary__c</fullName>
        <description>Weightage for Masonary ( Brickwork, Doors and Window Frames)</description>
        <inlineHelpText>Weightage for Masonary ( Brickwork, Doors and Window Frames)</inlineHelpText>
        <label>Weightage - Masonary(%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weightage_RCC_Slab_Casting__c</fullName>
        <label>Weightage - RCC Slab Casting (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to check any Exceptions  are  there  for a visit.</description>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProjecIdVisitType__c</fullName>
        <description>Used in Trigger for duplication.</description>
        <externalId>true</externalId>
        <label>ProjecIdVisitType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_DTRLoad.cls
public with sharing class RBI_DTRLoad {

	public string ProjectId {get;set;}
	public string ProjectName {get;set;}
	public boolean disframe {get;set;}
	public string  FTRpath {get;set;}
	string filename;
	string custprojectid;
	string bucketname;
	boolean execptionflg;
	Customer_Projects__c updcustproj;

	public RBI_DTRLoad(){
		execptionflg = false;
        ProjectId = ApexPages.currentPage().getParameters().get('Id');
        ProjectName = ApexPages.currentPage().getParameters().get('Name');
        custprojectid = ApexPages.currentPage().getParameters().get('custProjectId');
        filename = ApexPages.currentPage().getParameters().get('path');
        bucketname =System.Label.RBI_FTRBucket;
        string ftrvstexternalid = ProjectId+'-First Technical Report';
        list<Visit__c> vstLst = new list<Visit__c>(); 
       	vstLst =[select Id, name, Exception__c from Visit__c where ProjecIdVisitType__c=:ftrvstexternalid ];
       	if(vstLst!=null && vstLst.size()>0)
       	{
       		execptionflg = vstLst[0].Exception__c;
       	}
        if((filename!=null) && (filename!='') && (execptionflg != true))
		{
			
        	AWS_S3_ExampleController awscontroller = new AWS_S3_ExampleController();
        	FTRpath = awscontroller.AWSLogin(filename, bucketname);
		}
	}
	
	public PageReference gotoReport(){
	try{  		
			if(execptionflg == true){
				PageReference pg = new PageReference('/apex/RBI_Detail_Technical_Report_PDF?Id='+ProjectId);
				return pg;				
			}
			else{
				if (filename == null || filename == '' ){
					disframe = false;
					bucketname =System.Label.RBI_FTRBucket;
					string s3path     =System.Label.RBI_S3Link;
					string fileaccess = 'private';
					PageReference myPdf = Page.RBI_Detail_Technical_Report_PDF;
					myPdf.getParameters().put('Id', ProjectId);
					Blob b;
					b = myPdf.getContent();
					string inpfilename = custprojectid+'-'+ProjectName +'-DTR.pdf';
					//call function to upload the FTR in s3
					AWS_S3_ExampleController awscls = new AWS_S3_ExampleController();
					awscls.uploadFilesystemDoc(bucketname,inpfilename,b,fileaccess);
					//after upload  update the path on customer package
					s3path = s3path+'/'+bucketname+'/'+inpfilename;
					if(custprojectid != null && custprojectid !='')
					{
						updcustproj = new Customer_Projects__c(Id = custprojectid,FTR_File_Path__c=inpfilename);
						Database.update(updcustproj);
					}		
					PageReference pg = new PageReference('/apex/RBI_Detail_Technical_Report_PDF?Id='+ProjectId);
					return pg;
				}else{
					disframe = true;
					return null;
				}
			}
		}catch(Exception ex){
    		System.debug('EXCEPTION: ' + ex);			
		}		
		return null;
	}
	
	@IsTest(SeeAllData=true)  
	static void DTRLoadTest() {
		
		string bktname = System.Label.RBI_FTRBucket;
		string s3pth = System.Label.RBI_S3Link;
		string pth;
		ID  CusRecType = [SELECT Id FROM RecordType WHERE Name = 'Customer'].Id;
		list<Account> acc = new list<Account>();
        Account Acnt = new Account(Name = 'TestLastName',RecordTypeId=CusRecType);
        acc.add(Acnt);
        insert acc;
		
		list<Project__c> projlist = new list<Project__c>();
		Project__c proj = new Project__c(Project_Name__c='Test Class', Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
										 City__c ='test', Brochure_Zipcode__c = '568980', Site_Address_zipcode__c = '412578', 
										 Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today());
		projlist.add(proj);
		insert projlist;
		
		list<Customer_Projects__c> customerProjectlist = new list<Customer_Projects__c>();
		Customer_Projects__c cp = new Customer_Projects__c(Project_Id__c = projlist[0].Id, AccountId__c = acc[0].Id,Weightage_Basement__c=3,
									Weightage_Electrification_Sanitation__c=3,Weightage_Excavaton_of_Footings__c=1,Weightage_Finishing__c=5,
									Weightage_Masonary__c=6,Weightage_RCC_Slab_Casting__c=4, FTR_File_Path__c = 'Test Path');
		customerProjectlist.add(cp);
		insert customerProjectlist;
		
		//start test class method
       	System.Test.startTest();
       	
       	//Instantiate the RBI_DTRLoadPage
		PageReference dtrLoad = Page.RBI_DTRLoadPage;
		System.Test.setCurrentPage(dtrLoad);
		
		//Instantiate the class which is used in the page above
		apexpages.currentpage().getparameters().put('projectId' , projlist[0].Id);
		apexpages.currentpage().getparameters().put('ProjectName' , projlist[0].Project_Name__c);
		apexpages.currentpage().getparameters().put('custprojectid' , customerProjectlist[0].Id);
		pth = apexpages.currentpage().getparameters().put('FTRpath' , customerProjectlist[0].FTR_File_Path__c);
		RBI_DTRLoad rbiDtr = new RBI_DTRLoad();
		
		rbiDtr.FTRpath = null;
		rbiDtr.disframe = false;
		rbiDtr.gotoReport();
		
		AWS_S3_ExampleController awscon = new AWS_S3_ExampleController();
		rbiDtr.FTRpath = awscon.AWSLogin(customerProjectlist[0].FTR_File_Path__c, bktname);
		rbiDtr.FTRpath =  customerProjectlist[0].FTR_File_Path__c;
		rbiDtr.disframe = true;
		PageReference deTechPDF = Page.RBI_Detail_Technical_Report_PDF;
		System.Test.setCurrentPage(deTechPDF);
		rbiDtr.gotoReport();
		
		//Stop the Test Class
		System.Test.stopTest();
	}
}