Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Developer</fullName>
        <active>true</active>
        <label>Developer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Bank Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Year__c</fullName>
        <label>Completion Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_Project_Address__c</fullName>
        <description>This will hold the address for the other projects by Developer</description>
        <label>Project Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dwelling_Units__c</fullName>
        <label>Dwelling Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Loan Amount (in Crs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_DeveloperOtherProjectsTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@IsTest(SeeAllData=true) 
private class RBI_DeveloperOtherProjectsTestClass {

    static testMethod void DeveloperOtherProject() {
        
        ID  DevRecType = [SELECT Id FROM RecordType WHERE Name = 'Developer'].Id;
        
        list<Account> acc = new list<Account>();
        Account Acnt = new Account(Name = 'TestLastName', RecordTypeId = DevRecType);
        acc.add(Acnt);
        insert acc;
        
        list<List_of_Values__c> lovlist = new list<List_of_Values__c>();
		List_of_Values__c lov = new List_of_Values__c(Name='Other Projects', Entity_Name__c='Other Projects',Entity_Type__c='Other Projects',
								Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, Loan_Amount__c=25000, Dev_Project_Address__c='test unit');
		List_of_Values__c lov1 = new List_of_Values__c(Name='Other Projects1', Entity_Name__c='Other Projects1',Entity_Type__c='Other Projects1',
								Bank_Name__c = 'Axis Bank1', Completion_Year__c = 2012, Dwelling_Units__c=12, Loan_Amount__c=25000, Dev_Project_Address__c='test unit1');					
		lovlist.add(lov);
        lovlist.add(lov1);
		
        
        //start test class method
       	System.Test.startTest();
        
       	//Instantiate the RBI_OtherOngoingCompletedProjects
		PageReference rbiDevOtherproj = Page.RBI_OtherOngoingCompletedProjects;
		System.Test.setCurrentPage(rbiDevOtherproj);
		
		//Instantiate the class which is used in the page above
		Apexpages.currentpage().getparameters().put('AccId' , acc[0].Id);
		ApexPages.StandardController stdCon = new ApexPages.StandardController(lov);
		RBI_DeveloperOtherProjects DevOtherProj = new RBI_DeveloperOtherProjects(stdCon);
		DevOtherProj.AccountId = acc[0].Id;
		DevOtherProj.LOV.Name = 'Other Projects';
		DevOtherProj.LOV.Entity_Type__c = 'Other Projects';
		DevOtherProj.Save();
		
		//Logic for SaveAndNew Method
		ApexPages.StandardController stdCon1 = new ApexPages.StandardController(lov1);
		RBI_DeveloperOtherProjects DevOtherProj1 = new RBI_DeveloperOtherProjects(stdCon1);
		DevOtherProj1.AccountId = acc[0].Id;
		DevOtherProj1.LOV.Name = 'Other Projects';
		DevOtherProj1.LOV.Entity_Type__c = 'Other Projects';
		DevOtherProj1.SaveandNew();
		DevOtherProj.doCancel();
		
		//Stop Test Class
		System.Test.stopTest();
    }
}