Dev-RBI/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Developer</fullName>
        <active>true</active>
        <label>Developer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Group_Email__c</fullName>
        <description>To capture multiple Email Id, used in ProjectTriggerHandler.</description>
        <label>Group Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to denote Primary Contact for an account. Used for Customer Record Type</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Customer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Name__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Bank Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Completion_Year__c</fullName>
        <label>Completion Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_Project_Address__c</fullName>
        <description>This will hold the address for the other projects by Developer</description>
        <label>Project Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dwelling_Units__c</fullName>
        <label>Dwelling Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_Acres__c</fullName>
        <label>Land Area In Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <description>This field is used for Loan details for a Developer</description>
        <label>Loan Amount (in Crs)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Unit__r.Tower_Id__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Surveyor from User Object.</description>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Cust_Packages__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship of Customer project</description>
        <label>Customer Project</label>
        <referenceTo>Customer_Projects__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>List_of_Values__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores reference of master data for List of Values object</description>
        <label>Package Name</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <description>This field is used in Trigger.</description>
        <formula>Customer_Project__r.Project_Id__c &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 5, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 4, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 3, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 2, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 1, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 10, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 9, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 8, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 7, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 6, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 15, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 14, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 13, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 12, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 11, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1)</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Customer_Project__r.Project_Id__r.Name</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Customer_Project__r.Project_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Customer Package</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Package Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Package</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ProjectTriggerHandlerTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RBI_ProjectTriggerHandlerTestClass {

    static testMethod void RBI_ProjectTriggerHandler() {
    	
   	 	Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
   	 	//UserRole r = [Select id from UserRole where Name='Surveyor'];
   	 	UserRole ur = new UserRole(Name = 'Surveyor');
   	 	insert ur;
      	User u = new User(Alias = 'CRMAdmin', Email='standarduser@testorg.com', EmailEncodingKey='UTF-8', LastName='Testing', 
      					LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, City = 'Bangalore', userroleid = ur.Id, 
      					TimeZoneSidKey='America/Los_Angeles', UserName='stduser@testorg.com');
      				
      	System.runAs(u) {
      		System.debug('Current User: ' + UserInfo.getUserName());
      		System.debug('Current Profile: ' + UserInfo.getProfileId());
      		//insert project record for before insert And before update
		
		ID  CusRecType = [SELECT Id FROM RecordType WHERE Name = 'Customer'].Id;
		ID  DevRecType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Developer'].Id;
		      		
      	list<Account> accnt = new list<Account>();
      	Map<Id, Account> ObjectMap = new Map<Id, Account>();//blank
		Account acc = new Account(Name = 'Testclass Account', Description = 'Test', RecordTypeId = CusRecType, BillingCity = 'Delhi');
		Account acc1 = new Account(Name = 'Testclass Account1', Description = 'Test', RecordTypeId = DevRecType, BillingCity = 'Bangalore');
		Account acc2 = new Account(Name = 'Testclass Account2', Description = 'Test', RecordTypeId = DevRecType, BillingCity = 'Chennai');
		accnt.add(acc);
		accnt.add(acc1);
		accnt.add(acc2);
		insert accnt;
		
		list<Account> accnt1 = new list<Account>();
		accnt[2].name = 'Test Account1';
		Account acc3 = new Account(Name = 'Test Account2', Description = 'Test', RecordTypeId = DevRecType, BillingCity = 'Faridabad');
		accnt1.add(accnt[2]);
		accnt1.add(acc3);
		try{
			upsert accnt1;
		}catch(DMLException e){
			system.debug(e);
		}
		   
		list<Contact> cnt = new list<Contact>();
		Contact con = new Contact(LastName = 'LastContact', AccountId = accnt[0].Id, Email = 'test@gmail.com', Primary__c = true, Group_Email__c = 'test1@gmail.com, abc@xyz.com');
		cnt.add(con);
		insert cnt;
      	
      	list<Project__c> projlist = new list<Project__c>();
		Project__c proj = new Project__c(Project_Name__c='Test Class',Status__c='PDS' , Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
										 City__c ='test', Developer_Id__c = accnt[1].Id, Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' , 
										 Launch_Date__c = System.today(),Site_Address_City__c='Bangalore',OwnerId = u.id, Surveyor__c = u.Id);
		Project__c proj1 = new Project__c(Project_Name__c='Test1 Class',Status__c='PMR' ,Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
		 								 City__c ='test', Developer_Id__c = accnt[1].Id, Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' , 
		 								 Launch_Date__c = System.today(),Site_Address_City__c='Hydrabad');
		Project__c proj2 = new Project__c(Project_Name__c='Test2 Class', Status__c='PMS' ,Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
		 								  Brochure_Zipcode__c = '123456', Developer_Id__c = accnt[1].Id, Site_Address_zipcode__c = '654321' , 
		 								  Launch_Date__c = System.today(),Site_Address_City__c='Bangalore');							 								 
		projlist.add(proj);
		projlist.add(proj1);
		projlist.add(proj2);
		insert projlist;
		
		//Id  Accid=System.Label.RBI_AccountId;
		
		list<List_of_Values__c> lovlist = new list<List_of_Values__c>();
		List_of_Values__c lov = new List_of_Values__c(Name='PAS', Entity_Name__c = 'PAS',Entity_Type__c = 'Package',
								Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, Loan_Amount__c=25000, Dev_Project_Address__c='test unit');
		List_of_Values__c lov1 = new List_of_Values__c(Name='FTR',Entity_Name__c = 'FTR',Entity_Type__c = 'Package',
								Bank_Name__c = 'HDFC Bank', Completion_Year__c = 2014, Dwelling_Units__c=13, Loan_Amount__c=24000, Dev_Project_Address__c='test unit2');
		List_of_Values__c lov2 = new List_of_Values__c(Name='CRM Report',Key__c='Followup Report',Entity_Name__c = 'CRM Report',Entity_Type__c = 'Package',
								Bank_Name__c = 'HDFC Bank', Completion_Year__c = 2014, Dwelling_Units__c=13, Loan_Amount__c=24000, Dev_Project_Address__c='test unit2');
		List_of_Values__c lov3 = new List_of_Values__c(Name='PMS',Entity_Name__c = 'PMS',Entity_Type__c = 'Package',
								Bank_Name__c = 'HDFC Bank', Completion_Year__c = 2014, Dwelling_Units__c=13, Loan_Amount__c=24000, Dev_Project_Address__c='test unit2');																
		lovlist.add(lov);
		lovlist.add(lov1);
		lovlist.add(lov2);
		lovlist.add(lov3);
		insert lovlist;
		
		list<Customer_Projects__c> customerProjectlist = new list<Customer_Projects__c>();
		Customer_Projects__c cp = new Customer_Projects__c(Project_Id__c = projlist[0].Id, AccountId__c = accnt[0].Id);
		Customer_Projects__c cp1 = new Customer_Projects__c(Project_Id__c = projlist[1].Id, AccountId__c = accnt[0].Id);
		Customer_Projects__c cp2 = new Customer_Projects__c(Project_Id__c = projlist[2].Id, AccountId__c = accnt[0].Id);
		customerProjectlist.add(cp);
		customerProjectlist.add(cp1);
		customerProjectlist.add(cp2);
		insert customerProjectlist;
		
    	list<Project_Cust_Packages__c> prjCustPack = new list<Project_Cust_Packages__c>();
        Project_Cust_Packages__c ProjCustomPack = new Project_Cust_Packages__c (List_of_Values__c=lov.id, Customer_Project__c=customerProjectlist[0].Id);
        Project_Cust_Packages__c ProjCustomPack1 = new Project_Cust_Packages__c (List_of_Values__c=lov1.id, Customer_Project__c=customerProjectlist[1].Id);
        Project_Cust_Packages__c ProjCustomPack2 = new Project_Cust_Packages__c (List_of_Values__c=lov2.id, Customer_Project__c=customerProjectlist[2].Id);
        prjCustPack.add(ProjCustomPack);
        prjCustPack.add(ProjCustomPack1);
        prjCustPack.add(ProjCustomPack2);
        insert prjCustPack;
    	
		//for update trigger
		//Start Test Class
		Test.startTest();
		
        projlist[1].Project_Name__c='Test1 Class';
		projlist[1].Site_Address_City__c='Bangalore';
		projlist[1].Status__c = 'PMR';
		update projlist[1];
		
		projlist[2].Project_Name__c='Test2 Class';
		projlist[2].Site_Address_City__c='Mumbai';
		projlist[2].Status__c = 'PMR';
		update projlist[2];
		
		RBI_AccountTriggerHandler acTrHand = new RBI_AccountTriggerHandler();
		list<Account> actr = new list<Account>();
		//acTrHand.OnBeforeUpdate(accnt, actr, ObjectMap);
		RBI_ProjectTriggerHandler handler = new RBI_ProjectTriggerHandler();
		proj.Surveyor__c = u.Id;
		
		RBI_ProjectTriggerHandler.wrapEmailProject wrp1 = new RBI_ProjectTriggerHandler.wrapEmailProject(cp1);
		RBI_ProjectTriggerHandler.wrapEmailProject wrp = new RBI_ProjectTriggerHandler.wrapEmailProject(cp1,'sr@gmail.com');
		
		//Stop Test Class
		Test.stopTest();
      	}
    }
}