Dev-RBI/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Developer</fullName>
        <active>true</active>
        <label>Developer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the reference to the Account(developer) for other ongoing projects</description>
        <label>Developer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ongoing and Completed Projects</relationshipLabel>
        <relationshipName>OnGoingProjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_DeveloperOtherProjects.cls
/*
    Type:       Custom Controller
    Purpose:    Used to display the Ongoing and Completed projects of a developer in Customer Portal as a pop-up         

    Used By:   RBI_OtherOnGoingCompletedProjects.page
    ----------------------------------------------------------------------------------
    History:

    24-Apr-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_DeveloperOtherProjects {

	public Account selectedAccount { get; set; }
	public Account[] lstAccount;
    public List_of_Values__c LOV {get;set;}
    public String AccountId;
    public String LOVId;
   
    public ApexPages.StandardController std;
    
   	public RBI_DeveloperOtherProjects(ApexPages.StandardController stdcontroller) {
     	this.std = stdcontroller;
        this.LOV=(List_of_Values__c)stdcontroller.getRecord();
        AccountId = System.currentPagereference().getParameters().get('AccId');
        LOV.Developer__c = AccountId;
        LOV.Name = 'Other Projects';
        LOV.Entity_Type__c = 'Other Projects';
        
    }
    
    public pageReference Save(){
    	
    	/*if(LOV.Project_Type__c == 'Ongoing')
        	LOV.Name = 'Ongoing Projects';
       	if(LOV.Project_Type__c == 'Completed')*/
        	LOV.Name = 'Other Projects';
        	LOV.Entity_Type__c = 'Other Projects'; 	
        	
        insert LOV;
    	PageReference Pg = new PageReference('/' + AccountId);
		return Pg;
    }
    
    public PageReference doCancel(){
		PageReference Pg = new PageReference('/' + AccountId);
		return Pg;
    }
    public PageReference SaveandNew(){
    	insert LOV;
    	LOV = new List_of_Values__c(Developer__c = AccountId, Name = 'Other Projects', Entity_Type__c = 'Other Projects');
    	PageReference newPage = New PageReference('/apex/RBI_OtherOngoingCompletedProjects?AccId='+AccountId);
    	newPage.setRedirect(true);
    	return newPage;
    }
}