Dev-RBI/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Group_Email__c</fullName>
        <description>To capture multiple Email Id, used in ProjectTriggerHandler.</description>
        <label>Group Email</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to indicated whether the project created by Customer has been approved or rejected</description>
        <label>Project Rejected?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Surveyor from User Object.</description>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Be_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is flag which will determine whether a project needs to be displayed to the Customer or not. If it is Y,, then it will not be displayed to any Customer.</description>
        <label>To Be Approved</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Please enter a value before submitting for approval.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Used for Project level visits</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ApproveProject.cls
/*
    Type:       Custom Controller
    Purpose:    Used to approve the projects created by customers (through Customer Portal).         

    Used By:   RBI_ApproveProject.page
    ---------------------------------------------------------------
    History:

    07-May-2013     Created     Tugboat Info Solutions Pvt. Ltd

*/
public class RBI_ApproveProject {

    public Account acc{get; set;}
    public list<Account> acclst;
    public Project__c prj{get; set;}
    public ApexPages.StandardController sController;
    private string AcctId     = '';
    String  prjId;
    String  custProjId;
    list<Visit__c> VisitList;
    Id ProjRecTypeId;
    //Added for Phase2B on 13/8/2013
    public boolean displayPopup {get; set;}
	//public Account objAcc {get; set;}
	//Ends
    public RBI_ApproveProject(ApexPages.StandardController stdCon)
    {
        sController = stdCon;
        this.prj=(Project__c)stdCon.getRecord();
        AcctId  = UserUtil.CurrentUser.AccountId; //Logged in user's account id
        prjId = prj.Id;
        VisitList = new list<Visit__c>();
        
    }
    
    public PageReference AprovPrj(){
        prj.To_Be_Approved__c = false;
        prj.Project_Rejected__c = false;
        update prj;
        system.debug('xxxxxx'+prj);
        if((prj.Launch_Date__c < system.today()) && (prj.To_Be_Approved__c == false)){
            ProjRecTypeId = [select Id,name from RecordType where name='Project' and SObjectType='Visit__c' limit 1].Id;
            Visit__c visit = new Visit__c();
            visit.RecordTypeId = ProjRecTypeId;
            visit.Project__c = prj.Id;
            visit.Visit_Report__c = 'First Technical Report';
            if(prj.Surveyor__c != null){
                visit.Surveyor__c = prj.Surveyor__c;
                visit.OwnerId = prj.Surveyor__c;
            }
            visit.Start_Date__c = system.today();    
            VisitList.add(visit);
                   
        }
        try{
            insert VisitList;
            sendEmail();
        }catch(DMLException e){
            system.debug(e);
        }
        PageReference Pg = Page.RBI_ProjectsForApproval;
        return Pg;
    }
   //Added for Phase2B on 13/8/2013
   public PageReference RejectPrj(){
        
        prj.Project_Rejected__c = true;
        try{
        	update prj;
        	system.debug('xxxxxx'+prj+' yyy '+AcctId);
        	sendEmail();
        }catch(DMLException e){
        	system.debug(e);
        	return null;
        }
        PageReference Pg = Page.RBI_ProjectsForApproval;
        displayPopup = false;
        return Pg;
   }
   // 
    public PageReference doCancel(){
        PageReference Pg = Page.RBI_ProjectsForApproval;
        return Pg;
    }
    
    //Added for Phase2B on 14/8/2013
    public void sendEmail(){
    	User custPrimContact = new User();
    	if(prj.ownerId != null || prj.ownerId != '')
    		custPrimContact = [select Name,ContactId,Contact.Group_Email__c from User where Id = : prj.ownerId];
    	if(custPrimContact != null){	
	    	Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			String[] toAddresses = custPrimContact.Contact.Group_Email__c.split(',');
	        mail.setToAddresses(toAddresses);
	        if(prj.Project_Rejected__c == false)
	        	mail.setTemplateId(System.label.RBI_TempIdForCustProjectApproved);
	        else
	        	mail.setTemplateId(System.label.RBI_TempIdForCustProjectRejected);	
	        mail.setTargetObjectId(custPrimContact.ContactId);
	        mail.setWhatId(prj.Id);
        	Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    	}
    }
    
    public void closePopup()
	{
		displayPopup = false;
	}
	public void showPopup()
	{
		displayPopup = true;
	}
    //End of Phase2B on 14/8/2013
    
}