Dev-RBI/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Developer_Name_Cust_Provided__c</fullName>
        <description>Stores the Developer Name as entered by the Customer</description>
        <label>Developer Name (Cust. Provided)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <formula>Developer_Id__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer_Phone_Cust_Provided__c</fullName>
        <description>Stores the phone number of the developer provided by the Customer</description>
        <label>Developer Phone (Cust. Provided)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plot_Area__c</fullName>
        <label>Plot Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Region__c</fullName>
        <label>Project Region</label>
        <picklist>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to indicated whether the project created by Customer has been approved or rejected</description>
        <label>Project Rejected?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To_Be_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is flag which will determine whether a project needs to be displayed to the Customer or not. If it is Y,, then it will not be displayed to any Customer.</description>
        <label>To Be Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Units__c</fullName>
        <label>Total Units</label>
        <summarizedField>Tower__c.Total_Units__c</summarizedField>
        <summaryForeignKey>Tower__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ProjectsForApproval.cls
/*
    Type:       Custom Controller
    Purpose:    Used to Approve the Projects created by the Customer from Customer Portal.     

    Used By:   RBI_ProjectForApproval.page
    ----------------------------------------------------------------------------------
    History:

    01-May-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_ProjectsForApproval {
	// Variable Declaration
	public list<Project__c> WrapperProjList {get; set;}
 	private String first_picklist_option = '- All -'; 
 	transient String QryString;
 	public Project__c Proj;
	public string     ProjId = '';
	public string     Projectname{get; set;}
	public string     Projectcity{get; set;}	
	public boolean    ProjectFlag = false;
	public boolean    ErrorFlag {get; set;}
	public boolean    flag {get; set;}
	public Id SelectedProjId {get;set;}
	private string AcctId     = '';
	public List<String> SerchAlpabet{get;set;}
	public String SearchVar{get;set;}
	List<Project__c> projList;	
	public list<Project__c> Showpro{set;get;}
	public integer sizee{get;set;}

	//Pagination
	public RBI_PageManager objPageManager {get;set;}   
	public Integer pageSize;
	public List<Project__c> Wrapper1prolist{get;set;}
	public List<Project__c> prolist = new List<Project__c>(); 
	public List<Project__c> proDetails;
	
	/* Constructor */
    public RBI_ProjectsForApproval(){
        WrapperProjList = new list<Project__c>();
        Wrapper1prolist= new List<Project__c>(); 
       	ErrorFlag       = false;
        AcctId          = UserUtil.CurrentUser.AccountId; //Logged in user's account id   
        projList 		= new list<Project__c>();
      	//paging variables
		pageSize = 10; 
        objPageManager = new RBI_PageManager(pageSize);               
        objPageManager.page = 0;
        objPageManager.numberOfRows =0;
        	
		SerchAlpabet=new List<string>{'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','All'};
					
}
    
    /* Action funtion called on initial load */
	public PageReference InitialLoad(){
		projList 		= new list<Project__c>();		
		projList = [Select Id, Name, Project_Name__c, Developer_Id__c, City__c, Land_Area_in_acres__c, Plot_Area__c, Project_Region__c, Site_Address_City__c, Launch_Date__c, Total_Units__c, Developer_Name__c, Developer_Name_Cust_Provided__c, Developer_Phone_Cust_Provided__c From
					Project__c where To_Be_Approved__c = true AND Project_Rejected__c != true];
        WrapperProjList = new list<Project__c>();  
  		SearchVar='All';
  		Showpro = new list<Project__c>();
  		Showpro.addAll(projList);
  		WrapperProjList.addAll(projList);
  		
		if(WrapperProjList!= null){
			sizee=WrapperProjList.size(); 
			objPageManager.numberOfRows = WrapperProjList.size();
		}	
		
		
		return null;
	}    
	
	/* Action funtion called on click of aphabet order */
	public PageReference display() 
	{
		
		Showpro.clear();
		WrapperProjList.clear();
		for(Project__c p:projList)
		{
			if(SearchVar.equals('All'))
			{
				Showpro.add(p);
			 	WrapperProjList.add(p);
			}					
			else
				if((p.Project_Name__c.startsWith(SearchVar.toLowerCase())||p.Project_Name__c.startsWith(SearchVar)))
				{
				   Showpro.add(p);
			 	   WrapperProjList.add(p);					   
				   
				}   
		   
		}
		if(WrapperProjList!= null){
			sizee=WrapperProjList.size(); 
			objPageManager.numberOfRows = WrapperProjList.size();
		}			
		return null;
	}

    // Getter-setter for proDetails used for pagination
  	public List<Project__c> getproDetails(){
  	if((WrapperProjList !=null) && (WrapperProjList.size() >0)){ 
      	 if(Wrapper1prolist !=null)	
       		Wrapper1prolist.clear();
        	for(integer i=objPageManager.startIndex;i<objPageManager.endIndex&&i<WrapperProjList.size();i++){
            	Wrapper1prolist.add(WrapperProjList.get(i));

         }

      } 
       return Wrapper1prolist; 
    } 
    
	public void  setproDetails (List<Project__c> proDetails) {
		this.proDetails = proDetails;
	}    
		
	/* Action funtion called on Search */
    public PageReference searchProjects() {
    	WrapperProjList = new List<Project__c>();
    	QryString = 'Select Id, Name, Project_Name__c, Site_Address_City__c, City__c, Land_Area_in_acres__c, Plot_Area__c, Project_Region__c, Launch_Date__c, Total_Units__c, Developer_Name__c, Developer_Id__c, Developer_Name_Cust_Provided__c, Developer_Phone_Cust_Provided__c From Project__c where To_Be_Approved__c=true AND Project_Name__c LIKE \'%'  + Projectname + '%\'';
    	
    	if(!Projectcity.equals('- All -')) {
   	    	QryString += ' AND Site_Address_City__c LIKE \'%' + Projectcity + '%\'';
   	    }
  		
        projList 		= new list<Project__c>();
        projList 		= Database.query(QryString);
        if(projList == null){
		      ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.INFO, 'No results found');
	          ApexPages.addMessage(errorMessage);   	 		
   	 		
   	 	}
   	 	else{  
		 	WrapperProjList = new list<Project__c>();
	  		SearchVar='All';
	  		Showpro = new list<Project__c>();
	  		Showpro.addAll(projList);
	  		for(Project__c Serv1: projList) {
	        	WrapperProjList.add(Serv1);
	        }   	 				
	  		
			if(WrapperProjList!= null){
				sizee=WrapperProjList.size(); 
				objPageManager.numberOfRows = WrapperProjList.size();
			}	   	    
    }
      return null;
    }
    
    /*This method is refered from RBI_UtilClass to fetch the City values*/
    public List<selectOption> getCity() {
    	Proj = new Project__c();
		list<selectOption> pickvalue;          
    	pickvalue = RBI_UtilClass.getPickValues(Proj, 'Site_Address_City__c', first_picklist_option);
        return  pickvalue;
   }
   
    public pageReference detail()
    {
      PageReference pagref = new PageReference('/apex/RBI_ApproveProject?id='+SelectedProjId);
      return pagref;
      
    }
   
}