Dev-RBI/src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Images</relationshipLabel>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to store tower images</description>
        <label>Tower</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Images</relationshipLabel>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AWS S3 Object</label>
    <nameField>
        <displayFormat>AWS-{0000}</displayFormat>
        <label>AWS S3 Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AWS S3 Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Construction_Status__c.object
<CustomObject>
    <description>Used to store Construction Status</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship with project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Construction Status</relationshipLabel>
        <relationshipName>Construction_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship with Tower</description>
        <label>Tower</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Construction Status</relationshipLabel>
        <relationshipName>Construction_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Construction Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Construction Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Construction Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Remarks__c</fullName>
        <description>Stores the comments from the Customer while approving/rejecting a project</description>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Unit Report generation</description>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Unit Report Details</relationshipLabel>
        <relationshipName>UnitReport</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Construction_Start_Date__c</fullName>
        <label>Construction Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site_Address_Actual__c</fullName>
        <formula>IF(ISBLANK(Site_Address_Line_1__c) , &apos;&apos; , Site_Address_Line_1__c &amp; &apos;,&apos;) &amp; IF(ISBLANK(Site_Address_Line_2__c), &apos;&apos;, Site_Address_Line_2__c &amp; &apos;,&apos;) &amp; IF(ISBLANK(Site_Address_Landmark__c), &apos;&apos; , Site_Address_Landmark__c &amp; &apos;,&apos; ) &amp; IF(ISBLANK(TEXT(Site_Address_City__c )), &apos;&apos; ,TEXT(Site_Address_City__c) &amp; &apos;,&apos;) &amp; IF(ISBLANK(TEXT(  Site_Address_State__c)), &apos;&apos; ,TEXT(  Site_Address_State__c) &amp; &apos;,&apos;) &amp; IF(ISBLANK(Site_Address_zipcode__c), &apos;&apos; ,Site_Address_zipcode__c)</formula>
        <label>Site Address Actual</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Contact_NameDesg__c</fullName>
        <label>Name/Designation of Person</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Units__c</fullName>
        <label>Total Units</label>
        <summarizedField>Tower__c.Total_Units__c</summarizedField>
        <summaryForeignKey>Tower__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>construction_Status__c</fullName>
        <label>Construction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underconstruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halted (Builder)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halted (Court)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halted (External)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Strores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Feedbacks</relationshipLabel>
        <relationshipName>Project_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Feedback</label>
    <nameField>
        <displayFormat>FB-{0000000000}</displayFormat>
        <label>Feedback Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Basement_Floors__c</fullName>
        <label>No.of Basement Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Parking_Floors__c</fullName>
        <label>No.of Parking Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_ResCom_Floors__c</fullName>
        <label>No.of Residential / Commercial Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Construction_Start_Date__c</fullName>
        <label>Construction Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deviation__c</fullName>
        <description>Stores the deviation for a Tower</description>
        <label>Deviation</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Comment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Launched_Units__c</fullName>
        <label>Launched Units</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Avg_Developer_BSP_per_Sq_Ft__c</fullName>
        <label>Max Avg Developer BSP (per Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Avg_Resale_Price_Per_Sqft__c</fullName>
        <description>Used to store Avg Resale Price (Per Sqft)</description>
        <label>Max Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Developer_BSP_per_Sq_Ft__c</fullName>
        <description>Used to store min avg developer BSP</description>
        <label>Min Avg Developer BSP (per Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Resale_Price_Per_Sqft__c</fullName>
        <description>Used to store Min Avg Resale Price (Per Sqft)</description>
        <label>Min Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planned_Basement_Floors__c</fullName>
        <label>No.of Basement Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_Parking_Floors__c</fullName>
        <label>No.of Parking Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_ResCom_Floors__c</fullName>
        <label>No.of Residential / Commercial Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Proposed_Completion_Date__c</fullName>
        <label>Proposed Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ResCommCompare__c</fullName>
        <formula>IF( Actual_ResCom_Floors__c  &lt;  Planned_ResCom_Floors__c ,  Actual_ResCom_Floors__c ,  Planned_ResCom_Floors__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ResCommCompare</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sold_Units__c</fullName>
        <label>Sold Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Structure_as_per_Brochure__c</fullName>
        <label>Tower Structure on site</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Structure_as_per_Plan__c</fullName>
        <label>Structure as per Plan</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Floors__c</fullName>
        <formula>IF( Planned__c  &lt;  Proposed__c , Planned__c ,Proposed__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Floors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Units__c</fullName>
        <label>Total Units</label>
        <summaryForeignKey>Unit__c.Tower_Id__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Total_Floors__c</fullName>
        <description>This will get the Total floors from Tower formula field Total_Floors__c.</description>
        <formula>Tower_Id__r.Max_Floors__c</formula>
        <label>Total Floors</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit_Type__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Unit Type</relationshipLabel>
        <relationshipName>Unit_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Type</label>
    <nameField>
        <displayFormat>UNITTYP-{0000000000}</displayFormat>
        <label>Unit Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ProjectReportPDF.cls
/*
    Type:       Custom Controller
    Purpose:    Used to Generate Project Report in PDF format by Customer in the Customer Portal.     

    Used By:   RBI_ProjectReportPDF.page
    ----------------------------------------------------------------------------------
    History:

    30-Apr-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_ProjectReportPDF {

	public Tower__c Tower{get; set;}
	public Unit__c Unit{get; set;}
	public list <Tower__c> towerlist {get;set;}
	set<Id> TowerIdsSet = new set<Id>();
	public Project__c prj{get; set;}
	public String ProjectPhase {get; set;}
	public String ContactPerson{get; set;}
	public ApexPages.StandardController sController;
	public list<Project_Feedback__c> feedStatApp{get; set;}
	public list<Project_Feedback__c> feedlist;
	public list<Project_Feedback__c> feedRemark{get; set;}	
	public list<CStatuswrapper> WrapperCSList {get; set;} 
    public list<CStatuswrapper> TotalWrapperCSList{get; set;}
    public list<Customer_Projects__c> prjweights{get; set;}
    public Integer TotalFloors{get; set;}
    public Integer ResCommCompare{get; set;}
    Integer noOfTowerRec;
    Double totalPhaseComp;
    public Double average{get;set;}
    public Construction_Status__c ConStat {get;set;}
    public Customer_Projects__c CustWeights {get;set;}
    public decimal calcCS {get;set;}
    public map<Id, String> mapTowerUnitType {get; set;} 
    private string AcctId     = '';
    public string fsideviation {get;set;}
    public list<aggregateResult> UnitList{get; set;}
    public list<aggregateResult> UnitQuery{get; set;}
  	public string unitTypeString {get;set;}
    public string unitTypeStringForMap {get;set;}
    public long longAverage {get;set;}
    public boolean IsPorEnabled {get;set;}    
    private string RBIaccnt = '';
    public string AcctName {get;set;}
	public decimal calcCSRoundDown;
	//For Bar graph
	List<ChartDataItem> items;
	public string ChartData {get;set;}
	list<AWS_S3_Object__c> imgList;
	list<AWS_S3_Object__c> totalimgList;
	public list<RBI_TowerReportPdf.imgdata> imgurlList{get; set;} 	
	public boolean disChart {get;set;}

	public RBI_ProjectReportPDF(ApexPages.StandardController stdCon)
	{
		sController = stdCon;
		this.prj=(Project__c)stdCon.getRecord();
		RBIaccnt =  System.Label.RBI_AccountId;
        AcctId = UserUtil.CurrentUser.AccountId; //Logged in user's account id
        AcctId = (AcctId == null || AcctId == '')?RBIaccnt:AcctId; //set account id to RBI cust record in case it is null
        IsPorEnabled = UserUtil.CurrentUser.IsPortalEnabled;
		AcctName = UserUtil.CurrentUser.contact.account.Name;
		towerlist = new list<Tower__c>();
		prjweights = new list<Customer_Projects__c>();
		feedlist = new list<Project_Feedback__c>();
        feedRemark = new list<Project_Feedback__c>();
        feedStatApp = new list<Project_Feedback__c>();
        WrapperCSList = new list<CStatuswrapper>();
        UnitList = new list<aggregateResult>();
        UnitQuery = new list<aggregateResult>();
       	items = new List<ChartDataItem>(); //graph
       	disChart = false;
        noOfTowerRec = 0;
        totalPhaseComp = 0.0;
        average = 0.0;
        queryTower();
        QueryFeedback();
        WeightsQuery();
        mapForTowerUnitTypeValues();
        QueryAWS();
	}
	
	public void queryTower(){
		towerlist = [SELECT Max_Avg_Developer_BSP_per_Sq_Ft__c,Max_Avg_Resale_Price_Per_Sqft__c, Min_Avg_Developer_BSP_per_Sq_Ft__c,Project__r.Contact_Person__r.name,
                    Min_Avg_Resale_Price_Per_Sqft__c , Deviation__c, Id, Total_Floors__c, ResCommCompare__c, Launched_Units__c, Construction_Start_Date__c, Launch_Date__c,
                    Proposed_Completion_Date__c, Actual_Basement_Floors__c, Planned_Basement_Floors__c, Actual_Parking_Floors__c,
                    Planned_Parking_Floors__c, Actual_ResCom_Floors__c, Planned_ResCom_Floors__c, Remarks__c, Name, Project__c,Project__r.Site_Contact_NameDesg__c, 
                    Sold_Units__c,Structure_as_per_Brochure__c, Structure_as_per_Plan__c,Total_Units__c, Project__r.Site_Address_Actual__c,
                    (Select Tower__c, Tower_Name__c, Excavation_of_Footings__c, Basement__c, RCC_Slab_Casting__c,
                    Masonary__c, Electrification_and_Sanitation__c, Finishing__c From Construction_Status__r ORDER BY LastModifiedDate DESC limit 1) 
                    FROM Tower__c where  Project__c = :prj.Id ORDER BY Name];
        if(towerlist != null && towerlist.size() > 0){			
			ContactPerson = towerList[0].Project__r.Site_Contact_NameDesg__c;
			
			for (Tower__c TowIds : towerlist) {
           		TowerIdsSet.add(TowIds.Id);
        	}
        }
	}
	
	/*Query the Project FeedBack Object*/
    public void QueryFeedback(){
        feedlist = [Select List_of_Values_Id__r.Name, List_of_Values_Id__r.Entity_Name__c,  Comments__c From Project_Feedback__c where Project__c =: prj.Id];
        if(feedlist != null && feedlist.size() > 0){
	        for(Project_Feedback__c pf : feedlist){
	            if(pf.List_of_Values_Id__r.Entity_Name__c == 'Remark'){
	                feedRemark.add(pf);
	            }
	            else if(pf.List_of_Values_Id__r.Entity_Name__c == 'Statutory Approval'){
	                feedStatApp.add(pf);
	            }
	        }
        }
    }
	
	/*Query the Customer Project Object*/
    public void WeightsQuery(){
    	prjweights = new list<Customer_Projects__c>();
    	if(AcctId == RBIaccnt){
    		List <Account> accntlst = [Select Id, Name, Weightage_RCC_Slab_Casting__c, Weightage_Masonary__c, Weightage_Finishing__c, Weightage_Excavaton_of_Footings__c,
        					Weightage_Electrification_Sanitation__c, Weightage_Basement__c From Account where Id =:AcctId];
        	if(accntlst != null && accntlst.size() > 0){
        		Account accnt = accntlst[0];
            	prjweights.add(new Customer_Projects__c(
            										Weightage_RCC_Slab_Casting__c = accnt.Weightage_RCC_Slab_Casting__c,
										            Weightage_Masonary__c = accnt.Weightage_Masonary__c,
										            Weightage_Finishing__c = accnt.Weightage_Finishing__c,
										            Weightage_Excavaton_of_Footings__c = accnt.Weightage_Excavaton_of_Footings__c,
										            Weightage_Electrification_Sanitation__c = accnt.Weightage_Electrification_Sanitation__c,
										            Weightage_Basement__c = accnt.Weightage_Basement__c, 
            										AccountId__c = accnt.Id));
      	}
    	}
        else{ 
    		prjweights = [select Project_Id__c, Weightage_Basement__c, Weightage_Electrification_Sanitation__c,Customer_Name__c,
                       	 Weightage_Excavaton_of_Footings__c, Weightage_Finishing__c, Weightage_Masonary__c,
                       	 Weightage_RCC_Slab_Casting__c from Customer_Projects__c where Project_Id__c =:prj.Id and AccountId__c=:AcctId];
        }
      	WrapperCSList = new list<CStatuswrapper>();
       	TotalWrapperCSList = new list<CStatuswrapper>();
        
        if(prjweights != null && prjweights.size() > 0){
            for(Tower__c TL: towerList)
            {
                ConStat = new Construction_Status__c();
                Customer_Projects__c wtobj = new Customer_Projects__c();
                if(TL.Construction_Status__r != null && TL.Construction_Status__r.size() > 0){
                	ConStat = TL.Construction_Status__r;
	               	TotalFloors = (Integer)TL.Total_Floors__c;
	               	ResCommCompare = (Integer)TL.ResCommCompare__c;
	               	calcCS  = RBI_UtilClass.calculateconststatus(ConStat,prjweights[0],TotalFloors,ResCommCompare); 
	               	totalPhaseComp += calcCS;
	               	calcCSRoundDown = calcCS.setscale(2,System.RoundingMode.HALF_UP);
	               	noOfTowerRec++;
	               	TotalWrapperCSList.add(new CStatuswrapper(ConStat, calcCSRoundDown));
	          	}
            }
            if (TotalWrapperCSList != null){
           		for(CStatuswrapper totWrap : TotalWrapperCSList){
           			items.add(new ChartDataItem(totWrap.CStatus.Tower_Name__c, totWrap.TotConstStatus));//graph
        		}
        	}
            if (noOfTowerRec != 0){
            	average = totalPhaseComp/noOfTowerRec;
            	longAverage = average.round();
            	loadChartData();
	     	}
        }
        //loadChartData();
    }
    
    public void mapForTowerUnitTypeValues(){
        set<Id> TowIdsSet = new set<Id>();
        mapTowerUnitType = new map<Id, String>();
        set<Id> unitTypeIds;
        unitTypeStringForMap = '';
        unitTypeString = '';
        unitQuery = [select Unit_Type_Id__r.Unit_Type__c unittyp from Unit__c where 
                    Tower_Id__c IN : TowerIdsSet GROUP BY Unit_Type_Id__r.Unit_Type__c];
        for(aggregateResult aggRes : unitQuery){
        	unitTypeString += (String) aggRes.get('unittyp');
        	unitTypeString +=',';
        }
        if (unitTypeString !=null && unitTypeString != '')
        	unitTypeStringForMap = unitTypeString.substring(0, unitTypeString.length()-1); 
    }
    
    public class CStatuswrapper{
        public Construction_Status__c CStatus {get; set;} 
        public decimal TotConstStatus {get; set;}
        
        public CStatuswrapper(Construction_Status__c CS, decimal TCS)
        {
            CStatus = cs;
            TotConstStatus= TCS;
        }
    }
    
   //Method for loading chart data
	private void loadChartData()
	{
	 //Prepare the chart URL
	 	String chartPath = System.Label.RBI_BarChartlink;
	 	chartData 		 = chartPath +  getChartDataItem(items);
	 	chartData 		 = + chartData +'&chxr=1,0,100,10' + '&chtt= + ' + '&chg=0,10,0,0' + '&chts=000000,11.5';
	 	disChart = true;
	}
	
	//helper function for loadChartData
	private String getChartDataItem(List<ChartDataItem> items)
	{
		String chd = ''; 
	 	String chl = ''; 
	 	for(ChartDataItem citem : items)
	 	{
	    	chd += citem.ItemValue + ',';
	    	chl += citem.sLabel + '|';
	 	}
	 	//remove the last comma or pipe
	 	chd = chd.substring(0, chd.length() -1);
	 	chl = chl.substring(0, chl.length() -1);
		String result = '&chd=t:' + chd + '&chl=' + chl;
	 	return result;
	}// end of method
	
	/*Query the AWS Object for Tower Images*/
    public void QueryAWS(){
    	Set <Id> setTowerIds = new Set <Id>();
		//imgList       = new list<AWS_S3_Object__c>();
		totalimgList  = new list<AWS_S3_Object__c>();
		imgurlList  = new list<RBI_TowerReportPdf.imgdata>();
		string qrystring;
		AWS_S3_ExampleController awscontroller = new AWS_S3_ExampleController();		
		totalimgList  = [select id,bucket_name__c,content_type__c, file_name__c, access__c,Project__c,Tower__c,Tower__r.Name,Tower__r.Project__c,Preview_Link__c,imageurl__c from AWS_S3_Object__c where Tower__r.Project__c = :prj.Id order by Tower__c, createddate desc];
		for(AWS_S3_Object__c awsobj : totalimgList){
			if(setTowerIds.add(awsobj.Tower__c)){
				//imgList.add(awsobj);
				qrystring = '';
				qrystring = awscontroller.AWSLogin(awsobj.file_name__c, awsobj.bucket_name__c);
				imgurlList.add(new RBI_TowerReportPdf.imgdata(qrystring,awsobj.Tower__r.Name));					
		  	}
		}
    }
		      	
	//wrapper class for chart data
	public class ChartDataItem
	{
		public Decimal ItemValue {get;set;}
		public String sLabel {get;set;}
		public ChartDataItem(String Lbl, Decimal Value)
		{
		   this.sLabel = Lbl;
		   this.ItemValue = Value;
		}
	}
}