Dev-RBI/src/objects/AWS_S3_Object__c.object
<CustomObject>
    <description>Represents a bucket and object name as it exists on Amazon S3</description>
    <fields>
        <fullName>Access__c</fullName>
        <label>Access</label>
        <picklist>
            <picklistValues>
                <fullName>FULL_CONTROL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>public-read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WRITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>private</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bucket_Name__c</fullName>
        <label>Bucket Name</label>
        <length>122</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <label>Content Type</label>
        <picklist>
            <picklistValues>
                <fullName>image/gif</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>image/jpeg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>image/png</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text/html</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>text/plain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gif</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>pdf</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>jpg</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preview_Link__c</fullName>
        <formula>HYPERLINK(&apos;https://s3.amazonaws.com/&apos;&amp; Bucket_Name__c &amp;&apos;/&apos;&amp; File_Name__c , 
&apos;https://s3.amazonaws.com/&apos; &amp; Bucket_Name__c &amp;&apos;/&apos;&amp; File_Name__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Open the resource in a new window</inlineHelpText>
        <label>Preview Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Images</relationshipLabel>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Report_Name_Calc__c</fullName>
        <description>Used for DVU and TSR</description>
        <formula>IF(Report_Type__c = &apos;TSR&apos;, &apos;Title Search Report&apos;,Report_Type__c&amp;&apos; Report&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Report Name Calc</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Type__c</fullName>
        <description>Stores the value DVU or TSR</description>
        <label>Report Type</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used to store tower images</description>
        <label>Tower</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Images</relationshipLabel>
        <relationshipName>AWS_S3_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>imageurl__c</fullName>
        <formula>&apos;https://s3.amazonaws.com/&apos; &amp;  Bucket_Name__c  &amp; &apos;/&apos; &amp;  File_Name__c</formula>
        <label>imageurl</label>
        <type>Text</type>
    </fields>
    <label>AWS S3 Object</label>
    <nameField>
        <displayFormat>AWS-{0000}</displayFormat>
        <label>AWS S3 Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AWS S3 Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/CRM_Report__c.object
<CustomObject>
    <description>Used to store list of project reports</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Stores relationship with project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Report_Name_Calc__c</fullName>
        <formula>Report_Name__r.Name</formula>
        <label>Report Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the Report</description>
        <label>Report Name</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>CRM Reports</relationshipLabel>
        <relationshipName>CRM_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This will store the status of the report</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CRM Report</label>
    <nameField>
        <displayFormat>RPT-{0000000}</displayFormat>
        <label>Report Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRM Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_Acres__c</fullName>
        <label>Land Area In Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_DVUTSRImageLoad.cls
/*
    Type:       Custom Controller
    Purpose:    Used to generate the TSR, DVU for a Customer from Customer Portal.        

    Used By:   RBI_DVUTSRLoad.page
    ---------------------------------------------------------------
    History:

    26-Apr-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_DVUTSRImageLoad {
	public AWS_S3_Object__c reportimg{get; set;}  
	public boolean norecordsflg {get; set;}// to indicate no dvu tsr images 
	public string qrystring {get; set;}	
	string projid;
	string reportname;
	list <AWS_S3_Object__c> reportimglst;
	public S3.AmazonS3 as3l {get;set;}
	public RBI_DVUTSRImageLoad(){
        projid  	= ApexPages.currentPage().getParameters().get('ProjectId');	
        reportname  = ApexPages.currentPage().getParameters().get('rptName');
        AWS_S3_ExampleController awscontroller = new AWS_S3_ExampleController();
        as3l = awscontroller.as3;
		reportimg = new AWS_S3_Object__c();
		norecordsflg = false;
		reportimglst  = new list <AWS_S3_Object__c>();
		reportimglst = [select id,bucket_name__c,content_type__c, file_name__c, access__c,Project__c,Tower__c,Tower__r.Name,Tower__r.Project__c,Preview_Link__c,imageurl__c, Report_Type__c, Report_Name_Calc__c from AWS_S3_Object__c where Project__c =: projid and Report_Name_Calc__c =:reportname];
		if(reportimglst != null && reportimglst.size()>0){
			reportimg = reportimglst[0];
			qrystring = awscontroller.AWSLogin(reportimglst[0].file_name__c, reportimglst[0].bucket_name__c);
			norecordsflg = false;
		}
		else{
			norecordsflg = true;
		}
	}
	
   @IsTest(SeeAllData=true)  
    static  void RBI_DVUTSRImageLoadTest() {
    	
    	list<Project__c> projlist = new list<Project__c>();
		Project__c proj = new Project__c(Project_Name__c='Test Class', Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
										 City__c ='test', Launch_Date__c = System.today(), Brochure_Zipcode__c = '568980', 
										 Site_Address_City__c = 'Bangalore', Site_Address_zipcode__c = '412578');
		projlist.add(proj);
		insert projlist;
		
		list<List_of_Values__c> lovlist = new list<List_of_Values__c>();
		List_of_Values__c lov = new List_of_Values__c(Name='DVU Report', Entity_Name__c='CRM Report',Entity_Type__c='/apex/RBI_DVUTSRImageLoad?ProjectId=',Key__c='DVU Report',Value__c='DVU');
		
		lovlist.add(lov);
		insert lovlist;
		
		list<CRM_Report__c> crmlist = new list<CRM_Report__c>();
		CRM_Report__c cr = new CRM_Report__c(Report_Name__c=lov.Id, Project__c = proj.Id,
										 Status__c ='completed');
		crmlist.add(cr);
		insert crmlist;

		list<AWS_S3_Object__c> Awlist = new list<AWS_S3_Object__c>();
		AWS_S3_Object__c aw = new AWS_S3_Object__c(Bucket_Name__c='testbucket',Content_Type__c='pdf', Project__c = proj.Id, Report_Type__c='DVU',file_name__c='testfile');
		Awlist.add(aw);
		insert Awlist;
		
		//start test class method
       	System.Test.startTest();
       	//Instantiate the RBI_RBI_DVUTSRImageLoad which generates the PDF
		PageReference DVUimageLoad = Page.RBI_DVUTSRImageLoad;
		System.Test.setCurrentPage(DVUimageLoad);
		apexpages.currentpage().getparameters().put('ProjectId' , projlist[0].Id);
		apexpages.currentpage().getparameters().put('rptName' , lov.Name);
		//instantiate the class
		RBI_DVUTSRImageLoad loadImg = new RBI_DVUTSRImageLoad();
   		loadImg.projid = apexpages.currentpage().getparameters().put('ProjectId' , projlist[0].Id);
       	loadImg.reportname = apexpages.currentpage().getparameters().put('rptName' , lov.Name);
     	
     	AWS_S3_ExampleController awscontroller = new AWS_S3_ExampleController();
     	loadImg.qrystring=awscontroller.AWSLogin(Awlist[0].Bucket_Name__c, Awlist[0].file_name__c);
       	
       	//stop the test class
       	System.Test.stopTest();
    }
}