Dev-RBI/src/objects/Construction_Status__c.object
<CustomObject>
    <description>Used to store Construction Status</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship with project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Construction Status</relationshipLabel>
        <relationshipName>Construction_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship with Tower</description>
        <label>Tower</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Construction Status</relationshipLabel>
        <relationshipName>Construction_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship with visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Construction Status</relationshipLabel>
        <relationshipName>Construction_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Construction Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Construction Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Construction Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Construction_Start_Date__c</fullName>
        <label>Construction Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Developer_Address__c</fullName>
        <description>This field is used in reports.</description>
        <formula>IF(ISBLANK(Developer_Id__r.BillingStreet) , &apos;&apos; , Developer_Id__r.BillingStreet &amp; &apos;,&apos;) &amp; IF(ISBLANK( Developer_Id__r.BillingCity), &apos;&apos;, Developer_Id__r.BillingCity &amp; &apos;,&apos;) &amp; IF(ISBLANK(Developer_Id__r.BillingState), &apos;&apos; , Developer_Id__r.BillingState &amp; &apos;,&apos; ) &amp; IF(ISBLANK(Developer_Id__r.BillingPostalCode ), &apos;&apos; ,Developer_Id__r.BillingPostalCode  &amp; &apos;,&apos;) &amp; IF(ISBLANK(Developer_Id__r.BillingCountry), &apos;&apos; ,Developer_Id__r.BillingCountry)</formula>
        <label>Developer Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <formula>Developer_Id__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Registration_Number__c</fullName>
        <label>License Registration Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_the_Municipal_Corporation__c</fullName>
        <label>Name of the Municipal Corporation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plot_Area__c</fullName>
        <label>Plot Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Surveyor from User Object.</description>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>construction_Status__c</fullName>
        <label>Construction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underconstruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halted (Builder)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halted (Court)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halted (External)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>Construction_Start_Date__c</fullName>
        <label>Construction Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Launched_Units__c</fullName>
        <label>Launched Units</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Avg_Resale_Price_Per_Sqft__c</fullName>
        <description>Used to store Avg Resale Price (Per Sqft)</description>
        <label>Max Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Resale_Price_Per_Sqft__c</fullName>
        <description>Used to store Min Avg Resale Price (Per Sqft)</description>
        <label>Min Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sold_Units__c</fullName>
        <label>Sold Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Construction__c</fullName>
        <label>Construction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Underconstruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <formula>Project__r.Developer_Name__c</formula>
        <label>Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Launched_Units__c</fullName>
        <label>Launched Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Legal_Agency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Legal Agency</description>
        <label>Legal Agency</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits (Legal Agency)</relationshipLabel>
        <relationshipName>Visits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Avg_Developer_BSP_per_Sqft__c</fullName>
        <label>Max Avg Developer BSP(per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Avg_Resale_Price_Per_Sqft__c</fullName>
        <label>Max Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Developer_BSP_per_Sqft__c</fullName>
        <label>Min Avg Developer BSP(per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Resale_Price_Per_Sqft__c</fullName>
        <label>Min Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Address__c</fullName>
        <formula>Project__r.Site_Address_Actual__c</formula>
        <label>Project Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_Units__c</fullName>
        <label>Sold Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Please enter a value before submitting for approval.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Forwarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tower</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Followup</fullName>
        <active>true</active>
        <description>For Followup Visit</description>
        <label>Followup</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ProjectReport.cls
public class RBI_ProjectReport {
    public list<RecordType> Reclist;
    public list<Tower__c> towList {get;set;}
    public list<Visit__c> visitlist {get;set;}
    public String projName{get; set;}
    public String projAddress{get; set;}
    public String DevName{get; set;}
    public String DevAddress{get; set;}
    public String Constatus{get; set;}
    public String visitIdFromURL = '';
    public ApexPages.StandardController std;
    
    public void RBI_ProjectReport (ApexPages.StandardController stdcontroller)
    {
     stdcontroller=std;
      QueryVisit();
      visitIdFromURL = ApexPages.currentPage().getParameters().get('Id');
    }
    
    public void QueryVisit()
    {
        
        visitlist= new list<Visit__c>();
        Reclist =[Select SobjectType, Name, DeveloperName From RecordType where SobjectType ='Visit__c' AND DeveloperName='Followup'];
        visitlist=[Select  Tower__c, Surveyor__c, Status__c, Start_Date__c, Sold_Units__c, RecordTypeId, Project__c, Project__r.id,Project__r.Contact_Person__r.Name, Project__r.Developer_Address__c,Project__r.License_Registration_Number__c,Project__r.Name_of_the_Municipal_Corporation__c,Project__r.Plot_Area__c,Project__r.construction_Status__c,Project__r.Construction_Start_Date__c, Project_Name__c, Project_Address__c,   Min_Avg_Resale_Price_Per_Sqft__c, Min_Avg_Developer_BSP_per_Sqft__c, Max_Avg_Resale_Price_Per_Sqft__c, Max_Avg_Developer_BSP_per_Sqft__c, Legal_Agency__c, Launched_Units__c,Id, Developer_Name__c ,Construction__c  From Visit__c where id=:visitIdFromURL AND RecordTypeId=:Reclist[0].Id ];
        system.debug('the visitlist'+visitlist);
        projName=visitlist[0].Project_Name__c;
        projAddress=visitlist[0].Project_Address__c;
        DevName= visitlist[0].Developer_Name__c;
        DevAddress=visitlist[0].Project__r.Developer_Address__c;
        
        
        
        
    }

}