Dev-RBI/src/objects/Construction_Status__c.object
<CustomObject>
    <description>Used to store Construction Status</description>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship with project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Construction Status</relationshipLabel>
        <relationshipName>Construction_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship with Tower</description>
        <label>Tower</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Construction Status</relationshipLabel>
        <relationshipName>Construction_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Construction Status</label>
    <nameField>
        <displayFormat>CS-{0000}</displayFormat>
        <label>Construction Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Construction Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Detail_Price_List__c.object
<CustomObject>
    <description>Stores project level &amp; visit level price list information</description>
    <fields>
        <fullName>Project_Name__c</fullName>
        <description>Used in Visit trigger handler.</description>
        <formula>Tower__r.Project__r.Name</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Id</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Detail Price List</relationshipLabel>
        <relationshipName>Detail_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tower__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tower</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Detail Price List</relationshipLabel>
        <relationshipName>Detail_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Detail Price List</label>
    <nameField>
        <displayFormat>DPL-{0000}</displayFormat>
        <label>Detail Price List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Detail Price List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used for Unit Report generation</description>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Unit Report Details</relationshipLabel>
        <relationshipName>UnitReport</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <description>Stores the Discount offered for a particular plan type</description>
        <label>Discount %</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Store plan type for List of value object</description>
        <label>Plan Type</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship with project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <displayFormat>PPId- {0000000000}</displayFormat>
        <label>Payment Plan Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Construction_Start_Date__c</fullName>
        <label>Construction Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Developer_Address__c</fullName>
        <description>This field is used in reports.</description>
        <formula>IF(ISBLANK(Developer_Id__r.BillingStreet) , &apos;&apos; , Developer_Id__r.BillingStreet &amp; &apos;,&apos;) &amp; IF(ISBLANK( Developer_Id__r.BillingCity), &apos;&apos;, Developer_Id__r.BillingCity &amp; &apos;,&apos;) &amp; IF(ISBLANK(Developer_Id__r.BillingState), &apos;&apos; , Developer_Id__r.BillingState &amp; &apos;,&apos; ) &amp; IF(ISBLANK(Developer_Id__r.BillingPostalCode ), &apos;&apos; ,Developer_Id__r.BillingPostalCode  &amp; &apos;,&apos;) &amp; IF(ISBLANK(Developer_Id__r.BillingCountry), &apos;&apos; ,Developer_Id__r.BillingCountry)</formula>
        <label>Developer Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <formula>Developer_Id__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Possesion_Date__c</fullName>
        <label>Expected Possesion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Registration_Number__c</fullName>
        <label>License Registration Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_the_Municipal_Corporation__c</fullName>
        <label>Name of the Municipal Corporation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plot_Area__c</fullName>
        <label>Plot Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Phase__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Phase</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects (Project Phase)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Address_Actual__c</fullName>
        <formula>IF(ISBLANK(Site_Address_Line_1__c) , &apos;&apos; , Site_Address_Line_1__c &amp; &apos;,&apos;) &amp; IF(ISBLANK(Site_Address_Line_2__c), &apos;&apos;, Site_Address_Line_2__c &amp; &apos;,&apos;) &amp; IF(ISBLANK(Site_Address_Landmark__c), &apos;&apos; , Site_Address_Landmark__c &amp; &apos;,&apos; ) &amp; IF(ISBLANK(TEXT(Site_Address_City__c )), &apos;&apos; ,TEXT(Site_Address_City__c) &amp; &apos;,&apos;) &amp; IF(ISBLANK(TEXT(  Site_Address_State__c)), &apos;&apos; ,TEXT(  Site_Address_State__c) &amp; &apos;,&apos;) &amp; IF(ISBLANK(Site_Address_zipcode__c), &apos;&apos; ,Site_Address_zipcode__c)</formula>
        <label>Site Address Actual</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>construction_Status__c</fullName>
        <label>Construction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Underconstruction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halted (Builder)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halted (Court)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Halted (External)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Strores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Feedbacks</relationshipLabel>
        <relationshipName>Project_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Feedback</label>
    <nameField>
        <displayFormat>FB-{0000000000}</displayFormat>
        <label>Feedback Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>Construction_Start_Date__c</fullName>
        <label>Construction Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Deviation__c</fullName>
        <description>Stores the deviation for a Tower</description>
        <label>Deviation</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Comment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Launched_Units__c</fullName>
        <label>Launched Units</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Avg_Developer_BSP_per_Sq_Ft__c</fullName>
        <label>Max Avg Developer BSP (per Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Avg_Resale_Price_Per_Sqft__c</fullName>
        <description>Used to store Avg Resale Price (Per Sqft)</description>
        <label>Max Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Developer_BSP_per_Sq_Ft__c</fullName>
        <description>Used to store min avg developer BSP</description>
        <label>Min Avg Developer BSP (per Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Avg_Resale_Price_Per_Sqft__c</fullName>
        <description>Used to store Min Avg Resale Price (Per Sqft)</description>
        <label>Min Avg Resale Price (Per Sqft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit_Type__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Unit Type</relationshipLabel>
        <relationshipName>Unit_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Unit Type</label>
    <nameField>
        <displayFormat>UNITTYP-{0000000000}</displayFormat>
        <label>Unit Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ProjectUnitClassTest.cls
public with sharing class RBI_ProjectUnitClassTest {

	public String selectedTowers {get; set;}
	
	public Id selectedUnit {get;set;}
	public Id selectedPaymType {get;set;}
	public list<Tower__c> towerRecordsForPDF {get;set;}
	public Tower__c TowerRecord{get; set;} 
	public list<Unit__c> UnitValues {get;set;}
	public list<Project_Feedback__c> feedRemark{get; set;}
	public list<Project_Feedback__c> feedStatApp{get; set;}
	public Integer TotalFloors{get; set;}
    public Integer ResCommCompare{get; set;}
	//public Unit__c unitforPDF {get;set;}
	public Id projectId = null;
	public boolean EnabledBuilding{get; set;}
	public List<SelectOption> unitOptions {get; set;}
	public String ProjectAddress{get; set;}
	public Project__c objproject {get;set;}
	public string projectName {get; set;}
	public String selUnitTowerId {get;set;}
	public String selUnitFloor {get;set;}
	public Detail_Price_List__c detailPriceforSelUnit {get;set;}
	//public list<CStatuswrapper> WrapperCSList {get; set;} 
	//public list<floorStrucWrap> floorWrapForPDF {get;set;}
	public Double DeveloperBSP {get;set;}
	public Double Discount{get; set;}
	public Double DiscountedDeveloperBSP{get; set;}
	public Construction_Status__c ConStat {get;set;}
	public list<aggregateResult> finalUnitList{get; set;}
	public decimal calcCS {get;set;}
	private string AcctId = '';
	
	/* Borrower Info */
	public String BorrowerName {get;set;}
	public String BorrowerEmail {get;set;}
	public Project__c ProjectRec {get;set;}
	
	public RBI_ProjectUnitClassTest(){
        projectId = ApexPages.currentPage().getParameters().get('projectId');
        projectName = '';
        unitOptions = new List<SelectOption>() ;
        BorrowerName = '';
        BorrowerEmail = '';
        selUnitTowerId = '';
        selUnitFloor = '';
      /*  detailPriceforSelUnit = new Detail_Price_List__c();
        feedRemark = new list<Project_Feedback__c>();
       	feedStatApp = new list<Project_Feedback__c>();
       	finalUnitList = new list<aggregateResult>();*/
       	//AcctId = UserUtil.CurrentUser.AccountId; //Logged in user's account id
      // 	AcctId = '0019000000NV0Ld';
       	ProjectRec = new Project__c();
       	ProjectRec=[SELECT Id, Project_Name__c from Project__c where id=:projectId];
     }
	
	public list<selectOption> getTypesofPaymPlan(){
		List<SelectOption> options = new List<SelectOption>();
		list<Payment_Plan__c> paymentPlanRec = new list<Payment_Plan__c>();
		paymentPlanRec = [select name, Plan_Type__r.name from Payment_Plan__c where Project__c =: projectId];
		if(paymentPlanRec != null && paymentPlanRec.size()>0){
			for(Payment_Plan__c payPlan:paymentPlanRec){ 
		     	options.add(new SelectOption(payPlan.Id,payPlan.Plan_Type__r.name));
	   		}
		}
		return options;
	}
	public Payment_Plan__c getPaymentType(){
		Payment_Plan__c paymTypeRecord = new Payment_Plan__c();
		if(selectedPaymType != null){
			paymTypeRecord = [select name, Discount__c, Plan_Type__r.name from Payment_Plan__c where Id =: selectedPaymType];
		}
		Discount = paymTypeRecord.Discount__c;
		return paymTypeRecord;
	}
	
	public List<SelectOption> gettowerRecords(){
 		List<SelectOption> options = new List<SelectOption>();
		towerRecordsForPDF = [select Max_Avg_Developer_BSP_per_Sq_Ft__c,Max_Avg_Resale_Price_Per_Sqft__c, Min_Avg_Developer_BSP_per_Sq_Ft__c,
					Min_Avg_Resale_Price_Per_Sqft__c ,Deviation__c , Id,Launched_Units__c,Name,
					Project_Name__c,Project__c,Project__r.name,Project__r.Site_Address_Actual__c, Project__r.Site_Visit_Date__c,Project__r.Project_Phase__c,
					Project__r.Project_Phase__r.name, Project__r.Contact_Person__r.name, Project__r.Contact_Person__c,
					Project__r.Developer_Name__c,Project__r.Developer_Address__c,Project__r.License_Registration_Number__c,
					Project__r.Name_of_the_Municipal_Corporation__c,Project__r.Plot_Area__c, Project__r.construction_Status__c,
					Project__r.Launch_Date__c,Project__r.Construction_Start_Date__c,Project__r.Expected_Possesion_Date__c,
					Sold_Units__c,Structure_as_per_Brochure__c, Structure_as_per_Plan__c,Total_Units__c , 
					(Select Tower__c, Tower_Name__c, Excavation_of_Footings__c, Basement__c, RCC_Slab_Casting__c,
                    Masonary__c, Electrification_and_Sanitation__c, Finishing__c From Construction_Status__r) from Tower__c where Project__c = : projectId];
					
		projectName = towerRecordsForPDF[0].Project_Name__c;
		ProjectAddress = towerRecordsForPDF[0].Project__r.Site_Address_Actual__c;
				
		if (towerRecordsForPDF.Size() >0){
			for(Tower__c tower:towerRecordsForPDF){ 
		     	options.add(new SelectOption(tower.Id,tower.name));
	   		}
	    }
	   
	    return options;
	}
	
	public void getPopUnitPicklst(){
		
		UnitValues = [select name, Floor__c, Unit_Type__c,Tower_Id__c, Tower_Id__r.name,Tower_Id__r.Avg_Resale_Price_per_Sq_Ft__c,
		Carpet_Area_Sq_Ft__c, Built_up_area_Sq_Ft__c from Unit__c where Tower_Id__c = : selectedTowers];
		if (UnitValues != null && UnitValues.Size() >0){
			for(Unit__c unit:UnitValues){
		     	unitOptions.add(new SelectOption(unit.Id,unit.name));
	   		}
		}
		
	}
	
    public PageReference populatePicklistValue(){
    	if(SelectedTowers != '--None--'){
	    	unitOptions = new List<SelectOption>() ;
    		getPopUnitPicklst();
    	}
    	else{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select Tower Name'));
		}
    	return null;
    }
    
        
    
	public PageReference generatePDF(){
		
		 if(selectedTowers != null && selectedTowers != '--None--'){
			//PageReference pg = new PageReference('/apex/RBI_ProjectUnitPDFPage');
			//PageReference newPAge = page.SFDCVariables02;
               
			PageReference pg = new PageReference('/apex/RBI_ProjectUnitPDFPageTest');
			pg.getParameters().put('MyVar1', projectId);
			pg.getParameters().put('MyVar2', selectedTowers);
			pg.getParameters().put('MyVar3', SelectedUnit);
			pg.getParameters().put('MyVar4', selectedPaymType);
			
			return pg; 
		}
		else{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select Tower Name'));
		}
		return null;
	}

	
}