Dev-RBI/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Group_Email__c</fullName>
        <description>To capture multiple Email Id, used in ProjectTriggerHandler.</description>
        <label>Group Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to denote Primary Contact for an account. Used for Customer Record Type</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stores the value to indicate Exceptions for an approval from Customer</description>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Unit__r.Tower_Id__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Cust_Packages__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <description>To get account Id from Customer Project.</description>
        <formula>Customer_Project__r.AccountId__c</formula>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship of Customer project</description>
        <label>Customer Project</label>
        <referenceTo>Customer_Projects__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LOV_Name__c</fullName>
        <description>This field is used in Trigger.</description>
        <formula>List_of_Values__r.Name</formula>
        <label>LOV Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_of_Values__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores reference of master data for List of Values object</description>
        <label>Package Name</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <description>This field is used in Trigger.</description>
        <formula>Customer_Project__r.Project_Id__c &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 5, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 4, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 3, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 2, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 1, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 10, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 9, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 8, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 7, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 6, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 15, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 14, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 13, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 12, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 11, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1)</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Customer_Project__r.Project_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Customer Package</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Package Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Package</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Query__c.object
<CustomObject>
    <description>Stores the Document Queries</description>
    <fields>
        <fullName>CustProjAccountId__c</fullName>
        <formula>Customer_Project__r.AccountId__r.Id</formula>
        <label>CustProjAccountId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores Relationship between Queries/Exception and Customer_Project</description>
        <label>Customer Project</label>
        <referenceTo>Customer_Projects__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exception_Status__c</fullName>
        <description>Used to hold status of exception as closed or open</description>
        <label>Exception Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>IF(ISBLANK(Visit__c),  Customer_Project__r.Project_Id__c ,   Visit__r.Project__c )</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Head_EmailId__c</fullName>
        <description>Use to get the email id of the technical head of the project.</description>
        <formula>IF( ISBLANK(Visit__c),  Customer_Project__r.Project_Id__r.Technical_Head__r.Email , Visit__r.Project__r.Technical_Head__r.Email)</formula>
        <label>Technical Head EmailId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Head_Id__c</fullName>
        <description>This is used to get the Technical head Id.</description>
        <formula>Visit__r.Project__r.Technical_Head__c</formula>
        <label>Technical Head Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship  between  Visit and  Queries/Exception</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Query/Exception</label>
    <nameField>
        <displayFormat>Qr-{0000}</displayFormat>
        <label>Query Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries/Exceptions</pluralLabel>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <description>Record type for  Query/Execption object Named as Exception</description>
        <label>Exception</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to check any Exceptions  are  there  for a visit.</description>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Used for Project level visits</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_QueryExceptionTriggerHandler.cls
public with sharing class RBI_QueryExceptionTriggerHandler
 {
	list<Query__c> QueryExplist;
	set<string> visitid;
	set<String> custProjId;
	list<Visit__c> visitlist;
	Map<Id,Query__c> visitmap;
	map<Id,Query__c> visitIdQueryMap;
	map<Id, Query__c> projIdQueryMap;
	set<string>Techheademail;
	string ExceptionId;
	set<Id> projectId;
	set<Id> accountId;
	map<Id, list<Project_Cust_Packages__c>> custPackMap; 
	//map<Id, Project_Cust_Packages__c> custPackMap;
	list<Project_Cust_Packages__c> custPackList;
	list<Contact> primaryContactList; 
	map<Id, Contact> primaryContactMap;
	list<Visit__c> updatevisitlist;
	list<Customer_Projects__c> updateCustProjList; 
	public Static boolean FirstUpdate = true; //Used To avoid recursive call
	
	public void OnBeforeInsert(list<Query__c> QueryExpNew){
		for(Query__c que : QueryExpNew){
			if(que.Record_Type_Name__c == 'Exception' && que.Visit__c != null){
				que.OwnerId = que.Technical_Head_Id__c;
			}
		}
	}
	
	public void OnAfterUpdate(list<Query__c> QueryExpNew, Map<Id, Query__c> ObjectMap)
	{
		if(FirstUpdate){
			FirstUpdate = false;
			updatevisitlist = new list<Visit__c>();
			visitlist = new list<Visit__c>();
			visitmap = new Map<Id,Query__c>();
			QueryExplist = new list<Query__c>();
			visitid = new set<string>();
			custProjId = new set<String>();
			Techheademail = new set<string>();
			visitIdQueryMap = new map<Id, Query__c>();
			projIdQueryMap = new map<Id, Query__c>();
			projectId = new set<Id>();
			accountId = new set<Id>();
			
			for(Query__c qrexp:QueryExpNew){
				if(qrexp.Id == ObjectMap.get(qrexp.Id).Id && ObjectMap.get(qrexp.Id).Exception_Status__c != qrexp.Exception_Status__c){ 
					if(qrexp.Visit__c != null && qrexp.Customer_Project__c == null){
						visitid.add(qrexp.Visit__c);
					}	
					else
					{
						custProjId.add(qrexp.Customer_Project__c);

					}		
				}
			}
			
			system.debug('+++++++'+accountId+' 888 '+custProjId);
			//if(visitid != null && visitid.size() > 0 && custProjId == null)
			if(visitid != null && visitid.size() > 0 && custProjId.size() < 1)
				QueryExplist=[Select id,Exception_Status__c,Visit__c,Visit__r.Project__c,Project_Id__c ,Technical_Head_Id__c,Technical_Head_EmailId__c from Query__c where Visit__c IN : visitid ORDER BY Visit__c]; //Get all the Exception records based on the Visit Ids
			else if(custProjId != null && custProjId.size() > 0)
				QueryExplist=[Select id,Exception_Status__c,Customer_Project__c,Project_Id__c ,Technical_Head_Id__c,Technical_Head_EmailId__c,CustProjAccountId__c from Query__c where Customer_Project__c IN : custProjId ORDER BY Customer_Project__c]; //Get all the Exception records based on the Customer project Ids	
			
			if(visitid != null && visitid.size() > 0 && custProjId.size() < 1){
				//Build a Map of Visit Ids which have at least one exception record with the status as Open. For every Visit record, loop through Exception records with status as Open
				for(Query__c Queryexp : QueryExplist){	   
					if(Queryexp.Exception_Status__c != 'Closed'){  
						visitmap.put(Queryexp.Visit__c,Queryexp); //Build a Visit Map with Visit Ids or Customer Project Ids which need to exculded from updating the Exception flag	
					}else{
						visitIdQueryMap.put(Queryexp.Visit__c,Queryexp);
					}
				}  
				// Loop through the Visit List and check whether the Visit Id is already present in the Map created above. It is not present,
				// it means that the Visit record does not have any Exception records with Status as 'Closed'. Build a list of Visit Records to be updated.
				for(Id vis1:visitid){
					if(visitmap.containsKey(vis1)){
						//Do nothing
					}else{
						Visit__c visit = new Visit__c(Id=vis1, Exception__c = false);
						updatevisitlist.add(visit);
						if(visitIdQueryMap.containsKey(vis1) && vis1 == visitIdQueryMap.get(vis1).Visit__c){
						  	string projId = '';
						   	projId = visitIdQueryMap.get(vis1).Project_Id__c;
						   	projectId.add(projId);
						   	string updvisProjId = visitIdQueryMap.get(vis1).Project_Id__c;
						   	projIdQueryMap.put(updvisProjId,visitIdQueryMap.get(vis1));
						   	system.debug('Hello '+projectId);
						}
				   	}
				}
			}else if(custProjId != null && custProjId.size() > 0){ // This else part is to update the customer project flag when all the child exceptions are closed.
				updateCustProjList = new list<Customer_Projects__c>();
				//Build a Map of Visit Ids which have at least one exception record with the status as Open. For every Visit record, loop through Exception records with status as Open
				for(Query__c Queryexp : QueryExplist){	   
					if(Queryexp.Exception_Status__c != 'Closed'){  
						visitmap.put(Queryexp.Customer_Project__c,Queryexp); //Build a Visit Map with Visit Ids or Customer Project Ids which need to exculded from updating the Exception flag	
					}else{
						visitIdQueryMap.put(Queryexp.Customer_Project__c,Queryexp);
					}
				}  
				accountId = new set<Id>();
				for(Id custId :custProjId){
					if(visitmap.containsKey(custId)){
						//Do nothing
					}else{
						Customer_Projects__c custProj = new Customer_Projects__c(Id=custId, Exception__c = false);
						updateCustProjList.add(custProj);
						if(visitIdQueryMap.containsKey(custId) && custId == visitIdQueryMap.get(custId).Customer_Project__c){
						  	string projId = '';
						   	projId = visitIdQueryMap.get(custId).Project_Id__c;
						   	projectId.add(projId);
						   	//string updvisProjId = visitIdQueryMap.get(custId).Id;
						   	projIdQueryMap.put(custId,visitIdQueryMap.get(custId));
						   	system.debug('Hello '+projectId+' ddddddd '+projIdQueryMap);
						   	
							accountId.add(visitIdQueryMap.get(custId).CustProjAccountId__c);
							system.debug('1212121'+accountId);
						}
				   	}
				}
			}
			try{
				if(updatevisitlist != null && updatevisitlist.size()>0){
					update updatevisitlist;
					QueryCustomerProject();
					system.debug('XXXXXX'+updatevisitlist);
					sendEmail();
						
				}
				if(updateCustProjList != null && updateCustProjList.size()>0){
					update updateCustProjList;
					sendEmailCustPrj();
				}
			}catch(DMLException e){
		    	system.debug(e);
		    }
		}
	}	
	
	/* This method is used for build logic for visit and customer project Exception email */ 
	public void QueryCustomerProject(){
		
       	list<Project_Cust_Packages__c> custPackValue; // used for building custPackMap map
		list<Project_Cust_Packages__c> custPackListinMap; // used for building custPackMap map
		
		custPackList = new list<Project_Cust_Packages__c>();
       	custPackMap = new map<Id, list<Project_Cust_Packages__c>>();
       	//custPackMap = new map<Id, Project_Cust_Packages__c>();
		primaryContactList = new list<Contact>();
       	primaryContactMap = new map<Id, Contact>();
       	system.debug('hhhhhhhhh'+projectId);
		if(projectId != null && projectId.size() > 0 && custProjId.size() < 1){
       		//custPackMap = new map<Id, Project_Cust_Packages__c> ([select Name, LOV_Name__c, List_of_Values__r.Entity_Type__c, Account_Id__c from Project_Cust_Packages__c where Project_Id__c IN : projectId and LOV_Name__c = 'PAS']);
       		custPackList = [select Name, Project_Id__c, LOV_Name__c, List_of_Values__r.Entity_Type__c, Account_Id__c from Project_Cust_Packages__c where Project_Id__c IN : projectId and LOV_Name__c = 'PAS'];
       	}
       	else if(custProjId != null && custProjId.size() > 0){
       		custPackList = [select Name, Project_Id__c, LOV_Name__c, List_of_Values__r.Entity_Type__c, Account_Id__c from Project_Cust_Packages__c where Customer_Project__c IN : custProjId and LOV_Name__c = 'PAS'];
       	}
       	
       	/* Logic to build a map with key and a list (map<Id, list<Project_Cust_Packages__c>> custPackMap)  */
       	for(Project_Cust_Packages__c pcp : custPackList){
       		if(pcp.LOV_Name__c == 'PAS' && pcp.List_of_Values__r.Entity_Type__c == 'Package'){
       			accountId.add(pcp.Account_Id__c);
       			custPackValue = new list<Project_Cust_Packages__c>();
       			custPackListinMap = new list<Project_Cust_Packages__c>();
       			if(pcp.Project_Id__c != null){
       				if(custPackMap != null && custPackMap.size() > 0 && custPackMap.containsKey(pcp.Project_Id__c)){
       					custPackListinMap = custPackMap.get(pcp.Project_Id__c);
       				}
       				if(custPackListinMap != null && custPackListinMap.size() >0){
       					custPackValue.addAll(custPackListinMap);
       				}
       				custPackValue.add(pcp);
       				custPackMap.put(pcp.Project_Id__c,custPackValue);
       			}
       		}
       	}
       	// logic ends here
       	
       	if(accountId != null && accountId.size() > 0){
       		primaryContactList = [select Name, accountId, Primary__c, Email, Group_Email__c from Contact where AccountId IN : accountId and Primary__c = true];
       	}
       	for(Contact con : primaryContactList){
       		if(con.Primary__c == true)
       			primaryContactMap.put(con.AccountId, con);
       	}
       	system.debug('66666666 '+custPackMap);
	}
	
	public void sendEmail(){
		List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
		for(Id projId : projIdQueryMap.keySet()){
			if((projIdQueryMap != null && projIdQueryMap.size() > 0) &&(projIdQueryMap.containsKey(projId) && projId == projIdQueryMap.get(projId).Project_Id__c)){
				list<Project_Cust_Packages__c> custPackLocalList;
					Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		            String[] toAddresses;
		            toAddresses = new String[] {projIdQueryMap.get(projId).Technical_Head_EmailId__c};
		            if((primaryContactMap != null && primaryContactMap.size() > 0)){
		            	if(custPackMap != null && custPackMap.size() > 0 && custPackMap.containsKey(projId)){
		            		custPackLocalList = custPackMap.get(projId);
		            		if(custPackLocalList != null && custPackLocalList.size() > 0){
		            			boolean firstTimeFlag = true;
		            			for(Project_Cust_Packages__c pcp : custPackLocalList){
		            				if(firstTimeFlag){
		            					mail.setTargetObjectId(primaryContactMap.get(pcp.Account_Id__c).Id);
		            					//Added for Phase 2B on 12.08.2013
		            					if(primaryContactMap.get(pcp.Account_Id__c).Group_Email__c != null)
		            						toAddresses.addAll(primaryContactMap.get(pcp.Account_Id__c).Group_Email__c.split(','));
		            					//Adding Ended	
										firstTimeFlag = false;	            					
		            				}else{
		            					//Added for Phase 2B on 12.08.2013
		        						toAddresses.addAll(primaryContactMap.get(pcp.Account_Id__c).Group_Email__c.split(','));
		        						system.debug('.........'+toAddresses);
		        						
		            					//toAddresses.add(primaryContactMap.get(pcp.Account_Id__c).Email);
		            				}
			            		}	
		            		}
		            	}
		            	else{
			            	mail.setTargetObjectId(system.Label.RBI_DefaultContact);
			            	system.debug('22222222 '+mail);
			            }
		            	system.debug('11111111 '+mail);
		            }else{
		            	mail.setTargetObjectId(system.Label.RBI_DefaultContact);
		            	system.debug('22222222 '+mail);
		            }
		            system.debug('555555555'+projId);
		            mail.setToAddresses(toAddresses);
		            system.debug('========'+toAddresses);
		            mail.saveAsActivity = false;
		            mail.setWhatId(projIdQueryMap.get(projId).Visit__c);
		            mail.setTemplateId(System.label.RBI_Exception_Status_Closed);
		            /*if(visitid != null && visitid.size() > 0 && custProjId.size() < 1){
		            	mail.setWhatId(projIdQueryMap.get(projId).Visit__c);
		            	mail.setTemplateId(System.label.RBI_Exception_Status_Closed);
		            }
		            else if(custProjId != null && custProjId.size() > 0){
		            	mail.setWhatId(projIdQueryMap.get(projId).Customer_Project__c);
		            	mail.setTemplateId(System.label.RBI_Exception_Status_Closed_For_Customer);	
		            }*/
		            
					//system.debug('/////////'+toAddresses+ '1110 '+mail );
					emails.add(mail);
		            //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
				//}
			}
		}
		system.debug('/////'+emails);
		if(emails != null && emails.size() > 0)
			Messaging.sendEmail(emails);
	}
	//Helper function used to send emails for customer project expection closure
	public void sendEmailCustPrj(){
		List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
		primaryContactList = new list<Contact>();
       	primaryContactMap = new map<Id, Contact>();
		String[] toAddresses;
		Messaging.SingleEmailMessage mail;
		
		if(accountId != null && accountId.size() > 0){
			primaryContactList = [select Name, accountId, Primary__c, Email, Group_Email__c from Contact where AccountId IN : accountId and Primary__c = true];
		}
		
		for(Contact con : primaryContactList){
			if(con.Primary__c == true)
				primaryContactMap.put(con.AccountId, con);
		}
		
		for(Customer_Projects__c cpObj : updateCustProjList){
		toAddresses = new String[] {projIdQueryMap.get(cpObj.Id).Technical_Head_EmailId__c};				
			mail = new Messaging.SingleEmailMessage();
		    if((primaryContactMap != null && primaryContactMap.size() > 0)){
		        mail.setTargetObjectId(primaryContactMap.get(visitIdQueryMap.get(cpObj.Id).CustProjAccountId__c).Id);
		        //Added for Phase 2B on 12.08.2013
		        toAddresses.addAll(primaryContactMap.get(visitIdQueryMap.get(cpObj.Id).CustProjAccountId__c).Group_Email__c.split(','));
		        //Adding Ended
		       	mail.setToAddresses(toAddresses);
		        mail.saveAsActivity = false;
		        mail.setWhatId(cpObj.Id);
		 		mail.setTemplateId(System.label.RBI_Exception_Status_Closed_For_Customer);	
		 		emails.add(mail);		            	
		    }
		}
		if(emails != null && emails.size() > 0)
			Messaging.sendEmail(emails);       	
	}	
}