Dev-RBI/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Group_Email__c</fullName>
        <description>To capture multiple Email Id, used in ProjectTriggerHandler.</description>
        <label>Group Email</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to denote Primary Contact for an account. Used for Customer Record Type</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stores the value to indicate Exceptions for an approval from Customer</description>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <description>Stores the comments from the Customer while approving/rejecting a project</description>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Head_Email__c</fullName>
        <label>Technical Head Email</label>
        <type>Email</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Land_Area_in_Acres__c</fullName>
        <label>Land Area In Acres</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Unit__r.Tower_Id__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Technical_Head_Email__c</fullName>
        <label>Technical Head Email</label>
        <type>Email</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Cust_Packages__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Customer_Project__r.Project_Id__r.Name</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Customer_Project__r.Project_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Customer Package</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Package Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Package</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Query__c.object
<CustomObject>
    <description>Stores the Document Queries</description>
    <fields>
        <fullName>Closure_Remarks__c</fullName>
        <description>Used to hold  Closure Remarks for Exception.</description>
        <label>Closure Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Status__c</fullName>
        <description>Used to hold status of exception as closed or open</description>
        <label>Exception Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>IF( ISBLANK(Visit__c),  Customer_Project__r.Project_Id__r.Project_Name__c, Visit__r.Project__r.Project_Name__c)</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship  between  Visit and  Queries/Exception</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Query/Exception</label>
    <nameField>
        <displayFormat>Qr-{0000}</displayFormat>
        <label>Query Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries/Exceptions</pluralLabel>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <description>Record type for  Query/Execption object Named as Exception</description>
        <label>Exception</label>
    </recordTypes>
    <recordTypes>
        <fullName>Query</fullName>
        <active>true</active>
        <description>Record type for  Query/Execption object</description>
        <label>Query</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to check any Exceptions  are  there  for a visit.</description>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Forwarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Used for Project level visits</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_QueryExceptionHandlerTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RBI_QueryExceptionHandlerTestClass {

    static testMethod void RBI_QueryExceptionHandler() {
    
    	    // insert project Record
	    	list<Project__c> projlist = new list<Project__c>();
			Project__c proj = new Project__c(Project_Name__c='Test Class',Status__c='PDS' ,Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
											 City__c ='test', Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' , 
											 Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today());
			Project__c proj1 = new Project__c(Project_Name__c='Test1 Class',Status__c='PDS' ,Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today()-30,
											 City__c ='test', Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' , 
											 Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today(),Technical_Head_Email__c='sss@gmail.com');								 
											 
			projlist.add(proj);
			projlist.add(proj1);
			insert projlist;
			
			list<Visit__c> vstList = new list<Visit__c>();
	    	Visit__c vst = new Visit__c(Status__c = 'Approved', Project__c = projlist[0].Id,  Visit_Report__c = 'First Technical Report', Exception__c = true);
	    	vstList.add(vst);
	    	insert vstList;
	    	
		    ID  QueryType = [SELECT Id FROM RecordType WHERE Name = 'Exception'].Id;
		    list<Query__c> querylist= new list<Query__c>();
		    Query__c query= new Query__c (Exception_Status__c = 'Open', Visit__c = vstList[0].Id, RecordTypeId=QueryType);
		    querylist.add(query);
		    insert querylist;

		    querylist[0].Exception_Status__c = 'Closed';
		    querylist[0].Closure_Remarks__c = 'Hello';
		    RBI_QueryExceptionTriggerHandler qry = new RBI_QueryExceptionTriggerHandler();
		    RBI_QueryExceptionTriggerHandler.FirstUpdate = true; 
		    update querylist;
    }	   
	static testMethod void RBI_QueryExceptionHandler1(){
	    	list<Project__c> projlist1 = new list<Project__c>();
			Project__c proj = new Project__c(Project_Name__c='Test Class',Status__c='PDS' ,Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
											 City__c ='test', Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' , 
											 Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today());
			Project__c proj1 = new Project__c(Project_Name__c='Test1 Class',Status__c='PDS' ,Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today()-30,
											 City__c ='test', Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' , 
											 Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today());								 
											 
			projlist1.add(proj);
			projlist1.add(proj1);
			insert projlist1;
			
			 //insert Account Record with type as Customer
			ID  CusRecType = [SELECT Id FROM RecordType WHERE Name = 'Customer'].Id;
			
			list<Account> acc = new list<Account>();
	       	Account Acnt = new Account(Name = 'TestAccount', BillingStreet = 'TestStreet', BillingCity = 'Hyderabad', BillingState = 'AP', BillingCountry = 'India',
	       								BillingPostalCode = '123456', Phone = '124567', Type='Customer',RecordTypeId = CusRecType );
	       	acc.add(Acnt);
	       	insert acc;
	       	
	       	list<Contact> conlist= new list<Contact>();
	       	Contact con = new Contact(AccountId = acc[0].Id, lastname = 'lastname',Email='soumya.samal@tugboat.in',Group_Email__c='ss@gmail.com',Primary__c=true);
	       	conlist.add(con);
	       	insert conlist;
	       	
	       	//insert cus project make association to Account and project
	       	list<Customer_Projects__c> customerProjectlist = new list<Customer_Projects__c>();
			Customer_Projects__c cp = new Customer_Projects__c(Remarks__c = 'Good', Project_Id__c = projlist1[1].Id, AccountId__c = acc[0].Id,Exception__c=true);
			Customer_Projects__c cp1 = new Customer_Projects__c(Remarks__c = 'Good', Project_Id__c = projlist1[1].Id, AccountId__c = acc[0].Id,Exception__c=true);
			customerProjectlist.add(cp);
			customerProjectlist.add(cp1);
			insert customerProjectlist;
			
			//inserting lov record for PAS, FTR 
			list<List_of_Values__c> lovlist = new list<List_of_Values__c>();
	        List_of_Values__c lov = new List_of_Values__c(Name='PAS', Entity_Name__c = 'PAS',Entity_Type__c = 'Package',
	                                Bank_Name__c = 'Axis Bank', Completion_Year__c = 2013, Dwelling_Units__c=12, Loan_Amount__c=25000, Dev_Project_Address__c='test unit');
	        List_of_Values__c lov1 = new List_of_Values__c(Name='FTR',Entity_Name__c = 'FTR',Entity_Type__c = 'Package',
	                                Bank_Name__c = 'HDFC Bank', Completion_Year__c = 2014, Dwelling_Units__c=13, Loan_Amount__c=24000, Dev_Project_Address__c='test unit2');
	        
	        lovlist.add(lov);
	        lovlist.add(lov1);
	        insert lovlist;
	        
	        list<Project_Cust_Packages__c> prjCustPack = new list<Project_Cust_Packages__c>();
	        Project_Cust_Packages__c ProjCustomPack = new Project_Cust_Packages__c (List_of_Values__c=lovlist[0].id, Customer_Project__c=customerProjectlist[0].Id);
	        Project_Cust_Packages__c ProjCustomPack1 = new Project_Cust_Packages__c (List_of_Values__c=lovlist[1].id, Customer_Project__c=customerProjectlist[0].Id);
	        prjCustPack.add(ProjCustomPack);
	        prjCustPack.add(ProjCustomPack1);
	        insert prjCustPack; 
	         ID  QueryType = [SELECT Id FROM RecordType WHERE Name = 'Exception'].Id;
		    list<Query__c> custquerylist= new list<Query__c>();
		    Query__c query1= new Query__c (Exception_Status__c='Open', Customer_Project__c = customerProjectlist[0].Id ,RecordTypeId = QueryType);
		    custquerylist.add(query1);
		    insert  custquerylist;	
		    
		    custquerylist[0].Exception_Status__c='Closed';
		    custquerylist[0].Closure_Remarks__c = 'Hello';
		    RBI_QueryExceptionTriggerHandler qry1 = new RBI_QueryExceptionTriggerHandler();
		    RBI_QueryExceptionTriggerHandler.FirstUpdate = true; 
	    	update custquerylist;
	    		
	   }
    
}