Dev-RBI/src/objects/CRM_Report__c.object
<CustomObject>
    <description>Used to store list of project reports</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Stores relationship with project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This will store the status of the report</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in Reports pdf.</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>CRM Reports</relationshipLabel>
        <relationshipName>CRM_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRM Report</label>
    <nameField>
        <displayFormat>RPT-{0000000}</displayFormat>
        <label>Report Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRM Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Unit__r.Tower_Id__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Surveyor from User Object.</description>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used when (TSR or DVU)visit record is created.</description>
        <label>Team Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Head</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TechnicalHead</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Cust_Packages__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship of Customer project</description>
        <label>Customer Project</label>
        <referenceTo>Customer_Projects__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LOV_Name__c</fullName>
        <description>This field is used in Trigger.</description>
        <formula>List_of_Values__r.Name</formula>
        <label>LOV Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>List_of_Values__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores reference of master data for List of Values object</description>
        <label>Package Name</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <description>This field is used in Trigger.</description>
        <formula>Customer_Project__r.Project_Id__c &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 5, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 4, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 3, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 2, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 1, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 10, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 9, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 8, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 7, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 6, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 15, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 14, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 13, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 12, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 11, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1)</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Customer_Project__r.Project_Id__r.Name</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>Customer_Project__r.Project_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This is used to store the Start date for the service</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Surveyor_Id__c</fullName>
        <description>This field is used in Trigger.</description>
        <formula>Customer_Project__r.Project_Id__r.Surveyor__c</formula>
        <label>Surveyor Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Leader__c</fullName>
        <formula>Customer_Project__r.Project_Id__r.Team_Leader__c</formula>
        <label>Team Leader</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Head__c</fullName>
        <formula>Customer_Project__r.Project_Id__r.Technical_Head__c</formula>
        <label>Technical Head</label>
        <type>Text</type>
    </fields>
    <label>Customer Package</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Package Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Package</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>ProjecIdVisitType__c</fullName>
        <description>Used in Trigger for duplication.</description>
        <externalId>true</externalId>
        <label>ProjecIdVisitType</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Please enter a value before submitting for approval.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Forwarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Visits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture operation manager. This field is used when the owner is changed in the visit. The value will be same as in the project object</description>
        <label>Operation Mgr Data</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Followup</fullName>
        <active>true</active>
        <description>For Followup Visit</description>
        <label>Followup</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Used for Project level visits</description>
        <label>Project</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tower</fullName>
        <active>true</active>
        <description>Indicates Tower level visit</description>
        <label>Tower</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_CustomerPackageTriggerHandler.cls
public without sharing class RBI_CustomerPackageTriggerHandler {
    
    /* This is handler class for RBI_CustomerPackageTrigger */
    
    public list<Project_Cust_Packages__c> PASCustPack = new list<Project_Cust_Packages__c>();
    public list<Project_Cust_Packages__c> FTRCustPack = new list<Project_Cust_Packages__c>();
    public list<Project_Cust_Packages__c> PMSCustPack = new list<Project_Cust_Packages__c>();
    public list<Visit__c> VisitList = new list<Visit__c>();
    public list<CRM_Report__c> CRMReportList = new list<CRM_Report__c>();
    list<List_of_Values__c> PasLOVList = new list<List_of_Values__c>();
    list<List_of_Values__c> PmsLovList = new list<List_of_Values__c>();
    list<List_of_Values__c> FtrLOVList = new list<List_of_Values__c>();
    list<List_of_Values__c> LOVList;
    list<CRM_Report__c> ReportForInsert = new list<CRM_Report__c>();
    Id ProjRecTypeId;
    boolean TSRFlag = false;
    boolean DVUFlag = false;
    boolean FTRFlag = false;
    boolean PMSFlag = false;
    Set<Id> projidset;
    Map<Id,Project_Cust_Packages__c> CustprojMap; 
    map<String,CRM_Report__c> CRMReportMap;
    map<String , Visit__c> mapForDupCheck;
    public list<CRM_Report__c> ReportsforInsert;       
    public RBI_CustomerPackageTriggerHandler(){
        LOVList = [SELECT Entity_Name__c,Entity_Type__c,Key__c,Name, Id FROM List_of_Values__c];
        ProjRecTypeId = [select Id,name from RecordType where name='Project' and SObjectType='Visit__c' limit 1].Id;
    }
    
    /* This method will handle the call from trigger after insert of Customer Package */
    public void OnAfterInsert(list<Project_Cust_Packages__c> custpackageList){
        
        Id ProjId = null;
        Id projIdkey = null;
        set<String> projVisitType = new set<String>(); 
        projidset = new Set<Id>();
        for(Project_Cust_Packages__c pcp:custpackageList ){
            ProjId = pcp.Project_Id__c;
            projidset.add(ProjId);
            projVisitType.add(ProjId+'-TSR Report');
            projVisitType.add(ProjId+'-DVU Report');
            projVisitType.add(ProjId+'-First Technical Report');
            
        }
        system.debug('projVisitType '+projVisitType);
        checkVisitRec(projVisitType); //This call will build the map for dups check
        loadFTRMap();  
        queryForCRMReports();
        system.debug('CustprojMap'+CustprojMap);      
        for(Project_Cust_Packages__c pcp:custpackageList ){
            projId = pcp.Project_Id__c;
            system.debug('map2'+mapForDupCheck.get(projId+'-TSR Report'));
            system.debug('CRMReportMap '+CRMReportMap);
            system.debug('CustprojMap '+CustprojMap);
            system.debug('mapForDupCheck '+mapForDupCheck);
            system.debug('pcp.LOV_Name__c '+pcp.LOV_Name__c);

            if(pcp.LOV_Name__c=='PAS' ){
                PASCustPack.add(pcp);
                
            }else if(pcp.LOV_Name__c=='FTR' && !(mapForDupCheck.containsKey(projId+'-First Technical Report')) && (mapForDupCheck.get(projId+'-First Technical Report') == null)){
                FTRCustPack.add(pcp);
                system.debug('xxxxxx'+FTRCustPack);
            }
            
            //else if(pcp.LOV_Name__c=='PMS' && ((!CRMReportMap.containsKey(projId+)) && (CustprojMap.containsKey(projId))&&(mapForDupCheck.containsKey(ProjId+'-First Technical Report')))){
            else if(pcp.LOV_Name__c=='PMS' && (CustprojMap.containsKey(projId))&&(mapForDupCheck.containsKey(ProjId+'-First Technical Report'))){
                if(mapForDupCheck.get(ProjId+'-First Technical Report').Status__c == 'Approved'){
                    PMSCustPack.add(pcp);
                    projVisitType.add(ProjId+' PMS Report');
                }
            }
            //system.debug('map4 '+mapForDupCheck.get(ProjId+'-First Technical Report').Status__c);
            //system.debug('projVisitType '+projVisitType);
            //system.debug('PASCustPack-- '+pc  p.Customer_Project__c+'level2 '+pcp.Project_Id__c);
        }   
       
        if(LOVList != null && LOVList.size() > 0){
            generateSingleProd(LOVList);
            system.debug('FtrLOVList '+FtrLOVList);
            system.debug('PasLOVList '+PasLOVList);
            system.debug('PASCustPack '+PASCustPack);
            
            //FtrLOVList = generateSingleProd(LOVList, 'FTR');
            //if(custpackageList.LOV_Name__c == 'PAS'){
            
                if(PasLOVList != null && PasLOVList.size() > 0){
                    for(List_of_Values__c LOV : PasLOVList){
                        for(Project_Cust_Packages__c pcp : PASCustPack){
                        		projIdkey = pcp.Project_Id__c;
                                system.debug('PASCustPack '+mapForDupCheck.containsKey(projIdkey+'-'+LOV.Key__c));
                                system.debug('pcp.Customer_Project__r.Project_Id__c '+projIdkey+'-'+LOV.Key__c);
                                if(LOV.Entity_Type__c == 'Service Visit' && !(mapForDupCheck.containsKey(projIdkey+'-'+LOV.Key__c))){
                                    
                                    Visit__c visit = new Visit__c();
                                    //visit. = system.today();
                                    visit.RecordTypeId = ProjRecTypeId;
                                    visit.Project__c = pcp.Project_Id__c;
                                    visit.Visit_Report__c = LOV.Key__c;
                                    visit.ProjecIdVisitType__c = visit.Project__c+'-'+visit.Visit_Report__c;
                                    //visit.Status__c = 'In Progress';//Checking
                                    system.debug('visit.ProjecIdVisitType__c '+visit.ProjecIdVisitType__c);
                                    /*if(pcp.Team_Leader__c != null){
                                        visit.Team_Leader__c = pcp.Team_Leader__c;
                                        visit.OwnerId = pcp.Team_Leader__c;
                                        //visit.Surveyor__c = pcp.Surveyor_Id__c;
                                    }*/
                                    //Added code for 2nd Phase on 05.08.2013
                                    /*
                                    if(pcp.Technical_Head__c != null){
                                        visit.Technical_Head__c = pcp.Operation_Mgr_Data__c; // changed based on phase 2b on 30.08.2013
                                        visit.OwnerId = pcp.Operation_Mgr_Data__c;
                                    }*/
                                    //Adding End on 05.08.2013
                                    visit.Start_Date__c = system.today();    
                                    VisitList.add(visit);
                                    mapForDupCheck.put(projIdkey+'-'+LOV.Key__c,visit);
                                    system.debug('going in pas'); 
                                }   
        
                        }       
                    }
                    /* This is for adding Team Manager
                    for(Visit__c vis : VisitList){
                         
                    }*/
                }
            
            //}
            //if(custpackageList.LOV_Name__c == 'FTR'){
                if(FtrLOVList != null && FtrLOVList.size() > 0){
                    for(List_of_Values__c LOV : FtrLOVList){
                        for(Project_Cust_Packages__c fcp : FTRCustPack){
                        	projIdkey = fcp.Project_Id__c;
                            system.debug('PASCustPack '+fcp.Project_Id__c);
                            system.debug('pcp.Customer_Project__r.Project_Id__c '+fcp.Customer_Project__r.Project_Id__c);
                            if(LOV.Entity_Type__c == 'Service Visit' && !(mapForDupCheck.containsKey(projIdkey+'-'+LOV.Key__c))){
                                Visit__c visit = new Visit__c();
                                visit.RecordTypeId = ProjRecTypeId;
                                //visit. = system.today();
                                visit.Project__c = fcp.Project_Id__c;
                                visit.Visit_Report__c = LOV.Key__c;
                                visit.ProjecIdVisitType__c = visit.Project__c+'-'+visit.Visit_Report__c;
                                system.debug('visit.ProjecIdVisitType__c '+visit.ProjecIdVisitType__c);
                                if(fcp.Surveyor_Id__c != null){
                                    visit.OwnerId = fcp.Surveyor_Id__c;
                                    visit.Surveyor__c = fcp.Surveyor_Id__c;
                                }
                                visit.Start_Date__c = system.today();
                                //visit.OwnerId = fcp.Surveyor_Id__c;
                                VisitList.add(visit);
                                mapForDupCheck.put(projIdkey+'-'+LOV.Key__c,visit);
                                system.debug('going in ftr'+VisitList);
                            }   
                        }       
                    }
                }
                if(PMSCustPack != null && PMSCustPack.size() >0){
                    ReportsforInsert = new List<CRM_Report__c>();
                    for(List_of_Values__c LOV : PmsLovList){
                        for(Project_Cust_Packages__c pmscp : PMSCustPack){
                                system.debug('CRMReportMapinPMS'+CRMReportMap);
                                system.debug('CRMReportMapinPMS'+pmscp);
                            if(!(CRMReportMap.containsKey(pmscp.Project_Name__c+'-'+LOV.Name))){
                                system.debug('Insideloop');
                                CRM_Report__c CRMRecord = new CRM_Report__c();
                                CRMRecord.Report_Name__c = LOV.Id;
                                CRMRecord.Which_Report__c = LOV.Entity_Type__c;
                                CRMRecord.Status__c = 'Completed';
                                CRMRecord.Project__c = pmscp.Project_Id__c;
                                ReportsforInsert.add(CRMRecord);  
                            }
                                
                        }
                        
                    }
                    system.debug('ReportsforInsert'+ReportsforInsert);
                }
            //}
        }
        
       // try{
            system.debug('VisitList1'+VisitList);
            if(VisitList != null && VisitList.size() > 0){
                //system.debug('VisitList2 '+VisitList);
                Database.Insert(VisitList, false);
                //insert VisitList;
                
            }
            if(ReportsforInsert != null && ReportsforInsert.size() > 0){
                system.debug('ReportsforInsert '+ReportsforInsert);
                insert ReportsforInsert;
                
            }            
            /*
            if(CRMReportList != null && CRMReportList.size() > 0)
                insert CRMReportList;
            */    
        /*}
        catch(DmlException e){
            system.debug(e);
        }*/ 
    }
    public void generateSingleProd(list<List_of_Values__c> lovlist){
        
        for(List_of_Values__c lov : lovlist){
            if(lov.Entity_Name__c == 'PAS')
                PasLOVList.add(lov);
            else if(lov.Entity_Name__c == 'FTR')
                FtrLOVList.add(lov);    
            else if(lov.Entity_Name__c == 'CRM Report' && lov.Key__c == 'Followup Report')
                PmsLovList.add(lov);    
        }
    }
    /* This method is to check whether that project is already having visit records or not */
    
    
    public void checkVisitRec(set<String> projVisitType){
        mapForDupCheck = new map<String, Visit__c>();
        string ProjIdReport = '';
        list<Visit__c> visitListCheck = [select name, Visit_Report__c, Project__c,Status__c from Visit__c where ProjecIdVisitType__c IN : projVisitType];
        system.debug('visitListCheck '+visitListCheck);
        for(Visit__c vis : visitListCheck){
            ProjIdReport = vis.Project__c+'-'+vis.Visit_Report__c;
            mapForDupCheck.put(ProjIdReport, vis);              
        }
    }
    
    list<CRM_Report__c> crmList;
    /* query for CRM Report based on project */
    public void queryForCRMReports(){
        CRMReportMap = new map<String,CRM_Report__c>();
        crmList = [select name, Report_Name__c,Report_Name__r.Name, Project__c, Project__r.Id, Generate_Report__c, Project__r.Name from CRM_Report__c where Project__c IN : projidset];
        for(CRM_Report__c crmrep : crmList){
            if((crmrep.Report_Name__r.Name == 'Project Report')||(crmrep.Report_Name__r.Name == 'Unit Report')||(crmrep.Report_Name__r.Name == 'Tower Report')){
        //  if(crmrep.Generate_Report__c == 'PMS'){
                CRMReportMap.put(crmrep.Project__r.Name+'-'+crmrep.Report_Name__r.name,crmrep);
                //break;
            }
        }
    }
       private void loadFTRMap(){
        CustprojMap = new Map<Id,Project_Cust_Packages__c>();
        List<Project_Cust_Packages__c> custpckg= [Select Customer_Project__r.Project_Id__c,Id,Name From Project_Cust_Packages__c where Customer_Project__r.Project_Id__c IN : projidset AND LOV_Name__c = 'PMS'];
        system.debug('AA'+custpckg+'CC'+projidset);
        for(Project_Cust_Packages__c cpk :custpckg){
            if(!(CustprojMap.containsKey(cpk.Customer_Project__r.Project_Id__c)))
                CustprojMap.put(cpk.Customer_Project__r.Project_Id__c, cpk);
        }
        system.debug('BB'+CustprojMap);
    }
}