Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stores the value to indicate Exceptions for an approval from Customer</description>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PAS_Manager_Email__c</fullName>
        <description>This field is updated when the PAS Manager is changed</description>
        <label>PAS Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used when (TSR or DVU)visit record is created.</description>
        <label>Team Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Head</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TechnicalHead</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Query__c.object
<CustomObject>
    <description>Stores the Document Queries</description>
    <fields>
        <fullName>Closure_Remarks__c</fullName>
        <description>Used to hold  Closure Remarks for Exception.</description>
        <label>Closure Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Status__c</fullName>
        <description>Used to hold status of exception as closed or open</description>
        <label>Exception Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_Closure_Date__c</fullName>
        <description>Used as  Expected Closure Date for Exception</description>
        <label>Expected Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Closure_Email_Date__c</fullName>
        <description>Used to give one day before date of expected closure date(Used in ExceptionAlertBatch class).</description>
        <formula>Expected_Closure_Date__c - 1</formula>
        <label>Expected Closure Email Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PAS_Manager_Email__c</fullName>
        <label>PAS Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>IF( ISBLANK(Visit__c),  Customer_Project__r.Project_Id__r.Project_Name__c, Visit__r.Project__r.Project_Name__c)</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_Description__c</fullName>
        <description>used as Description field for both query and Exception.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Query_Resolved_Date__c</fullName>
        <description>Used as Close Date for both Query and Exception.</description>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Team_Leader_Email__c</fullName>
        <description>Used   Visit TeamLeader email through CrossObject Formula field in Query\Exception</description>
        <formula>IF( ISBLANK(Visit__c),  Customer_Project__r.Project_Id__r.Team_Lead_Email__c ,  Visit__r.Project__r.Team_Lead_Email__c )</formula>
        <label>Team Leader Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Head_EmailId__c</fullName>
        <description>Use to get the email id of the technical head of the project.</description>
        <formula>IF( ISBLANK(Visit__c),  Customer_Project__r.Project_Id__r.Technical_Head__r.Email , Visit__r.Project__r.Technical_Head__r.Email)</formula>
        <label>Technical Head EmailId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship  between  Visit and  Queries/Exception</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Query/Exception</label>
    <nameField>
        <displayFormat>Qr-{0000}</displayFormat>
        <label>Query Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries/Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to check any Exceptions  are  there  for a visit.</description>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Forwarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Visits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture operation manager. This field is used when the owner is changed in the visit. The value will be same as in the project object</description>
        <label>Operation Mgr Data</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ExceptionAlertBatchTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RBI_ExceptionAlertBatchTestClass {

    static testMethod void ExceptionAlertMethod() {
        
        //Querying user from org
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		
		list<UserRole> ur = [select name from UserRole where Name = 'Technical Head'];
		
		User u = new User(Alias = 'CRMAdmin', Email='manjunath.rao@tugboat.in', EmailEncodingKey='UTF-8', LastName='Testing', FirstName='FstName',
      					LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, City = 'Bangalore', userroleid = ur[0].Id, 
      					TimeZoneSidKey='America/Los_Angeles', UserName='stduser@testorg.com');
      	insert u;
      	System.runAs(u){
      		list<Project__c> projlist = new list<Project__c>();
			Project__c proj = new Project__c(Project_Name__c='Test Class',Status__c='PDS' , Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
											 City__c ='test', Brochure_Zipcode__c = '123456' , Site_Address_zipcode__c = '654321' , Team_Leader__c = u.Id,
											 Launch_Date__c = System.today(), Site_Address_City__c='Bangalore',Technical_Head__c = u.Id);
			projlist.add(proj);
			insert projlist;
			
			list<Visit__c> vstLst = new list<Visit__c>();
			Visit__c vs = new Visit__c(Project__c = projlist[0].Id,  Visit_Report__c = 'First Technical Report',Exception__c =true);
			vstLst.add(vs);
			insert vstLst;
			
			list<Query__c> qry = new list<Query__c>();
			Query__c qrExc = new Query__c(Exception_Status__c = 'Open',Expected_Closure_Date__c = system.today()+1,Visit__c = vstLst[0].Id);
			Query__c qrExc1 = new Query__c(Exception_Status__c = 'Open',Expected_Closure_Date__c = system.today()+1, Visit__c = vstLst[0].Id);
			qry.add(qrExc);
			qry.add(qrExc1);
			insert qry;
			
			System.runAs(u){
				//Start Test Class
				Test.StartTest();
				RBI_ExceptionAlertBatch batch =  new RBI_ExceptionAlertBatch();
				batch.QueryString = 'select Name,Expected_Closure_Date__c,Query_Resolved_Date__c,Visit__c,Visit__r.Name,Visit__r.Project__r.Name,Technical_Head_EmailId__c,PAS_Manager_Email__c,Team_Leader_Email__c, Closure_Remarks__c,Expected_Closure_Email_Date__c, Query_Description__c, Query_Initiated_Date__c,Exception_Status__c, Other_Remarks__c,Customer_Project__c,Customer_Project__r.Project_Name__c,Customer_Project__r.Name,Visit__r.Project__r.Project_Name__c from Query__c  where Exception_Status__c != \'Closed\' and Expected_Closure_Email_Date__c = : todayDate order by Visit__c' ; 
				batch.start(null);
				Database.executeBatch(batch);
			    batch.finish(null);
			    RBI_ExceptionAlertScheduler sco = new RBI_ExceptionAlertScheduler();
            	String sch = '0 0 23 * * ?';
            	system.schedule('visit Creates', sch, sco);
			    
		      //stop test class
		    	test.stopTest();
			}
      	}		
    }
}