Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <formula>TEXT(Project_Id__r.Site_Address_City__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address City</label>
        <type>Text</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Developer_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Developer Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <formula>Developer_Id__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Received_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures who received Document.</description>
        <label>Document Received by</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Received_date__c</fullName>
        <description>Capture Document Received date for the project.</description>
        <label>Document Received date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RBI_Created_By_Batch_Job__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RBI Created By Batch Job</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Surveyor from User Object.</description>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used when (TSR or DVU)visit record is created.</description>
        <label>Team Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Head</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TechnicalHead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Be_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is flag which will determine whether a project needs to be displayed to the Customer or not. If it is Y,, then it will not be displayed to any Customer.</description>
        <label>To Be Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <formula>LOWER( Project_Name__c &amp; TEXT( Site_Address_City__c )  &amp;  Developer_Id__r.Name )</formula>
        <label>Unique Key</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Covering_Cities__c</fullName>
        <label>Covering Cities</label>
        <picklist>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rsamos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secunderabad</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <formula>Project__r.Developer_Name__c</formula>
        <label>Developer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Received_Date__c</fullName>
        <description>Document Received date is formula field to project Document Received date</description>
        <formula>Project__r.Document_Received_date__c</formula>
        <label>Document Received Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Please enter a value before submitting for approval.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Leader__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Visits1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture operation manager. This field is used when the owner is changed in the visit. The value will be same as in the project object</description>
        <label>Operation Mgr Data</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <description>Used for (Visit)duplicate check in trigger.</description>
        <formula>LOWER(  Project_Auto_Num__c  &amp;  TEXT(Visit_Report__c ))</formula>
        <label>Unique Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Used for Project level visits</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ProjectTriggerHandler.cls
public without sharing class RBI_ProjectTriggerHandler {
    /* This is handler class for RBI_ProjectTrigger */
    public static boolean firstRun = true;
    public  list<User> userListEmail;
    Static list<Visit__c> VisitList = new list<Visit__c>(); 
    Static Id ProjRecTypeId = [select Id,name from RecordType where name='Project' and SObjectType='Visit__c' limit 1].Id;
    
    public void OnBeforeInsert(list<Project__c> project){
        //function call to check duplicate project records
        hasDuplicates(project);
        map<String, User> userlst = new map<String, User>();
        set<String> siteCity = new set<String>();
        String siteCityString = '';
        for(Project__c proj : project){
        	//Added for Phase2B on 16/8/2013
        	if((proj.Document_Received_date__c!=null) && (proj.Document_Received_by__c==null)){
        		proj.Document_Received_by__c = UserInfo.getUserId();
        	}
        	// End of Phase2B on 16/8/2013
            if(proj.Site_Address_City__c != null && (siteCity.add(proj.Site_Address_City__c)))
                //siteCity.add(proj.Site_Address_City__c); 
                siteCityString += '\''+proj.Site_Address_City__c+'\',';
        }
        if(siteCityString != null && siteCityString != '')
        	siteCityString = siteCityString.substring(0, siteCityString.length()-1); 
        system.debug('xxxxxxxxxxx'+siteCityString);
        userlst = queryUser(siteCityString);
        for(Project__c proj : project){
        	boolean userFlag = false;
            String surveyorKey = proj.Site_Address_City__c+'-Surveyor';
            //String pasManagerKey = proj.Site_Address_City__c+'-PAS Manager';
            String TechnicalHeadKey = proj.Site_Address_City__c+'-Technical Head';// Created for 2nd Phase 31.07.2013
            String zonalHeadKey = proj.Site_Address_City__c+'-Zonal Head';// Created for 2nd Phase 05.08.2013
            if(proj.Site_Address_City__c != null){
	            if(userlst.containsKey(surveyorKey) && userlst.get(surveyorKey).UserRole.Name == 'Surveyor'){
                	proj.Surveyor__c = userlst.get(surveyorKey).Id;
                }else{
                  	proj.Surveyor__c = system.Label.RBI_DefaultPASMgrId; 
                } 
                /*if(userlst.containsKey(pasManagerKey) && userlst.get(pasManagerKey).UserRole.Name == 'PAS Manager'){
                	proj.Team_Leader__c = proj.OwnerId;
                }
                else{
                 	proj.Team_Leader__c = system.Label.RBI_DefaultPASMgrId;
                }*/
                //Added for 2nd Phase 05.08.2013 
                system.debug('44444'+userlst);
                if(((proj.To_Be_Approved__c == true) || (proj.RBI_Created_By_Batch_Job__c == true)) && userlst.containsKey(zonalHeadKey) && userlst.get(zonalHeadKey).UserRole.Name == 'Zonal Head'){
                	proj.Team_Leader__c = userlst.get(zonalHeadKey).Id;
                	system.debug('5555555'+userlst.get(zonalHeadKey)+'      '+proj.Team_Leader__c);
                }
                else if((proj.To_Be_Approved__c == false) && (proj.RBI_Created_By_Batch_Job__c == false)){
                	proj.Team_Leader__c = proj.OwnerId;
                }
                else{
                 	proj.Team_Leader__c = system.Label.RBI_DefaultPASMgrId;
                }
                //ends
                //Added for 2nd Phase 31.07.2013 
                if(userlst.containsKey(TechnicalHeadKey) && userlst.get(TechnicalHeadKey).UserRole.Name == 'Technical Head'){
                	proj.Technical_Head__c = userlst.get(TechnicalHeadKey).Id;
                }
                else{
                 	proj.Technical_Head__c = system.Label.RBI_DefaultPASMgrId;
                }
                //Adding ended
            }
        }
    }
    
    public void OnBeforeUpdate(list<Project__c> projectNew, list<Project__c> projectOld, Map<Id, Project__c> ObjectMap){
        map<String, User> userlst = new map<String, User>();
        set<String> siteCity = new set<String>();
        String siteCityString = '';
        list<Project__c> projectListforUpdate = new list<Project__c>();
        boolean updateflag = false;
        for(Project__c projNew : projectNew){
        	//Added for Phase2B on 16/8/2013
        	if((projNew.Id == ObjectMap.get(projNew.Id).Id)&&(ObjectMap.get(projNew.Id).Document_Received_date__c == null)&&(projNew.Document_Received_date__c!=null) && (projNew.Document_Received_by__c==null)){
        		projNew.Document_Received_by__c = UserInfo.getUserId();
        	}
        	//End of Phase2B on 16/8/2013
            if(projNew.Id == ObjectMap.get(projNew.Id).Id && ObjectMap.get(projNew.Id).Site_Address_City__c != projNew.Site_Address_City__c){
                projectListforUpdate.add(projNew);
                if(projNew.Site_Address_City__c != null && (siteCity.add(projNew.Site_Address_City__c)))
                    siteCityString += '\''+projNew.Site_Address_City__c+'\',';
                updateflag = true;
            }
            else if(projNew.Id == ObjectMap.get(projNew.Id).Id && ObjectMap.get(projNew.Id).Project_Name__c != projNew.Project_Name__c){
                projectListforUpdate.add(projNew);
                updateflag = true;
            } 
            else if(projNew.Id == ObjectMap.get(projNew.Id).Id && ObjectMap.get(projNew.Id).Developer_Id__c != projNew.Developer_Id__c){
                projectListforUpdate.add(projNew);
                updateflag = true;
            }                                
        }
        if(updateflag){
	        //function call to check duplicate project records
	        if(projectListforUpdate!=null && projectListforUpdate.size()>0){
	            hasDuplicates(projectListforUpdate);
	        }
	        if(siteCityString != null && siteCityString != '')
	        	siteCityString = siteCityString.substring(0, siteCityString.length()-1); 
	        userlst = queryUser(siteCityString);
	        
	        for(Project__c proj : projectNew){
	            boolean userFlag = false;
	            boolean modifyFlag1 = false;
	            boolean modifyFlag2 = false;
	            String surveyorKey = proj.Site_Address_City__c+'-Surveyor';
	            //String pasManagerKey = proj.Site_Address_City__c+'-PAS Manager';
	            String TechnicalHeadKey = proj.Site_Address_City__c+'-Technical Head';// Created for 2nd Phase 31.07.2013
	            if(proj.Site_Address_City__c != null && ObjectMap.get(proj.Id).Site_Address_City__c != proj.Site_Address_City__c){
					//if(userlst.containsKey(surveyorKey) && userlst.get(surveyorKey).UserRole != null && proj.Site_Address_City__c == userlst.get(surveyorKey).City && userlst.get(surveyorKey).UserRole.Name == 'Surveyor'){
					if(userlst.containsKey(surveyorKey) && userlst.get(surveyorKey).UserRole != null && userlst.get(surveyorKey).UserRole.Name == 'Surveyor'){
			            proj.Surveyor__c = userlst.get(surveyorKey).Id;
		                system.debug('11111'+proj.Surveyor__c);
		            }
		            else{
		               	proj.Surveyor__c = system.Label.RBI_DefaultPASMgrId;
		            }
		            /*
		            if(userlst.containsKey(pasManagerKey) && userlst.get(pasManagerKey).UserRole != null && proj.Site_Address_City__c == userlst.get(pasManagerKey).City && userlst.get(pasManagerKey).UserRole.Name == 'PAS Manager'){
	    	            proj.Team_Leader__c = proj.OwnerId;
	                    system.debug('1111122'+proj.Team_Leader__c);
	                }
	                else{
	                   	proj.Team_Leader__c = system.Label.RBI_DefaultPASMgrId; 
	                }
	                */
	                // Added for 2nd Phase 31.07.2013
		            if(userlst.containsKey(TechnicalHeadKey) && userlst.get(TechnicalHeadKey).UserRole != null && userlst.get(TechnicalHeadKey).UserRole.Name == 'Technical Head'){
	    	            proj.Technical_Head__c = userlst.get(TechnicalHeadKey).Id;
	                }
	                else{
	                   	proj.Technical_Head__c = system.Label.RBI_DefaultPASMgrId; 
	                }
	                //Adding end
	            }
	        }
        }
    }
    
    /* This method is used from beforeInsert and beforeUpdate */
    
    public map<String, User> queryUser(String siteCity){
        //list<User> userList = [select name, UserRole.Name, Covering_Cities__c, City from User where City IN : siteCity];
        list<User> userList = new list<User>();
        system.debug('qqqqqqqqqq'+siteCity);
        //if((siteCity != null && siteCity != '') || (devCity != null && devCity != '')){
        if(siteCity != null && siteCity != ''){	
        	String userQuery = 'select name, UserRole.Name, Covering_Cities__c, City from User';
			//userQuery += ' where (City IN ('+siteCity+') OR Covering_Cities__c INCLUDES (' + siteCity + ')) and UserRole.Name = \'Surveyor\'';
			//userQuery += ' where (Covering_Cities__c INCLUDES (' + siteCity + ')) and UserRole.Name = \'Surveyor\'';Zonal Head
			//Added for 2nd Phase 31.07.2013
			userQuery += ' where (Covering_Cities__c INCLUDES (' + siteCity + ')) and (UserRole.Name = \'Surveyor\' OR UserRole.Name = \'Technical Head\' OR UserRole.Name = \'Zonal Head\' OR UserRole.Name = \'Operation Mgr - Data\')';
			//Adding ended
			system.debug('++++++++'+userQuery);
			userList = database.query(userQuery);
        }
        system.debug('yyyyyyyyyyy'+userList);
        map<String, User> userMap = new map<String, User>();
        for(User us : userList){
        	if(us.Covering_Cities__c != null){
        		list<String> cityList = us.Covering_Cities__c.split(';');
		        for(String strCity : cityList){
		           	userMap.put(strCity+'-'+us.UserRole.Name, us);
		        }
        	}
        } 
        system.debug('asdf'+userMap);
        return userMap;
    }
    /* This method is used from afterinsert to create project bucket on project creation*/
    /* Creating FTR Visit record when a project is created with the launch date before today */
        
        @future (callout=true)
        public static void OnAfterInsert(list<String> projectName, list<Id> projId, list<boolean> createFTR, list<Id> surveyorId){
            /*if (!Test.isRunningTest()) 
            {
                string bucketname = projectName;
                AWS_S3_ExampleController awscls;
                awscls =  new AWS_S3_ExampleController();
                if((bucketname != null) && (bucketname != '')){
                    awscls.createS3Bucket(bucketname);
                }
            }*/
            for(integer i = 0; i < projectName.size(); i++){
                if(createFTR[i]){
                    Visit__c visit = new Visit__c();
                    visit.RecordTypeId = ProjRecTypeId;
                    visit.Project__c = projId[i];
                    visit.Visit_Report__c = 'First Technical Report';
                    if(surveyorId[i] != null){
                        visit.Surveyor__c = surveyorId[i];
                        visit.OwnerId = surveyorId[i];
                    }
                    visit.Start_Date__c = system.today();    
                    VisitList.add(visit);
                }
            }
            
            try{
                insert VisitList;
            }catch(DMLException e){
                system.debug(e);
            }
         }

// This method acts as a uniqueness checker for the Project
    private  void hasDuplicates(Project__c[] projects){
        //Define a map for unique Projects
        Map <String,Project__c> projMap = new Map<String, Project__c> ();
        for (Project__c projinst: projects) {
            String Name     = (projinst.Project_Name__c==null)?'':projinst.Project_Name__c.toLowerCase();
            String city     = (projinst.Site_Address_City__c==null)?'':projinst.Site_Address_City__c.toLowerCase();
            String devname  = (projinst.Developer_Name__c==null)?'':projinst.Developer_Name__c.toLowerCase();
            String ukey = Name + city+devname;
            if (projMap.containsKey(ukey)) {
                projinst.addError('Project with this Name already exists in the system!');
            }
            else
                projMap.put(ukey,projinst);
        }

        //Check DB for dupes
        if (!projMap.isEmpty()){
            for(Project__c[] ProjCheck:[select Id, Unique_Key__c from Project__c where Unique_Key__c IN :projMap.keySet()]) {
                for(Project__c projr:ProjCheck) {
                    String currentProjectId = projr.Id;
                    if(projMap.containsKey(projr.Unique_Key__c) && (currentProjectId != projMap.get(projr.Unique_Key__c).Id)) {
                        //projMap.get(projr.Unique_Key__c).addError('Duplicate Project Name, City and Developer Name found in salesforce(id: ' + projr.id + ')');
                        projMap.get(projr.Unique_Key__c).addError('Project Name already exists for the selected City / Developer!');
                    }
                }
            }
        }
    }
    
    /* If an Project status is changed to PMR then this method will send Email to corresponding customer  */
    public void OnAfterUpdate(list<Project__c> projectNew, list<Project__c> projectOld, Map<Id, Project__c> ObjectMap){
        if (firstRun){
        	List<Messaging.SingleEmailMessage> emails;
            list<Customer_Projects__c> custProject = new list<Customer_Projects__c>();
            set<Id> projSetId = new set<Id>();
            set<Id> custProjSetId = new set<Id>();
            list<Contact> con = new list<Contact>();
            map<Id, wrapEmailProject> projWrap = new map<Id, wrapEmailProject>();
            map<Id, Project__c> projectMap = new map<Id, Project__c>();
            boolean PMRChangeFlag = false;
            //firstRun = false;
            system.debug('9999999'+projectNew[0].Status__c);
            for(Project__c projNew : projectNew){
                if(projNew.Id == ObjectMap.get(projNew.Id).Id && ObjectMap.get(projNew.Id).Status__c != projNew.Status__c && projNew.Status__c == 'PMR'){
                    projSetId.add(projNew.Id);
                    projectMap.put(projNew.Id, projNew);
                    PMRChangeFlag = true;
                    firstRun = false;
                }
            }
            if(PMRChangeFlag){
            	emails = new List<Messaging.SingleEmailMessage>();
                PMRChangeFlag = false;
                if(projSetId != null)
                    custProject = [select AccountId__c, Project_Id__c, Project_Id__r.Name, Project_Id__r.Project_Name__c, Project_Name__c from Customer_Projects__c where Project_Id__c IN : projSetId];
                for(Customer_Projects__c cusProj : custProject){
                    if(projectMap.containsKey(cusProj.Project_Id__c)){
                        //projWrap.put(cusProj.Id, new wrapEmailProject(cusProj));
                        custProjSetId.add(cusProj.AccountId__c);
                    }
                }   
                if(custProjSetId != null && custProjSetId.size() > 0)
                    con = [select name, Email, AccountId, Group_Email__c from Contact where AccountId IN : custProjSetId and Primary__c = true];
                for(Customer_Projects__c cusProj : custProject){ 
                    for(Contact c : con){ // Inner for loop
                        if(c.AccountId == cusProj.AccountId__c){
                        	String[] toAddresses;
                            Customer_Projects__c custProjRec = new Customer_Projects__c();
                            //custProjRec = projWrap.get(cusProj.Id).custProjrecord;
                            //projWrap.put(cusProj.Id, new wrapEmailProject(custProjRec, cusProj.Customer_User_Email__c));
                            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                            if(c.Group_Email__c != null){
                            	toAddresses = c.Group_Email__c.split(',');
                            	mail.setToAddresses(toAddresses);
                            }
                            mail.setTemplateId(System.label.RBI_TemplateIdForPRMStatusChange);
                            mail.setTargetObjectId(c.Id);
                            mail.setWhatId(cusProj.Project_Id__c);
                            //mail.saveAsActivity = false;
                            system.debug('/////////'+toAddresses+ '1110 '+mail );
                            //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                            emails.add(mail);
                        }
                    }// end of inner for loop   
                }   
                if(emails != null && emails.size() > 0)
                	Messaging.sendEmail(emails);
            }
        }
    }
    public class wrapEmailProject{
        public Customer_Projects__c custProjrecord;
        public String emailId;
        public wrapEmailProject(Customer_Projects__c custproj){
            custProjrecord = custproj;
        }
        public wrapEmailProject(Customer_Projects__c custproj, String conEmail){
            custProjrecord = custproj;
            emailId = conEmail;
        }
    }
}