Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>PAS_Manager_Email__c</fullName>
        <description>This field is updated when the PAS Manager is changed</description>
        <label>PAS Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Query__c.object
<CustomObject>
    <description>Stores the Document Queries</description>
    <fields>
        <fullName>Closure_Remarks__c</fullName>
        <description>Used to hold  Closure Remarks for Exception.</description>
        <label>Closure Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores Relationship between Queries/Exception and Customer_Project</description>
        <label>Customer Project</label>
        <referenceTo>Customer_Projects__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exception_Status__c</fullName>
        <description>Used to hold status of exception as closed or open</description>
        <label>Exception Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_Closure_Date__c</fullName>
        <description>Used as  Expected Closure Date for Exception</description>
        <label>Expected Closure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expected_Closure_Email_Date__c</fullName>
        <description>Used to give one day before date of expected closure date(Used in ExceptionAlertBatch class).</description>
        <formula>Expected_Closure_Date__c - 1</formula>
        <label>Expected Closure Email Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Other_Remarks__c</fullName>
        <description>Used as  Other_Remarks in exception</description>
        <label>Other Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PAS_Manager_Email__c</fullName>
        <label>PAS Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>IF( ISBLANK(Visit__c),  Customer_Project__r.Project_Id__r.Project_Name__c, Visit__r.Project__r.Project_Name__c)</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_Description__c</fullName>
        <description>used as Description field for both query and Exception.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Query_Initiated_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Used as  Initiation Date for both Query and Exception.</description>
        <label>Initiation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Query_Resolved_Date__c</fullName>
        <description>Used as Close Date for both Query and Exception.</description>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Team_Leader_Email__c</fullName>
        <description>Used   Visit TeamLeader email through CrossObject Formula field in Query\Exception</description>
        <formula>IF( ISBLANK(Visit__c),  Customer_Project__r.Project_Id__r.Team_Lead_Email__c ,  Visit__r.Project__r.Team_Lead_Email__c )</formula>
        <label>Team Leader Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Head_EmailId__c</fullName>
        <description>Use to get the email id of the technical head of the project.</description>
        <formula>IF( ISBLANK(Visit__c),  Customer_Project__r.Project_Id__r.Technical_Head__r.Email , Visit__r.Project__r.Technical_Head__r.Email)</formula>
        <label>Technical Head EmailId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship  between  Visit and  Queries/Exception</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Query/Exception</label>
    <nameField>
        <displayFormat>Qr-{0000}</displayFormat>
        <label>Query Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries/Exceptions</pluralLabel>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <description>Record type for  Query/Execption object Named as Exception</description>
        <label>Exception</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Used for Project level visits</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ExceptionAlertBatch.cls
global class RBI_ExceptionAlertBatch implements  Database.Batchable<sObject>{
	
	global String QueryString; 
	global Date todayDate;
	list<Query__c> exceptionList;
	
	global RBI_ExceptionAlertBatch(){
		todayDate = system.today();
		QueryString = 'select Name,Expected_Closure_Date__c,Query_Resolved_Date__c,Visit__c,Visit__r.Name,Visit__r.Project__r.Name,Technical_Head_EmailId__c,PAS_Manager_Email__c,Team_Leader_Email__c, Closure_Remarks__c,Expected_Closure_Email_Date__c, Query_Description__c, Query_Initiated_Date__c,Exception_Status__c, Other_Remarks__c,Customer_Project__c,Customer_Project__r.Project_Name__c,Customer_Project__r.Name,Visit__r.Project__r.Project_Name__c from Query__c  where Exception_Status__c != \'Closed\' and Expected_Closure_Email_Date__c = : todayDate order by Visit__c' ;
		exceptionList = new list<Query__c>();
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC){  
		return Database.getQueryLocator(QueryString);
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){
		String PASTechEmailId;
		exceptionList = scope;
		system.debug('xxxxxxxxxx'+exceptionList);
		map<String, list<Query__c>> exceptionMap = new map<String, list<Query__c>>() ;
		list<Query__c> excepValue;
		list<Query__c> excepListinMap;
		for(Query__c excep : exceptionList){
			excepValue = new list<Query__c> ();
			PASTechEmailId = '';
			excepListinMap = new list<Query__c> ();
			if((excep.Team_Leader_Email__c != null && excep.Team_Leader_Email__c != '') && (excep.Technical_Head_EmailId__c != null && excep.Technical_Head_EmailId__c != '')){
				PASTechEmailId = excep.Team_Leader_Email__c+','+excep.Technical_Head_EmailId__c;
				system.debug('yyyyyyyyyyyyyy'+PASTechEmailId);
				if(exceptionMap != null && exceptionMap .size() > 0 && exceptionMap .containsKey(PASTechEmailId)){
					excepListinMap = exceptionMap.get(PASTechEmailId);
					system.debug('33333 ' + excepListinMap);
				}
				if(excepListinMap != null && excepListinMap.size() > 0){
					excepValue.addAll(excepListinMap);
		 		}
				excepValue.add(excep);
				exceptionMap .put(PASTechEmailId, excepValue);
				system.debug('111111111111'+exceptionMap);
				system.debug('2222222 ' + exceptionMap.get(PASTechEmailId));
			}
		}
 		if(exceptionMap != null && exceptionMap.size() > 0){
 			EmailSurveyor(exceptionMap);
 		}
	}	
	public void EmailSurveyor(map<String, list<Query__c>> excepMap){
        system.debug('212121'+excepMap);
        for(String PASTechEmail : excepMap.keySet()){
        	list<Query__c> exceptionRec = excepMap.get(PASTechEmail);
    		String body = '' ;  
            //Creating tabular format for the exception details  
            body = BodyFormat(exceptionRec) ;  
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage() ; 
            String[] toAddresses = PASTechEmail.split(',');
            //String[] toAddresses = new String[] {PASTechEmail} ;  
            mail.setToAddresses(toAddresses) ; 
            mail.setSubject('Exception records which are expected to close tomorrow');
            //Body of email 
            mail.setHtmlBody('Hello, <br /><br />Please find below the details of Exceptions that are expected to close tommorow. <br /><br />' + body + '<br /> <br />Thanks & Regards, <br /> RealtyBI Team');  
            //Sending the email 
            if (!Test.isRunningTest()) { 
            	Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            	system.debug('mail Sent' + mail);
           	}
        }
    }
    
    public String BodyFormat(List<Query__c> lst){  
       	String str = '' ;  
       	
    	for(Query__c qry : lst){  
			Date myDate = date.newinstance(qry.Expected_Closure_Date__c.year(), qry.Expected_Closure_Date__c.month(), qry.Expected_Closure_Date__c.day());
            String d = String.valueOf(myDate);
            if(qry.Visit__c != null)
        		str += '<tr><td>'+ qry.Name +'</td>'+'<td>'+ qry.Query_Description__c +'</td>'+'<td>'+ d +'</td>'+'<td>'+ qry.Visit__r.Name +'</td>'+'<td>'+ qry.Visit__r.Project__r.Project_Name__c +'</td>'+'</tr>' ;  
            else
                str += '<tr><td>'+ qry.Name +'</td>'+'<td>'+ qry.Query_Description__c +'</td>'+'<td>'+ d +'</td>'+'<td>'+ qry.Customer_Project__r.Name +'</td>'+'<td>'+ qry.Customer_Project__r.Project_Name__c +'</td>'+'</tr>' ;  
        }  
        str = str.replace('null' , '') ;  
        String finalStr = '' ;  
        finalStr = '<table border="1"> <td><b> Exception Id </b> </td> <td><b> Description </b> </td> <td><b> Exception Closure Date </b></td> <td><b> Related To </b></td> <td><b> Project Name </b></td> '+ str +'</table>' ;    
        return finalStr ;  
   	}  
	
	global void finish(Database.BatchableContext BC){

	}

}