Dev-RBI/src/objects/Customer_Projects__c.object
<CustomObject>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Customer</relationshipLabel>
        <relationshipName>Customer_Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Project</label>
    <nameField>
        <displayFormat>CUSPROJ-{0000000000}</displayFormat>
        <label>Customer Projects Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Project_Id__c</fullName>
        <formula>Unit__r.Tower_Id__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Cust_Packages__c.object
<CustomObject>
    <fields>
        <fullName>Customer_Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship of Customer project</description>
        <label>Customer Project</label>
        <referenceTo>Customer_Projects__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>List_Pricing__c</fullName>
        <description>This field is used to store list price for the service.</description>
        <label>List Pricing</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>List_of_Values__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores reference of master data for List of Values object</description>
        <label>Package Name</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Customer Package</relationshipLabel>
        <relationshipName>Customer_Package</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <description>This field is used in Trigger.</description>
        <formula>Customer_Project__r.Project_Id__c &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 5, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 4, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 3, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 2, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 1, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 10, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 9, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 8, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 7, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 6, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1) &amp; 
MID( 
&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;, 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 15, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 16 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 14, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 8 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 13, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 4 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 12, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 2 + 
MIN(FIND(MID(Customer_Project__r.Project_Id__c, 11, 1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;), 1) * 1 + 1, 
1)</formula>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <label>Customer Package</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Package Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Package</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_CustPackageListClass.cls
/*
    Type:       Custom Controller
    Purpose:    Used to display the Packages/Services associated with the Customer, in Employee application          

    Used By:   RBI_CustPackageListPage.page
    ---------------------------------------------------------------
    History:

    18-Apr-2013          Created		Tugboat Info Solutions Pvt.Ltd

*/
public with sharing class RBI_CustPackageListClass {
	public list<Project_Cust_Packages__c> liParents{get; set;}
    public string projectId ='';
    public RBI_CustPackageListClass(ApexPages.standardController std){
        projectId=Apexpages.currentPage().getParameters().get('id');
        liParents = [select Customer_Project__r.Project_Id__r.Id,List_of_Values__c,List_Pricing__c
                             from Project_Cust_Packages__c where Customer_Project__r.Project_Id__r.Id=:projectId];
       }

}