Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Document_Description__c</fullName>
        <label>Document Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Document_Status__c.object
<CustomObject>
    <fields>
        <fullName>Document_Description__c</fullName>
        <formula>Project_Document__r.Document_Description__c</formula>
        <label>Document Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>Project_Document__r.Document_Type__c</formula>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>List of Values</description>
        <label>Project Document</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Project Documents</relationshipLabel>
        <relationshipName>Project_Document_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store relationship with Visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipName>Project_Document_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Document</label>
    <nameField>
        <displayFormat>DOC-{0000000000}</displayFormat>
        <label>Document Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Query__c.object
<CustomObject>
    <description>Stores the Document Queries</description>
    <fields>
        <fullName>Project_Document_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship between Project Document Status</description>
        <label>Project Document</label>
        <referenceTo>Project_Document_Status__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Query_Description__c</fullName>
        <description>used as Description field for both query and Exception.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Query_Initiated_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Used as  Initiation Date for both Query and Exception.</description>
        <label>Initiation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Query_Resolved_Date__c</fullName>
        <description>Used as Close Date for both Query and Exception.</description>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship  between  Visit and  Queries/Exception</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Query/Exception</label>
    <nameField>
        <displayFormat>Qr-{0000}</displayFormat>
        <label>Query Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries/Exceptions</pluralLabel>
    <recordTypes>
        <fullName>Exception</fullName>
        <active>true</active>
        <description>Record type for  Query/Execption object Named as Exception</description>
        <label>Exception</label>
    </recordTypes>
    <recordTypes>
        <fullName>Query</fullName>
        <active>true</active>
        <description>Record type for  Query/Execption object</description>
        <label>Query</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_DocQryDetails.cls
/*
    Type:       Custom Controller
    Purpose:    Used by the Customer in Customer Portal to see the Documents for TSR and DVU Visits records. Also, Customer can see
                the query details for each document. This can be accessed in Customer Portal under My Projects tab - Status subtab and 
                clicking on Visit Name.      

    Used By:   RBI_VisitDetails.page
    ----------------------------------------------------------------------------------
    History:

    25-Apr-2013     Modified        Tugboat Info Solutions Pvt. Ltd

*/
public class RBI_DocQryDetails {
    
    public  list<Query__c>      queryList    {get; set;}
    public  list<Project_Document_Status__c> allQryList {get; set;}
    public Id docId     {get; set;}
    public Visit__c vis{get; set;}
    public boolean disQry {get;set;}
    public ApexPages.StandardController sController;
    public boolean docRecFlag {get;set;} // Determines the field display in Document Section
    
    public RBI_DocQryDetails(ApexPages.StandardController stdCon)
    {
        try{  
            sController = stdCon;
            disQry = false;
            this.vis=(Visit__c)stdCon.getRecord();
            list<Query__c>   queryList = new list<Query__c>();
            if(vis.Visit_Report__c == 'TSR Report' || vis.Visit_Report__c == 'DVU Report')
                docRecFlag = true;
            else
                docRecFlag = false; 
            allQryList = new list<Project_Document_Status__c>();
            allQryList = vis.Project_Document_Status__r;
            if (allQryList != null && allQryList.size() > 0){ 
                docId =  allQryList[0].Id;
                queryList = getqueryList(docId);
            }
        }
        catch(System.Exception e){
            //DO Nothing                  
            
        } 
        
    }
    
    public PageReference selectRow() {
        
        queryList = getqueryList(docId);
        return null;
    }
    
    public Query__c[] getqueryList(String qId){
        
        queryList = new list<Query__c>();
        
        //Runquery to fetch Query records related to a Document
        if (docId!=null){
            queryList   =   [SELECT Id, Query_Initiated_Date__c, Query_Description__c, Query_Resolved_Date__c, Project_Document_Status__c, Project_Document_Status__r.Project_Document__r.Name, Project_Document_Status__r.Project_Document__r.Document_Description__c, Project_Document_Status__r.Project_Document__r.Document_Type__c FROM Query__c Where Project_Document_Status__c=:docId];
        
            if(queryList == null){
                disQry = false;
                return null;
                //ADD IN DEBUG LOG
            }
            else{
                disQry = true;
                return queryList;
                }
        }
        return null;
    }
}