Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Id_Const_Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Project Id for the Construction Loan taken by Developer</description>
        <label>Construction Loan for Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Construction Loan Details</relationshipLabel>
        <relationshipName>ConstructionLoan</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ConstructionLoanDetails.cls
/*
    Type:       Custom Controller
    Purpose:    Used to add Construction loan details for a Project.        

    Used By:   RBI_ConstructionLoanDetails.page
    ---------------------------------------------------------------
    History:

    07-May-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_ConstructionLoanDetails {
	public Account selectedAccount { get; set; }
	public Account[] lstAccount;
    public List_of_Values__c LOV {get;set;}
    public String ProjectId;
    public String LOVId;
   	public ApexPages.StandardController std;
    
    //Constructor
   	public RBI_ConstructionLoanDetails(ApexPages.StandardController stdcontroller) {
     	this.std = stdcontroller;
        this.LOV=(List_of_Values__c)stdcontroller.getRecord();
        ProjectId = System.currentPagereference().getParameters().get('ProjId');
        LOV.Project_Id_Const_Loan__c = ProjectId;
        LOV.Name = 'Construction Loan Details';
        LOV.Entity_Type__c = 'Construction Loan Details';
    }
    
    public pageReference Save(){
    	insert LOV;
    	PageReference Pg = new PageReference('/' + ProjectId);
		return Pg;
    }
    
    public PageReference doCancel(){
		PageReference Pg = new PageReference('/' + ProjectId);
		return Pg;
    }
    public PageReference SaveandNew(){
    	insert LOV;
    	LOV = new List_of_Values__c(Project_Id_Const_Loan__c = ProjectId, Name = 'Construction Loan Details', Entity_Type__c = 'Construction Loan Details');
    	PageReference newPage = New PageReference('/apex/RBI_ConstructionLoanDetails?ProjId='+ProjectId);
    	newPage.setRedirect(true);
    	return newPage;
    }
}