Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Store plan type for List of value object</description>
        <label>Plan Type</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship with project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <displayFormat>PPId- {0000000000}</displayFormat>
        <label>Payment Plan Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_AddPaymentPlan.cls
/*
    Type:       Custom Controller
    Purpose:    Used to add Payment Plan for a Project in Employee Portal.         

    Used By:   RBI_AddPaymentPlan.page
    ---------------------------------------------------------------
    History:

    03-May-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_AddPaymentPlan {
	public list<servicewrapper> WrapperListofval {get; set;} 
    public Payment_Plan__c recPayPlan;
    public List_of_Values__c reclistofval;
    public list<Payment_Plan__c> PayPlanlist;
    public string ProjectId;
    public string ProjectName {get;set;}
    
    public RBI_AddPaymentPlan(){
    	ProjectId = System.currentPagereference().getParameters().get('ProjId');
    	ProjectName = System.currentPagereference().getParameters().get('ProjName');
    	WrapperListofval = new list<servicewrapper>();
    	
    }
    
    public list<servicewrapper> getListofValues(){
    	WrapperListofval = new list<servicewrapper>();
        	for(List_of_Values__c reclistofval:[Select Id, Name, Entity_Name__c, Entity_Type__c, Key__c, Value__c From List_of_Values__c where Entity_Name__c = 'Payment Plan']){
            	WrapperListofval.add(new servicewrapper(reclistofval));
      
            }
      
        return WrapperListofval;
    }
    
    public PageReference dosave(){
       
        PayPlanlist = new list<Payment_Plan__c>();	  
        for(servicewrapper servwrapper: WrapperListofval) {
            if(servwrapper.selected == true) {
            
				PayPlanlist.add(new Payment_Plan__c(Project__c=ProjectId, Plan_Type__c=servwrapper.listofval.Id));                      
            }
        }
        try{
	       	if (PayPlanlist !=null){
	        	Database.Insert(PayPlanlist);
	        	PageReference Pg = new PageReference('/' + ProjectId);
	    		return Pg;
	        }
        }catch(DMLException ex){
        	ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, 'Payment Plan already exists!');
        	ApexPages.addMessage(errorMessage);
        	return null;
        }      
        return null;
    }
    
    public PageReference doCancel(){
		PageReference Pg = new PageReference('/' + ProjectId);
		return Pg;
    }
    
    public class servicewrapper{
        public List_of_Values__c listofval {get; set;} 
        public Boolean selected {get; set;}
        
        public servicewrapper(List_of_Values__c lov){
            listofval = lov;
            selected= false;
        }
    }
}