Dev-RBI/src/objects/List_of_Values__c.object
<CustomObject>
    <fields>
        <fullName>Document_Description__c</fullName>
        <label>Document Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>List of Values</label>
    <nameField>
        <label>List of Values Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List of Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Document_Status__c.object
<CustomObject>
    <fields>
        <fullName>Document_Description__c</fullName>
        <formula>Project_Document__r.Document_Description__c</formula>
        <label>Document Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <formula>Project_Document__r.Document_Type__c</formula>
        <label>Document Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>List of Values</description>
        <label>Project Document</label>
        <referenceTo>List_of_Values__c</referenceTo>
        <relationshipLabel>Project Documents</relationshipLabel>
        <relationshipName>Project_Document_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store relationship with Visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipName>Project_Document_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Document</label>
    <nameField>
        <displayFormat>DOC-{0000000000}</displayFormat>
        <label>Document Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_AddPDRList.cls
/*
    Type:       Custom Controller
    Purpose:    Used to add PDR List for a Visit Record (TSR and DVU Visit) in Employee Portal.         

    Used By:   RBI_AddPDRList.page
    ---------------------------------------------------------------
    History:

    06-May-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_AddPDRList {
	public list<servicewrapper> WrapperListofval {get; set;} 
    public Project_Document_Status__c recprojdoc;
    public List_of_Values__c reclistofval;
    public list<Project_Document_Status__c> documentlist;
    public string ProjectId;
    public string VisitId;
    public string ProjectName {get;set;}
    
    public RBI_AddPDRList(){
    	ProjectId = System.currentPagereference().getParameters().get('ProjId');
    	VisitId = System.currentPagereference().getParameters().get('VisId');
    	WrapperListofval = new list<servicewrapper>();
    	
    }
    
    public list<servicewrapper> getListofValues(){
    	WrapperListofval = new list<servicewrapper>();
        	for(List_of_Values__c reclistofval:[Select Id, Name, Entity_Name__c, Entity_Type__c, Document_Type__c, Document_Description__c, Key__c, Value__c From List_of_Values__c where Entity_Type__c = 'Document' ORDER BY Key__c]){
            	WrapperListofval.add(new servicewrapper(reclistofval));
      
            }
      
        return WrapperListofval;
    }
    
    public PageReference dosave(){
       
        documentlist = new list<Project_Document_Status__c>();	  
        for(servicewrapper servwrapper: WrapperListofval) {
            if(servwrapper.selected == true) {
            
				documentlist.add(new Project_Document_Status__c(Visit__c=VisitId, Project_Document__c=servwrapper.listofval.Id));                      
            }
        }
       	if (documentlist !=null){
        	Database.Insert(documentlist);
        	PageReference Pg = new PageReference('/' + VisitId);
    		return Pg;
        }      
        return null;
    }
    
    public PageReference doCancel(){
		PageReference Pg = new PageReference('/' + VisitId);
		return Pg;
    }
    
    public class servicewrapper{
        public List_of_Values__c listofval {get; set;} 
        public Boolean selected {get; set;}
        
        public servicewrapper(List_of_Values__c lov){
            listofval = lov;
            selected= false;
        }
    }
}