Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Yathi-UC/src/classes/ProjectTowerExt.cls
public with sharing class ProjectTowerExt {

	public Project__c Pro;
	public Tower__c tow;

	public ProjectTowerExt(ApexPages.StandardController std){
		this.Pro=(Project__c)std.getRecord();
		
		
	}
	
	public pagereference addTower(){
		tow=new Tower__c();
		tow.Name='needs to be changed';
		tow.Project__c=Pro.Id;                  
		insert tow;	
		return null;
	}
	/* public pagereference save() //To override the save method
    {
    	
        PageReference pg = new PageReference('/apex/ProjectTowerExtension');
		    pg.getParameters().put('id', 'pro.Id');
		    update Pro;
		    return pg;
		
	} */
}