Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Basement_Floors__c</fullName>
        <label>No.of Basement Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Parking_Floors__c</fullName>
        <label>No.of Parking Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_ResCom_Floors__c</fullName>
        <label>No.of Residential / Commercial Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Avg_Resale_Price_per_Sq_Ft__c</fullName>
        <label>Avg Resale Price (per Sq Ft)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deviation__c</fullName>
        <description>Stores the deviation for a Tower</description>
        <label>Deviation</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Comment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Basement_Floors__c</fullName>
        <label>No.of Basement Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_Parking_Floors__c</fullName>
        <label>No.of Parking Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_ResCom_Floors__c</fullName>
        <label>No.of Residential / Commercial Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Structure_as_per_Plan__c</fullName>
        <label>Structure as per Plan</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit_Type__c.object
<CustomObject>
    <fields>
        <fullName>Built_up_area_Sq_Ft__c</fullName>
        <label>Built up area (Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Carpet_Area_Sq_Ft__c</fullName>
        <label>Carpet Area (Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Unit Type</relationshipLabel>
        <relationshipName>Unit_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <label>Unit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Service Appt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penthouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2BHK+ STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK+ STUDY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Unit Type</label>
    <nameField>
        <displayFormat>UNITTYP-{0000000000}</displayFormat>
        <label>Unit Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_CreateUnitTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RBI_CreateUnitTestClass {

    static testMethod void RBI_CreateUnitTest() {
     list<Project__c> projlist = new list<Project__c>();
		Project__c proj = new Project__c(Project_Name__c='Test Class', Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
										 City__c ='test', Brochure_Zipcode__c = '412578', Site_Address_zipcode__c = '123456', 
										 Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today());
		projlist.add(proj);
		insert projlist;
        list<Tower__c> towerlist = new list<Tower__c>();
		Tower__c twd = new Tower__c(Project__c = projlist[0].Id, Name = 'TowerA',Structure_as_per_Plan__c='13',
									Avg_Resale_Price_per_Sq_Ft__c=250,Deviation__c='Yes',Planned_Basement_Floors__c=2,Planned_Parking_Floors__c=2,Planned_ResCom_Floors__c=15,Actual_Basement_Floors__c=2, Actual_Parking_Floors__c=3,Actual_ResCom_Floors__c=16  );
		towerlist.add(twd);
		insert towerlist;
		list<Unit_Type__c> unittypelist = new list<Unit_Type__c>();
		Unit_Type__c unit= new Unit_Type__c(Built_up_area_Sq_Ft__c = 20, Carpet_Area_Sq_Ft__c = 15, 
											Project__c=projlist[0].Id, Unit_Type__c='1 BHK');
		unittypelist.add(unit);
		insert unittypelist;
		//start test class method
       	System.Test.startTest();
       	
       	//Instantiate the RBI_CreateUnits which generates the PDF
		PageReference CreateunitPage = Page.RBI_CreateUnits;
		System.Test.setCurrentPage(CreateunitPage);
		apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id);
		apexpages.currentpage().getparameters().put('TowId' , towerlist[0].Id);
		apexpages.currentpage().getparameters().put('TowName' , towerlist[0].Name);
	
		//Instantiate  RBI_CreateUnits class
		RBI_CreateUnits unitCreate= new RBI_CreateUnits();
		unitCreate.towerId = apexpages.currentpage().getparameters().put('TowId' , towerlist[0].Id);
		unitCreate.ProjectId = apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id); 
		unitCreate.TowerName = apexpages.currentpage().getparameters().put('TowName' , towerlist[0].Name);
		//Call RBI_CreateUnits Class Method
		unitCreate.getUnitTypeOptions();
		unitCreate.unitCount = 3;
		unitCreate.selectedUnitType = unit.Id;
		unitCreate.populateSuperArea();
		unitCreate.doCreate();
		unitCreate.doCreateandNew();
		unitCreate.doCancel();
		//stop test class Method
		System.Test.stopTest();
    }
}