Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Basement_Floors__c</fullName>
        <label>No.of Basement Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_Parking_Floors__c</fullName>
        <label>No.of Parking Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Actual_ResCom_Floors__c</fullName>
        <label>No.of Residential / Commercial Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Avg_Resale_Price_per_Sq_Ft__c</fullName>
        <label>Avg Resale Price (per Sq Ft)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deviation__c</fullName>
        <description>Stores the deviation for a Tower</description>
        <label>Deviation</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Comment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Basement_Floors__c</fullName>
        <label>No.of Basement Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_Parking_Floors__c</fullName>
        <label>No.of Parking Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_ResCom_Floors__c</fullName>
        <label>No.of Residential / Commercial Floors</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Structure_as_per_Plan__c</fullName>
        <label>Structure as per Plan</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_ProjectTowersClass.cls
/*
    Type:       Custom Controller
    Purpose:    Used by the Customer in Customer Portal to select the towers for generation of Tower Report PDF.
                Customer can select min of 1 and max of 10 towers for a project. This can be accessed in Customer Portal
                under My Projects tab - Reports subtab and clicking on Generate report link.         

    Used By:   RBI_ProjectTowers.page
    ---------------------------------------------------------------
    History:

    19-Apr-2013     Created     Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_ProjectTowersClass {
    Id[] selectedTowers= new Id[]{};
    public ApexPages.StandardController std;
    Id projectId = null;
    
    public RBI_ProjectTowersClass(ApexPages.StandardController stdcontroller){
        projectId = stdcontroller.getId();
    }
    
    public Id[] getSelectedTowers() {
        return selectedTowers;
        
    }
    
    public void setSelectedTowers(Id[] selectedTowers) {
        this.selectedTowers= selectedTowers;
    } 
    
    public List<SelectOption> gettowerRecords(){
        List<SelectOption> options = new List<SelectOption>();
        list<Tower__c> towerRecords = [select name from Tower__c where Project__c = : projectId]; 
        if (towerRecords.Size() >0){
            for(Tower__c tower:towerRecords){
                options.add(new SelectOption(tower.Id,tower.name));
            }
       } 
       return options;
    }
    /* This method will Generate TowerReport in PDF */
    public pageReference generatePDF(){
        
        if(selectedTowers != null && selectedTowers.size() > 0){
            if(selectedTowers.size() < 11){
                PageReference pg = new PageReference('/apex/RBI_GenerateTowerReportPDF?TowerList='+selectedTowers);
                return pg;
            }
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.label.RBI_TowerSelectErrMes));
        }
        if(selectedTowers.size() < 11){
            if(selectedTowers.size() > 0){
                PageReference pg = new PageReference('/apex/RBI_GenerateTowerReportPDF?TowerList='+selectedTowers);
                return pg;
            }
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, System.label.RBI_MaxTowerSelErrMes));
        }
        return null;
    }
    
    //Test method for the class above
    
     @IsTest(SeeAllData=true)  static  void Towerpage() {
        //create record for following object and make association between them
        list<Project__c> projlist = new list<Project__c>();
        Project__c proj = new Project__c(Project_Name__c='Test Class', Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
                                         City__c ='test',Brochure_Zipcode__c = '568980', Site_Address_zipcode__c = '412578', 
                                         Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today());
        projlist.add(proj);
        insert projlist;
        
        list<Tower__c> towerlist = new list<Tower__c>();
        Tower__c twd = new Tower__c(Project__c = projlist[0].Id, Name = 'TowerA',Structure_as_per_Plan__c='13',
                                    Avg_Resale_Price_per_Sq_Ft__c=250,Deviation__c='Yes',Planned_Basement_Floors__c=2,Planned_Parking_Floors__c=2,Planned_ResCom_Floors__c=15,Actual_Basement_Floors__c=2, Actual_Parking_Floors__c=3,Actual_ResCom_Floors__c=16  );
        towerlist.add(twd);
        insert towerlist;
        
        //start test class method
        PageReference towerpage = Page.RBI_ProjectTowersPage;
        
        //Instantiate the controller
        ApexPages.StandardController stdCon = new ApexPages.StandardController(proj);
        RBI_ProjectTowersClass tow= new RBI_ProjectTowersClass(stdCon);
        System.Test.startTest();
        //test the RBI_Project Tower class Method
        tow.projectId=projlist[0].Id;
        tow.gettowerRecords();
        tow.getSelectedTowers();
        tow.setSelectedTowers(tow.SelectedTowers);
        tow.generatePDF();
        
        //Stop Test Class
        System.Test.stopTest();
    
     }
}