Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Forwarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Followup</fullName>
        <active>true</active>
        <description>For Followup Visit</description>
        <label>Followup</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_AddInfraPaymentPDRFeedTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RBI_AddInfraPaymentPDRFeedTestClass {

    static testMethod void myUnitTest() {
        
        list<Project__c> projlist = new list<Project__c>();
		Project__c proj = new Project__c(Project_Name__c='Test Class', Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
										 City__c ='test', Brochure_Zipcode__c = '412578', Site_Address_zipcode__c = '123456', 
										 Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today());
		projlist.add(proj);
		insert projlist;
		
		list<Visit__c> vstList = new list<Visit__c>();
    	Visit__c vst = new Visit__c(Status__c = 'Approved', Visit_Report__c = 'Followup Report', Project__c = projlist[0].Id);
    	vstList.add(vst);
    	insert vstList;
    	
        //Start the Test Class
        System.Test.startTest();
        
        //Instantiate the Page of RBI_AddInfraNearProject
        PageReference rbiInfrapage = Page.RBI_AddInfraNearProject;
		System.Test.setCurrentPage(rbiInfrapage);
		Apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id);
		Apexpages.currentpage().getparameters().put('ProjName' , projlist[0].Project_Name__c);
		Apexpages.currentpage().getparameters().put('VstId' , vstList[0].Id);
		//Instantiate the class which is used in the page above
		RBI_AddInfraNearProject infranearproject = new RBI_AddInfraNearProject();
		infranearproject.ProjectId = Apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id);
		infranearproject.ProjectName = Apexpages.currentpage().getparameters().put('ProjName' , projlist[0].Project_Name__c);
		//infranearproject.VisitId = Apexpages.currentpage().getparameters().put('VstId' , vstList[0].Id);
		infranearproject.getListofValues();
		infranearproject.WrapperListofval[0].selected=true;
		infranearproject.dosave();
		infranearproject.doCancel();
		
		//Instantiate the class which is used in the page above
		RBI_AddInfraNearProject infranearproject1 = new RBI_AddInfraNearProject();
		infranearproject1.ProjectId=null;
		infranearproject1.VisitId = Apexpages.currentpage().getparameters().put('VstId' , vstList[0].Id);
		infranearproject1.getListofValues();
		infranearproject1.WrapperListofval[0].selected=true;
		infranearproject1.dosave();
		infranearproject1.doCancel();
		
		
		//Instantiate the Page of RBI_AddPaymentPlan
		PageReference rbiAddPayPlan = Page.RBI_AddPaymentPlan;
		System.Test.setCurrentPage(rbiAddPayPlan);
		Apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id);
		Apexpages.currentpage().getparameters().put('ProjName' , projlist[0].Project_Name__c);
		
		//Instantiate the class which is used in the page above
		RBI_AddPaymentPlan rbipayplan = new RBI_AddPaymentPlan();
		rbipayplan.ProjectId = Apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id);
		rbipayplan.ProjectName = Apexpages.currentpage().getparameters().put('ProjName' , projlist[0].Project_Name__c);
		rbipayplan.getListofValues();
		rbipayplan.WrapperListofval[0].selected=true;
		rbipayplan.dosave();
		rbipayplan.doCancel();
		
		//Instantiate the Page of RBI_AddPDRList
		PageReference rbiAddPDR = Page.RBI_AddPDRList;
		System.Test.setCurrentPage(rbiAddPDR);
		Apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id);
		Apexpages.currentpage().getparameters().put('VisId' , vstList[0].Id);
		
		//Instantiate the class which is used in the page above
		RBI_AddPDRList addPDR = new RBI_AddPDRList();
		addPDR.ProjectId = Apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id);
		addPDR.VisitId = Apexpages.currentpage().getparameters().put('VisId' , vstList[0].Id);
		addPDR.getListofValues();
		addPDR.dosave();
		addPDR.doCancel();
		
		//Instantiate the Page of RBI_AddProjectFeedback
		PageReference rbiProjFeed = Page.RBI_AddProjectFeedback;
		System.Test.setCurrentPage(rbiProjFeed);
		Apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id);
		Apexpages.currentpage().getparameters().put('ProjName' , projlist[0].Project_Name__c);
		//Apexpages.currentpage().getparameters().put('VstId' , projlist[0].Project_Name__c);
		
		//Instantiate the class which is used in the page above
		RBI_AddProjectFeedback rbiProjFeedback = new RBI_AddProjectFeedback();
		rbiProjFeedback.ProjectId = Apexpages.currentpage().getparameters().put('ProjId' , projlist[0].Id);
		rbiProjFeedback.ProjectName = Apexpages.currentpage().getparameters().put('ProjName' , projlist[0].Project_Name__c);
		//rbiProjFeedback.VisitId = Apexpages.currentpage().getparameters().put('VstId' , vstList[0].Id);
		rbiProjFeedback.getListofValues();
		rbiProjFeedback.WrapperListofval[0].selected=true;
		rbiProjFeedback.dosave();
		rbiProjFeedback.doCancel();
		Apexpages.currentpage().getparameters().put('VstId' , vstList[0].Id);
		RBI_AddProjectFeedback rbiProjFeedback1 = new RBI_AddProjectFeedback();
		rbiProjFeedback1.ProjectId=null;
		rbiProjFeedback1.VisitId = Apexpages.currentpage().getparameters().put('VstId' , vstList[0].Id);
		rbiProjFeedback1.getListofValues();
		rbiProjFeedback1.WrapperListofval[0].selected=true;
		rbiProjFeedback1.dosave();
		rbiProjFeedback1.doCancel();
		
		
		
		//Stop the Test Class
		System.Test.stopTest();
    }
}