Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Towers</relationshipLabel>
        <relationshipName>Towers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Floor__c</fullName>
        <label>Floor</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Super_Area_Sq_Ft__c</fullName>
        <formula>TEXT(Unit_Type_Id__r.Super_Area_Sq_Ft__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Super Area (Sq Ft)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tower_Id__c</fullName>
        <label>Tower Id</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Type_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Type Id</label>
        <referenceTo>Unit_Type__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <formula>TEXT(Unit_Type_Id__r.Unit_Type__c)</formula>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit_Type__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Unit Type</relationshipLabel>
        <relationshipName>Unit_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Super_Area_Sq_Ft__c</fullName>
        <label>Super Area (Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <label>Unit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Service Appt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penthouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2BHK+ STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK+ STUDY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Unit Type</label>
    <nameField>
        <displayFormat>UNITTYP-{0000000000}</displayFormat>
        <label>Unit Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_CreateUnits.cls
/*
    Type:       Custom Controller
    Purpose:    Used to create multiple units for a Tower in the Employee application.        

    Used By:   RBI_CreateUnits.page
    ---------------------------------------------------------------
    History:

    08-May-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_CreateUnits {
	
   	public String Floor   {get; set;}             // Used to input searchfields
   	public Id selectedUnitType {get;set;}
   	public integer unitCount       {get; set;} 
   	public List<SelectOption> uTypeOptions {get; set;}
   	public list<Unit__c> UnitList;
   	public list<Unit_Type__c> UnitTypes {get;set;}
   	public Tower__c TowerRec   {get;set;}
   	public Unit__c objunit {get;set;}
   	public string ProjectId;
   	public string TowerName {get;set;}
   	public string towerId;
   	public decimal SuperArea {get;set;}
   	Map<ID,Unit_Type__c> UnitTypeMap;
   	integer towerunitcount; // used to populate unique name on unit
   	   	
   	public RBI_CreateUnits(){
       ProjectId = System.currentPagereference().getParameters().get('ProjId');
       	TowerName = System.currentPagereference().getParameters().get('TowName');
       	towerId = System.currentPagereference().getParameters().get('TowId');
       	towerunitcount = 0;
       	towerunitcount = (System.currentPagereference().getParameters().get('unittotal')!=null)?Integer.valueOf(System.currentPagereference().getParameters().get('unittotal')):0;
       	uTypeOptions = new List<SelectOption>() ;
        list<Unit__c>   UnitList = new list<Unit__c>();
        objunit = new Unit__c();
        unitCount = 0;
      	getunitTypeOptions();
      	
	}
     
    public void getUnitTypeOptions(){
    	UnitTypeMap = new Map<ID, Unit_Type__c>([select name, Unit_Type__c, Project__c, Super_Area_Sq_Ft__c from Unit_Type__c where Project__c = : ProjectId]);
    	if(UnitTypeMap!=null)
    		UnitTypes = UnitTypeMap.values(); 
		//UnitTypes = [select name, Unit_Type__c, Project__c, Super_Area_Sq_Ft__c from Unit_Type__c where Project__c = : ProjectId];
		if (UnitTypes != null && UnitTypes.Size() >0){
			for(Unit_Type__c unitType:UnitTypes){
		     	uTypeOptions.add(new SelectOption(unitType.Id,unitType.Unit_Type__c +' - '+unitType.Super_Area_Sq_Ft__c + ' sqft'));
	   		}
	   		SuperArea = UnitTypes[0].Super_Area_Sq_Ft__c;
		}
		
	}
	
	public pageReference doCreate(){
		list<Unit__c>   UnitList = new list<Unit__c>();
		Integer i=0;
		string unitname = '';
		for (i=0; i<unitCount; i++){
			towerunitcount = towerunitcount+1;
			unitname = 'To be changed-'+ string.valueOf(towerunitcount);
			UnitList.add(new Unit__c(Name = unitname, Tower_Id__c = towerId, Floor__c = objunit.Floor__c, Unit_Type_Id__c = selectedUnitType));
			system.debug('AAAAA'+UnitList[i].Id);
			
		}
		if (UnitList != null){
			try{
				insert UnitList;
			}catch(DMLException e){
				ApexPages.addMessages(e);
				return null;
			}
			PageReference Pg = new PageReference('/' + towerId);
			return Pg;
		}
		return null;
	}
	
	public pageReference doCreateandNew(){
		list<Unit__c>   UnitList = new list<Unit__c>();
		string unitname = '';
		Integer i=0;
		for (i=0; i<unitCount; i++){
			towerunitcount = towerunitcount+1;
			unitname = 'To be changed-'+ string.valueOf(towerunitcount);
			//unitname = 'To be changed-' + towerunitcount;			
			UnitList.add(new Unit__c(Name = unitname, Tower_Id__c = towerId, Floor__c = objunit.Floor__c, Unit_Type_Id__c = selectedUnitType));
			
		}
		if (UnitList != null){
			try{
				insert UnitList;
			}catch(DMLException e){
				ApexPages.addMessages(e);
				return null;
			}	
			objunit = new Unit__c();
			string strcount = (towerunitcount!=null)?String.valueOf(towerunitcount):'';
			PageReference Pg = ApexPages.currentPage();
			pg.getParameters().put('ProjId',ProjectId);
			pg.getParameters().put('TowName',TowerName);
			pg.getParameters().put('TowId',towerId);
			pg.getParameters().put('unittotal',strcount);
			Pg.setRedirect(true);
			return Pg;
		}
		return null;
	}
	
	public PageReference doCancel(){
		PageReference Pg = new PageReference('/' + towerId);
		return Pg;
    }
	//Used for action function call to populate super area on change of unit type
    public void populateSuperArea(){
    	system.debug('selectedUnitTypeXX'+selectedUnitType+'  '+UnitTypeMap);
 		if(selectedUnitType != null){
    		Unit_Type__c ut = UnitTypeMap.get(selectedUnitType);
    		if(ut!=null){
    			SuperArea = ut.Super_Area_Sq_Ft__c;
    		}
		}
		//return null;
    }    
}