Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is to capture Surveyor from User Object.</description>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Head</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TechnicalHead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <formula>LOWER( Project_Name__c &amp; TEXT( Site_Address_City__c )  &amp;  Developer_Id__r.Name )</formula>
        <label>Unique Key</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Covering_Cities__c</fullName>
        <label>Covering Cities</label>
        <picklist>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rsamos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secunderabad</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Project_Auto_Num__c</fullName>
        <description>This will capture the auto number field from the associated project.</description>
        <formula>Project__r.Name</formula>
        <label>Project Auto Num</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Site_City__c</fullName>
        <description>This will capture Project Site City.</description>
        <formula>TEXT(Project__r.Site_Address_City__c)</formula>
        <label>Project Site City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Surveyor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Head__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will capture operation manager. This field is used when the owner is changed in the visit. The value will be same as in the project object</description>
        <label>Operation Mgr Data</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <description>Used for (Visit)duplicate check in trigger.</description>
        <formula>LOWER(  Project_Auto_Num__c  &amp;  TEXT(Visit_Report__c ))</formula>
        <label>Unique Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Followup</fullName>
        <active>true</active>
        <description>For Followup Visit</description>
        <label>Followup</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <description>Used for Project level visits</description>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_VisitOwnerChangeTrighandler.cls
public without sharing class RBI_VisitOwnerChangeTrighandler{
    public Static boolean FirstUpdate = true;
    list<Visit__c> visitListForUpdate = new list<Visit__c>();
    
    public void OnBeforeUpdate(list<Visit__c>  visNew, list<Visit__c>  visOld, Map<Id, Visit__c> ObjectMap){
        if(FirstUpdate){
            FirstUpdate = false;
            list<Visit__c> ListforUpdate = new list<Visit__c>();
            for(Visit__c vNew : visNew){
                if(vNew.Id ==  ObjectMap.get(vNew.Id).Id && (vNew.ownerId != ObjectMap.get(vNew.Id).ownerId)){
                    if(vNew.Visit_Report__c == 'DVU Report' || vNew.Visit_Report__c == 'TSR Report')
                        vNew.Technical_Head__c = vNew.ownerId;
                    else
                        vNew.Surveyor__c = vNew.ownerId;
                }
                if(vNew.Id == ObjectMap.get(vNew.Id).Id && ObjectMap.get(vNew.Id).Project_Auto_Num__c != vNew.Project_Auto_Num__c && vNew.Visit_Report__c != 'Followup Report'){
    	            ListforUpdate.add(vNew);
    	        }
    	        else if(vNew.Id == ObjectMap.get(vNew.Id).Id && ObjectMap.get(vNew.Id).Visit_Report__c != vNew.Visit_Report__c && vNew.Visit_Report__c != 'Followup Report'){
    	            ListforUpdate.add(vNew);
    	        }
    	        //function call to check duplicate project records
                if(ListforUpdate!=null && ListforUpdate.size()>0){
                    hasDuplicates(ListforUpdate); 
                }
            }
        }
    }
    
    public void OnbeforeInsert(list<Visit__c>  visNew){
    	set<String> siteCity = new set<String>();
        String siteCityString = '';
        map<String, User> userlst = new map<String, User>();
        list<Visit__c> visitListIns = new list<Visit__c>();   
        
        for(Visit__c vis : visNew){
        	if(vis.Project_Site_City__c != null && (siteCity.add(vis.Project_Site_City__c)) && (vis.Visit_Report__c == 'TSR Report' || vis.Visit_Report__c == 'DVU Report'))
		        siteCityString += '\''+vis.Project_Site_City__c+'\',';
		    if(vis.Project__c != null && vis.Visit_Report__c != 'Followup Report'){
		    	visitListIns.add(vis);
		    }    
        }
        if(siteCityString != null && siteCityString != '')
	        siteCityString = siteCityString.substring(0, siteCityString.length()-1); 
	    system.debug('xxxxxxxxxxx'+siteCityString);
        userlst = queryUser(siteCityString);
        for(Visit__c vis : visNew){
            if(vis.Visit_Report__c == 'TSR Report' || vis.Visit_Report__c == 'DVU Report'){
	            String OperationMgrKey = vis.Project_Site_City__c+'-Operation Mgr - Data';
	            if(vis.Project_Site_City__c != null){
		            if(userlst.containsKey(OperationMgrKey) && userlst.get(OperationMgrKey).UserRole.Name == 'Operation Mgr - Data'){
	                	vis.Technical_Head__c = userlst.get(OperationMgrKey).Id;
	                }else{
	                  	vis.Technical_Head__c = system.Label.RBI_DefaultPASMgrId; 
	                } 
	                
	            }
	            vis.OwnerId = vis.Technical_Head__c;
            }
        }
        if(visitListIns!=null && visitListIns.size()>0){
            //Need to check for uniqueness for Developer accounts	
        	hasDuplicates(visitListIns);
        }
    }
    
    public map<String, User> queryUser(String siteCity){
		list<User> userList = new list<User>();
	    system.debug('qqqqqqqqqq'+siteCity);
	    if(siteCity != null && siteCity != ''){	
	     	String userQuery = 'select name, UserRole.Name, Covering_Cities__c, City from User';
			userQuery += ' where (Covering_Cities__c INCLUDES (' + siteCity + ')) and (UserRole.Name = \'Operation Mgr - Data\')';
			system.debug('++++++++'+userQuery);
			userList = database.query(userQuery);
	    }
	    system.debug('yyyyyyyyyyy'+userList);
	    map<String, User> userMap = new map<String, User>();
	    for(User us : userList){
	       	if(us.Covering_Cities__c != null){
	       		list<String> cityList = us.Covering_Cities__c.split(';');
		        for(String strCity : cityList){
		           	userMap.put(strCity+'-'+us.UserRole.Name, us);
		        }
	       	}
	    } 
	    system.debug('asdf'+userMap);
	    return userMap;
    }
    
    // This method acts as a uniqueness checker for the Visit for a project
    private  void hasDuplicates(Visit__c[] Visitlst){
        //Define a map for unique Projects
        Map <String,Visit__c> visMap = new Map<String, Visit__c> ();
        for (Visit__c vis: Visitlst) {
                String projName     = (vis.Project_Auto_Num__c==null)?'':vis.Project_Auto_Num__c.toLowerCase();
                String visitType     = (vis.Visit_Report__c==null)?'':vis.Visit_Report__c.toLowerCase();
                String ukey = projName + visitType;
                if (visMap.containsKey(ukey)) {
                    vis.addError('Visit record with the same type already exists in the system');
                }
                else visMap.put(ukey,vis);
        }
        //Check DB for dupes
        if (!visMap.isEmpty()){  
            for(Visit__c[] visCheck:[select Id, Unique_Key__c from Visit__c where Unique_Key__c IN :visMap.keySet()]) {
                for(Visit__c vis:visCheck) {
                    String currentId = vis.Id;
                    //if there's a dupe and this isn't the current record, then add the error.
                    if(visMap.containsKey(vis.Unique_Key__c) && (currentId != visMap.get(vis.Unique_Key__c).Id)) {
                        visMap.get(vis.Unique_Key__c).addError('Visit record with the same type already exists in the system');
                    }
                }
            }
        }
    }
}