Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Brochure_Zipcode__c</fullName>
        <label>Brochure Zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Land_Area_in_acres__c</fullName>
        <description>Stores the Land Area used for the development of the project</description>
        <label>Land Area (in Acres)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Address_City__c</fullName>
        <label>Site Address City</label>
        <picklist>
            <controllingField>Site_Address_State__c</controllingField>
            <picklistValues>
                <fullName>Agra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ahmedabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alwar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahadurgarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwani</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhiwari</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chandigarh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delhi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuheda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dharuhera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faridabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gachar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghaziabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ghazipur</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gurgaon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hyderabad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Karnal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manesar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meerut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mohali</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mumbai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neemrana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Noida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Palwal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panchkula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panipat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pune</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Address_zipcode__c</fullName>
        <label>Site Address zipcode</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site_Visit_Date__c</fullName>
        <label>Last Visit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Field to hold the status of the project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PDS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PQR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Project_Document_Status__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Approval__c</fullName>
        <label>Date of Approval</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project_Id__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provided_By_Bank__c</fullName>
        <label>Provided By Bank</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store relationship with Visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipName>Project_Document_Status</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Document</label>
    <nameField>
        <displayFormat>DOC-{0000000000}</displayFormat>
        <label>Document Status Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Query__c.object
<CustomObject>
    <description>Stores the Document Queries</description>
    <fields>
        <fullName>Project_Document_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship between Project Document Status</description>
        <label>Project Document</label>
        <referenceTo>Project_Document_Status__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>IF( ISBLANK(Visit__c),  Customer_Project__r.Project_Id__r.Project_Name__c, Visit__r.Project__r.Project_Name__c)</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_Description__c</fullName>
        <description>used as Description field for both query and Exception.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores relationship  between  Visit and  Queries/Exception</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Queries/Exceptions</relationshipLabel>
        <relationshipName>Queries_Exceptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Query/Exception</label>
    <nameField>
        <displayFormat>Qr-{0000}</displayFormat>
        <label>Query Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries/Exceptions</pluralLabel>
    <recordTypes>
        <fullName>Query</fullName>
        <active>true</active>
        <description>Record type for  Query/Execption object</description>
        <label>Query</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to check any Exceptions  are  there  for a visit.</description>
        <label>Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Project__r.Project_Name__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores relationship with Project</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Forwarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Positive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Report__c</fullName>
        <label>Visit Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Technical Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVU Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSR Report</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to relate Tower visit to the respective project visit</description>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>ProjVis-{0000000000}</displayFormat>
        <label>Visit Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_DocQryDetailsTestClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(SeeAllData=true)
private class RBI_DocQryDetailsTestClass {

    static testMethod void DocQryDetails() {
    	
    	list<Project__c> projlist = new list<Project__c>();
		Project__c proj = new Project__c(Project_Name__c='Test Class', Land_Area_in_acres__c=30.00, Site_Visit_Date__c = System.Today(),
										 City__c ='test', Brochure_Zipcode__c = '412578', Site_Address_zipcode__c = '123456', 
										 Site_Address_City__c = 'Bangalore', Launch_Date__c = System.today());
		projlist.add(proj);
		insert projlist;
        
        list<Visit__c> vstList = new list<Visit__c>();
    	Visit__c vst = new Visit__c(Status__c = 'Approved', Visit_Report__c = 'First Technical Report', Exception__c = true, Project__c = projlist[0].Id);
    	vstList.add(vst);
    	insert vstList;
        
        list<Project_Document_Status__c> prjDoc = new list<Project_Document_Status__c>();
        Project_Document_Status__c prjDocStat = new Project_Document_Status__c(Date_of_Approval__c = System.today(), Provided_By_Bank__c = 'Yes',
        										Visit__c = vstList[0].Id);
        prjDoc.add(prjDocStat);
        insert prjDoc;
        
        list<Query__c> query = new list<Query__c>();
        Query__c qry = new Query__c(Project_Document_Status__c = prjDoc[0].Id, Query_Description__c = 'TestDescription', Visit__c = vstList[0].Id);
        query.add(qry);
        insert query;
        
        
         //start test class method
       	System.Test.startTest();
        
       	//Instantiate the RBI_VisitDetails
		PageReference rbiDocQry = Page.RBI_VisitDetails;
		System.Test.setCurrentPage(rbiDocQry);
		
		//Instantiate the class which is used in the page above
		Apexpages.currentpage().getparameters().put('Id' ,vstList[0].Id);
		ApexPages.StandardController stdCon = new ApexPages.StandardController(vst);
		RBI_DocQryDetails DocQry = new RBI_DocQryDetails(stdCon);
		DocQry.allQryList = prjDoc;
		DocQry.selectRow();
		DocQry.docId = prjDoc[0].Id;
		String qId = query[0].Id;
		DocQry.getqueryList(qId);
		
		//Stop Test Class
		System.Test.stopTest();
    }
}