Dev-RBI/src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Launch_Date__c</fullName>
        <label>Launch Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_No_of_Towers__c</fullName>
        <label>Planned No of Towers</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{000000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Yathi-UC/src/classes/ProjectTowerExt_Test.cls
@isTest(SeeAllData=true)
private class ProjectTowerExt_Test {

    static testMethod void myUnitTest() {
     
     project__c pro=new project__c();
      pro.Projects_Name__c='testing'; 
     
     pro.Launch_Date__c= system.today();
     pro.Plot_Area_in_Acres__c=5;

     insert pro;
    
     
     
     
      system.Test.startTest();
      Pagereference pg=page.ProjectTowerExtension;
      System.test.setCurrentPage(pg);
      
      Apexpages.Standardcontroller std=new Apexpages.Standardcontroller(pro);
      
      ProjectTowerExt pttst = new ProjectTowerExt(std);
      
      pttst.addTower();
     /* pttst.Pro.Projects_Name__c = 'Yathi1';
      pttst.Pro.Planned_No_Of_Towers__c = 5; */
      pttst.save();
      system.Test.stopTest();
      
      
      
      
    }
}