Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Built_up_area_Sq_Ft__c</fullName>
        <formula>TEXT(Unit_Type_Id__r.Built_up_area_Sq_Ft__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Built up area (Sq Ft)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carpet_Area_Sq_Ft__c</fullName>
        <formula>TEXT(Unit_Type_Id__r.Carpet_Area_Sq_Ft__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Carpet Area (Sq Ft)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tower_Id__c</fullName>
        <label>Tower Id</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Type_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Type Id</label>
        <referenceTo>Unit_Type__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <formula>TEXT(Unit_Type_Id__r.Unit_Type__c)</formula>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit_Type__c.object
<CustomObject>
    <fields>
        <fullName>Built_up_area_Sq_Ft__c</fullName>
        <label>Built up area (Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Carpet_Area_Sq_Ft__c</fullName>
        <label>Carpet Area (Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <label>Unit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Service Appt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penthouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2BHK+ STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK+ STUDY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Unit Type</label>
    <nameField>
        <displayFormat>UNITTYP-{0000000000}</displayFormat>
        <label>Unit Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_TowerUnittypeCount.cls
/*
    Type:       Custom Controller
    Purpose:    Used to calculate the number of Unit Types for each tower in Employee Application.     

    Used By:   RBI_TowerUnitTypeCount.page
    ----------------------------------------------------------------------------------
    History:

    01-May-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_TowerUnittypeCount {
	
	public list<aggregateResult> UnitList{get; set;}
	public list<floorStrucWrap> floorWrapForPDF {get;set;}
	public string towerId ='';
    
    //Constructor
    public RBI_TowerUnittypeCount(ApexPages.standardController std){
        towerId=Apexpages.currentPage().getParameters().get('id');
        UnitList = new list<aggregateResult>();
        floorWrapForPDF = new list<floorStrucWrap>();
        unitlist = [Select Unit_Type_Id__r.Unit_Type__c unittyp, Tower_Id__r.Name towername, COUNT(Name) cou, MAX(Unit_Type_Id__r.Carpet_Area_Sq_Ft__c) CarpetArea,
							MAX(Unit_Type_Id__r.Built_up_area_Sq_Ft__c) builtuparea From Unit__c 
							WHERE  Tower_Id__c =: towerid
							GROUP BY Tower_Id__r.Name, Unit_Type_Id__r.Unit_Type__c];
			
		if (unitlist.size() != null){
			for(aggregateResult aggRes : unitlist){
				String towname = '';
				String unitType = '';
				Integer noOfUnit;
				Double cpparam;
				Double builtparam;
				
				towname  = (String) aggRes.get('towername');
				unitType = (String) aggRes.get('unittyp');
				noOfUnit = (Integer) aggRes.get('cou');
				cpparam = (Double) aggRes.get('CarpetArea');
				builtparam = (Double) aggRes.get('builtuparea');	
				
				floorWrapForPDF.add(new floorStrucWrap(towname, unitType, noOfUnit, cpparam, builtparam));
					
       		}
		}
    }
	
	public class floorStrucWrap{
    	public String towname        {get;set;}
    	public String unitType     {get;set;} 
    	public Integer noOfUnits   {get;set;}
    	public Double carpetarea  {get;set;}
    	public Double builtuparea {get;set;}    	    	
    	public floorStrucWrap(String tname, String unitTyp, Integer noOfUni, Double cparea,Double btarea){
    		towname = tname;
    		unitType = unitTyp;
    		noOfUnits = noOfUni;
    		carpetarea = cparea;
    		builtuparea = btarea;
    	}
    }
}