Dev-RBI/src/objects/Tower__c.object
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Built_up_area_Sq_Ft__c</fullName>
        <formula>TEXT(Unit_Type_Id__r.Built_up_area_Sq_Ft__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Built up area (Sq Ft)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Carpet_Area_Sq_Ft__c</fullName>
        <formula>TEXT(Unit_Type_Id__r.Carpet_Area_Sq_Ft__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Carpet Area (Sq Ft)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Floor_Number__c</fullName>
        <formula>VALUE(TEXT( Floor__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Floor Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Floor__c</fullName>
        <label>Floor</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Super_Area_Sq_Ft__c</fullName>
        <formula>TEXT(Unit_Type_Id__r.Super_Area_Sq_Ft__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Super Area (Sq Ft)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tower_Id__c</fullName>
        <label>Tower Id</label>
        <referenceTo>Tower__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Type_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Type Id</label>
        <referenceTo>Unit_Type__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <formula>TEXT(Unit_Type_Id__r.Unit_Type__c)</formula>
        <label>Unit Type</label>
        <type>Text</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dev-RBI/src/objects/Unit_Type__c.object
<CustomObject>
    <fields>
        <fullName>Built_up_area_Sq_Ft__c</fullName>
        <label>Built up area (Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Carpet_Area_Sq_Ft__c</fullName>
        <label>Carpet Area (Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Super_Area_Sq_Ft__c</fullName>
        <label>Super Area (Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <label>Unit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Service Appt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK + STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 BHK + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 BHK + STUDY + SERVANT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6BHK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penthouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2BHK+ STUDY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5BHK+ STUDY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Unit Type</label>
    <nameField>
        <displayFormat>UNITTYP-{0000000000}</displayFormat>
        <label>Unit Type Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Type</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev-RBI/src/classes/RBI_MassEditCustomUnits.cls
/*
    Type:       Custom Controller
    Purpose:    Used to Approve the Projects created by the Customer from Customer Portal.

    Used By:   RBI_MassEditCustomUnits.page
    ----------------------------------------------------------------------------------
    History:

    01-May-2013     Created		Tugboat Info Solutions Pvt. Ltd

*/
public with sharing class RBI_MassEditCustomUnits {
	// Variable Declaration
	public list<Unit__c> WrapperUnitList {get; set;}

 	transient String  QryString;
 	public Unit__c 	  uni12;
	public string     TowId = '';

	public boolean    ErrorFlag {get; set;}
	public boolean    flag {get; set;}

	public list<Unit__c> Showunit{set;get;}
	public integer sizee{get;set;}
	public string TowName{get;set;}

	//Pagination
	public RBI_PageManager objPageManager {get;set;}
	public Integer pageSize;
	public List<Unit__c> Wrapper1untlist{get;set;}
	public List<Unit__c> unitList = new List<Unit__c>();
	public List<Unit__c> unitDetails;

	/* Constructor */
    public RBI_MassEditCustomUnits(){
        WrapperUnitList = new list<Unit__c>();
        Wrapper1untlist = new List<Unit__c>();
       	ErrorFlag       = false;
        unitList 		= new list<Unit__c>();
        TowId			= System.currentPagereference().getParameters().get('TowerId');
        TowName			= System.currentPagereference().getParameters().get('TowerName');
      	//paging variables
		pageSize = 16;
        objPageManager = new RBI_PageManager(pageSize);
        objPageManager.page = 0;
        objPageManager.numberOfRows =0;

}

    /* Action funtion called on initial load */
	public PageReference InitialLoad(){
		unitList 		= new list<Unit__c>();
		unitList = [Select Name,Unit_Type__c, Unit_Type_Id__c, Super_Area_Sq_Ft__c, Id, Floor__c,Floor_Number__c, Carpet_Area_Sq_Ft__c, 
					Built_up_area_Sq_Ft__c,Tower_Id__r.Name From Unit__c where Tower_Id__c=:TowId order by Floor_Number__c ];
        WrapperUnitList = new list<Unit__c>();
        Showunit = new list<Unit__c>();
  		WrapperUnitList.addAll(unitList);
		Showunit.addAll(unitList);
		if(WrapperUnitList!= null){
			sizee=WrapperUnitList.size();
			objPageManager.numberOfRows = WrapperUnitList.size();
		}


		return null;
	}
    /* Action funtion called on Save button */
	public PageReference saveunits(){
		if(unitList!=null && unitList.size()>0){
			update unitList;
        	PageReference Pg = Page.RBI_MassEditCustomUnits;
    		pg.getParameters().put('TowerId',TowId);
    		Pg.setRedirect(true);
    		return Pg;			
		}

		return null;
	}
    /* Action funtion called on cancel button */
	public PageReference cancelunits(){
	 		PageReference pageRef = new PageReference('/'+TowId);
	 		return pageRef;		
	}			
    // Getter-setter for unitDetails used for pagination
  	public List<Unit__c> getunitDetails(){
  	if((WrapperUnitList !=null) && (WrapperUnitList.size() >0)){
      	 if(Wrapper1untlist !=null)
       		Wrapper1untlist.clear();
        	for(integer i=objPageManager.startIndex;i<objPageManager.endIndex&&i<WrapperUnitList.size();i++){
            	Wrapper1untlist.add(WrapperUnitList.get(i));

         }

      }
       return Wrapper1untlist;
    }

	public void  setunitDetails (List<Unit__c> unitDetails) {
		this.unitDetails = unitDetails;
	}

}